// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 49cdd5b57409

package operations

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"net/http"
)

type AutomationListIdentityProvidersGlobals struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `pathParam:"style=simple,explode=false,name=envId"`
}

func (a *AutomationListIdentityProvidersGlobals) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationListIdentityProvidersGlobals) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

type AutomationListIdentityProvidersRequest struct {
	// null
	OrganizationID *string `pathParam:"style=simple,explode=false,name=orgId"`
	// null
	EnvironmentID *string `pathParam:"style=simple,explode=false,name=envId"`
	// Key of the domain: its stable, immutable Automation identifier within the environment.
	DomainKey string `pathParam:"style=simple,explode=false,name=domainKey"`
}

func (a *AutomationListIdentityProvidersRequest) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationListIdentityProvidersRequest) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

func (a *AutomationListIdentityProvidersRequest) GetDomainKey() string {
	if a == nil {
		return ""
	}
	return a.DomainKey
}

type AutomationListIdentityProvidersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of identity providers
	AutomationIdentityProviders []shared.AutomationIdentityProvider
	// Permission denied
	Error *shared.Error
}

func (a *AutomationListIdentityProvidersResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutomationListIdentityProvidersResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutomationListIdentityProvidersResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutomationListIdentityProvidersResponse) GetAutomationIdentityProviders() []shared.AutomationIdentityProvider {
	if a == nil {
		return nil
	}
	return a.AutomationIdentityProviders
}

func (a *AutomationListIdentityProvidersResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
