// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d95207d3c9d0

package operations

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"net/http"
)

type AutomationDeleteCertificateRequest struct {
	// Identifier of the organization that owns the environment.
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment the domain belongs to.
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// Key of the domain: its stable, immutable Automation identifier within the environment.
	DomainKey string `pathParam:"style=simple,explode=false,name=domainKey"`
	// Key of the certificate within the domain.
	CertKey string `pathParam:"style=simple,explode=false,name=certKey"`
}

func (a *AutomationDeleteCertificateRequest) GetOrgID() string {
	if a == nil {
		return ""
	}
	return a.OrgID
}

func (a *AutomationDeleteCertificateRequest) GetEnvID() string {
	if a == nil {
		return ""
	}
	return a.EnvID
}

func (a *AutomationDeleteCertificateRequest) GetDomainKey() string {
	if a == nil {
		return ""
	}
	return a.DomainKey
}

func (a *AutomationDeleteCertificateRequest) GetCertKey() string {
	if a == nil {
		return ""
	}
	return a.CertKey
}

type AutomationDeleteCertificateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Permission denied
	Error *shared.Error
}

func (a *AutomationDeleteCertificateResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutomationDeleteCertificateResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutomationDeleteCertificateResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutomationDeleteCertificateResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
