// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 26ffb6354e03

package operations

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"net/http"
)

type AutomationDeleteDomainGlobals struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `pathParam:"style=simple,explode=false,name=envId"`
}

func (a *AutomationDeleteDomainGlobals) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationDeleteDomainGlobals) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

type AutomationDeleteDomainRequest struct {
	// null
	OrganizationID *string `pathParam:"style=simple,explode=false,name=orgId"`
	// null
	EnvironmentID *string `pathParam:"style=simple,explode=false,name=envId"`
	// Key of the domain: its stable, immutable Automation identifier within the environment.
	Key string `pathParam:"style=simple,explode=false,name=domainKey"`
}

func (a *AutomationDeleteDomainRequest) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationDeleteDomainRequest) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

func (a *AutomationDeleteDomainRequest) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

type AutomationDeleteDomainResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Permission denied
	Error *shared.Error
}

func (a *AutomationDeleteDomainResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutomationDeleteDomainResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutomationDeleteDomainResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutomationDeleteDomainResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
