// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c74d0a02179c

package operations

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"net/http"
)

type AutomationCreateOrUpdateDomainGlobals struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `pathParam:"style=simple,explode=false,name=envId"`
}

func (a *AutomationCreateOrUpdateDomainGlobals) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationCreateOrUpdateDomainGlobals) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

type AutomationCreateOrUpdateDomainRequest struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `pathParam:"style=simple,explode=false,name=envId"`
	// Desired state of the domain.
	AutomationDomain shared.AutomationDomainInput `request:"mediaType=application/json"`
}

func (a *AutomationCreateOrUpdateDomainRequest) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationCreateOrUpdateDomainRequest) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

func (a *AutomationCreateOrUpdateDomainRequest) GetAutomationDomain() shared.AutomationDomainInput {
	if a == nil {
		return shared.AutomationDomainInput{}
	}
	return a.AutomationDomain
}

type AutomationCreateOrUpdateDomainResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The created or updated domain
	AutomationDomain *shared.AutomationDomain
	// Invalid request: validation failure, an immutable field change, a key that already exists for a domain not managed by the Automation API, or an unknown defaultIdentityProviderForRegistration reference
	Error *shared.Error
}

func (a *AutomationCreateOrUpdateDomainResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutomationCreateOrUpdateDomainResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutomationCreateOrUpdateDomainResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutomationCreateOrUpdateDomainResponse) GetAutomationDomain() *shared.AutomationDomain {
	if a == nil {
		return nil
	}
	return a.AutomationDomain
}

func (a *AutomationCreateOrUpdateDomainResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
