// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 24cf40ea660a

package operations

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"net/http"
)

type AutomationListDomainsGlobals struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `pathParam:"style=simple,explode=false,name=envId"`
}

func (a *AutomationListDomainsGlobals) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationListDomainsGlobals) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

type AutomationListDomainsRequest struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `pathParam:"style=simple,explode=false,name=envId"`
}

func (a *AutomationListDomainsRequest) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationListDomainsRequest) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

type AutomationListDomainsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of domains
	AutomationDomains []shared.AutomationDomain
	// Permission denied
	Error *shared.Error
}

func (a *AutomationListDomainsResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutomationListDomainsResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutomationListDomainsResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutomationListDomainsResponse) GetAutomationDomains() []shared.AutomationDomain {
	if a == nil {
		return nil
	}
	return a.AutomationDomains
}

func (a *AutomationListDomainsResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
