// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cd9074ca96bc

package operations

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"net/http"
)

type AutomationDeleteReporterRequest struct {
	// Identifier of the organization that owns the environment.
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment the domain belongs to.
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// Key of the domain: its stable, immutable Automation identifier within the environment.
	DomainKey string `pathParam:"style=simple,explode=false,name=domainKey"`
	// Key of the reporter within the domain.
	ReporterKey string `pathParam:"style=simple,explode=false,name=reporterKey"`
}

func (a *AutomationDeleteReporterRequest) GetOrgID() string {
	if a == nil {
		return ""
	}
	return a.OrgID
}

func (a *AutomationDeleteReporterRequest) GetEnvID() string {
	if a == nil {
		return ""
	}
	return a.EnvID
}

func (a *AutomationDeleteReporterRequest) GetDomainKey() string {
	if a == nil {
		return ""
	}
	return a.DomainKey
}

func (a *AutomationDeleteReporterRequest) GetReporterKey() string {
	if a == nil {
		return ""
	}
	return a.ReporterKey
}

type AutomationDeleteReporterResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Permission denied
	Error *shared.Error
}

func (a *AutomationDeleteReporterResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutomationDeleteReporterResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutomationDeleteReporterResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutomationDeleteReporterResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
