// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: df66afa20f26

package operations

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"net/http"
)

type AutomationDeleteDataPlaneGlobals struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (a AutomationDeleteDataPlaneGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationDeleteDataPlaneGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationDeleteDataPlaneGlobals) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationDeleteDataPlaneGlobals) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

type AutomationDeleteDataPlaneRequest struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
	// Id of the data plane within the environment.
	DataPlaneID string `pathParam:"style=simple,explode=false,name=dataPlaneId"`
}

func (a AutomationDeleteDataPlaneRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationDeleteDataPlaneRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationDeleteDataPlaneRequest) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationDeleteDataPlaneRequest) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

func (a *AutomationDeleteDataPlaneRequest) GetDataPlaneID() string {
	if a == nil {
		return ""
	}
	return a.DataPlaneID
}

type AutomationDeleteDataPlaneResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Permission denied
	Error *shared.Error
}

func (a *AutomationDeleteDataPlaneResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutomationDeleteDataPlaneResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutomationDeleteDataPlaneResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutomationDeleteDataPlaneResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
