// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dd9377c8a477

package operations

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"net/http"
)

type AutomationGetCertificateRequest struct {
	// Identifier of the organization that owns the environment.
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment the domain belongs to.
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// Key of the domain: its stable, immutable Automation identifier within the environment.
	DomainKey string `pathParam:"style=simple,explode=false,name=domainKey"`
	// Key of the certificate within the domain.
	Key string `pathParam:"style=simple,explode=false,name=certKey"`
}

func (a *AutomationGetCertificateRequest) GetOrgID() string {
	if a == nil {
		return ""
	}
	return a.OrgID
}

func (a *AutomationGetCertificateRequest) GetEnvID() string {
	if a == nil {
		return ""
	}
	return a.EnvID
}

func (a *AutomationGetCertificateRequest) GetDomainKey() string {
	if a == nil {
		return ""
	}
	return a.DomainKey
}

func (a *AutomationGetCertificateRequest) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

type AutomationGetCertificateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The certificate
	AutomationCertificate *shared.AutomationCertificate
	// Permission denied
	Error *shared.Error
}

func (a *AutomationGetCertificateResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutomationGetCertificateResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutomationGetCertificateResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutomationGetCertificateResponse) GetAutomationCertificate() *shared.AutomationCertificate {
	if a == nil {
		return nil
	}
	return a.AutomationCertificate
}

func (a *AutomationGetCertificateResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
