// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 496a50e016cf

package operations

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"net/http"
)

type AutomationListReportersRequest struct {
	// Identifier of the organization that owns the environment.
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment the domain belongs to.
	EnvID string `pathParam:"style=simple,explode=false,name=envId"`
	// Key of the domain: its stable, immutable Automation identifier within the environment.
	DomainKey string `pathParam:"style=simple,explode=false,name=domainKey"`
}

func (a *AutomationListReportersRequest) GetOrgID() string {
	if a == nil {
		return ""
	}
	return a.OrgID
}

func (a *AutomationListReportersRequest) GetEnvID() string {
	if a == nil {
		return ""
	}
	return a.EnvID
}

func (a *AutomationListReportersRequest) GetDomainKey() string {
	if a == nil {
		return ""
	}
	return a.DomainKey
}

type AutomationListReportersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of reporters
	AutomationReporters []shared.AutomationReporter
	// Permission denied
	Error *shared.Error
}

func (a *AutomationListReportersResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AutomationListReportersResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AutomationListReportersResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AutomationListReportersResponse) GetAutomationReporters() []shared.AutomationReporter {
	if a == nil {
		return nil
	}
	return a.AutomationReporters
}

func (a *AutomationListReportersResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
