// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 58538b569570

package sdk

// Generated from OpenAPI doc version 4.12.0-alpha.6 and generator version 2.887.0

import (
	"context"
	"fmt"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/config"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/globals"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/hooks"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	"http://localhost:8093/automation",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// GraviteeAm - Gravitee: Gravitee Access Management Terraform Provider (alpha)
//
// You can manage with Terraform the following:
// * Domains
// * Certificates
// * Identity Providers
// * Reporters
//
// Compatible with Gravitee Access Management 4.12.0.
type GraviteeAm struct {
	SDKVersion string
	// Security domains: the top-level container for an authentication and authorization configuration. Create, read, update, and delete domains, and reach their sub-resources.
	Domains *Domains
	// Certificates configured under a domain to sign and verify tokens.
	Certificates *Certificates
	// Identity providers configured under a domain to authenticate users.
	IdentityProviders *IdentityProviders
	// Reporters configured under a domain to persist audit events to a backend.
	Reporters *Reporters

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*GraviteeAm)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *GraviteeAm) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *GraviteeAm) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *GraviteeAm) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *GraviteeAm) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(security shared.Security) SDKOption {
	return func(sdk *GraviteeAm) {
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (shared.Security, error)) SDKOption {
	return func(sdk *GraviteeAm) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

// WithOrganizationID allows setting the OrganizationID parameter for all supported operations
func WithOrganizationID(organizationID string) SDKOption {
	return func(sdk *GraviteeAm) {
		sdk.sdkConfiguration.Globals.OrganizationID = &organizationID
	}
}

// WithEnvironmentID allows setting the EnvironmentID parameter for all supported operations
func WithEnvironmentID(environmentID string) SDKOption {
	return func(sdk *GraviteeAm) {
		sdk.sdkConfiguration.Globals.EnvironmentID = &environmentID
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *GraviteeAm) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *GraviteeAm) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *GraviteeAm {
	sdk := &GraviteeAm{
		SDKVersion: "0.0.1",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/terraform 0.0.1 2.887.0 4.12.0-alpha.6 github.com/gravitee-io/terraform-provider-am/internal/sdk",
			Globals:    globals.Globals{},
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	currentServerURL, _ := sdk.sdkConfiguration.GetServerDetails()
	serverURL := currentServerURL
	serverURL, sdk.sdkConfiguration.Client = sdk.hooks.SDKInit(currentServerURL, sdk.sdkConfiguration.Client)
	if currentServerURL != serverURL {
		sdk.sdkConfiguration.ServerURL = serverURL
	}

	sdk.Domains = newDomains(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Certificates = newCertificates(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.IdentityProviders = newIdentityProviders(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Reporters = newReporters(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
