// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: df64326fcf31

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
	"time"
)

// AutomationDomain - A security domain managed by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update. Certificates, identity providers, and reporters are not embedded; they are managed via the domain's sub-resource endpoints and referenced here by key.
type AutomationDomain struct {
	// User account settings for the domain: brute-force protection, registration, password reset, remember-me, and MFA challenge behavior.
	AccountSettings *AutomationAccountSettings `json:"accountSettings,omitempty"`
	// Domain-level certificate settings.
	CertificateSettings *AutomationCertificateSettings `json:"certificateSettings,omitempty"`
	// Cross-Origin Resource Sharing configuration controlling which web origins may call the domain's endpoints from a browser.
	CorsSettings *CorsSettings `json:"corsSettings,omitempty"`
	// Creation timestamp (epoch milliseconds). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Identifier of the data plane this domain is connected to. Required at creation and immutable afterwards; included in the desired-state document but never re-applied on update.
	DataPlaneID string `json:"dataPlaneId"`
	// Human-readable description of the domain.
	Description *string `json:"description,omitempty"`
	// Whether the domain handles incoming authentication and authorization requests.
	Enabled *bool `default:"true" json:"enabled"`
	// Stable, immutable identifier for the domain within its environment. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the domain on create-or-update.
	Key string `json:"key"`
	// Configuration of the domain's login flow and the features offered on the sign-in page.
	LoginSettings *LoginSettings `json:"loginSettings,omitempty"`
	// Human-readable name of the domain.
	Name string `json:"name"`
	// OpenID Connect settings for the domain. CIMD (client identity metadata document) settings are not exposed by the Automation API and are reset on update.
	Oidc *AutomationOidcSettings `json:"oidc,omitempty"`
	// Password policy applied to users of the domain: complexity requirements, expiry, and history.
	PasswordSettings *PasswordSettings `json:"passwordSettings,omitempty"`
	// Context path the domain is served under, relative to the gateway. Must start with a slash.
	Path string `json:"path"`
	// Settings for the domain acting as a SAML 2.0 identity provider (IdP).
	Saml *AutomationSamlSettings `json:"saml,omitempty"`
	// Configuration of the domain's SCIM 2.0 provisioning endpoints.
	Scim *SCIMSettings `json:"scim,omitempty"`
	// Controls whether client secrets in the domain expire and after how long.
	SecretExpirationSettings *SecretExpirationSettings `json:"secretExpirationSettings,omitempty"`
	// Controls whether end users can manage their own account (for example, reset their password) and the rules that apply.
	SelfServiceAccountManagementSettings *SelfServiceAccountManagementSettings `json:"selfServiceAccountManagementSettings,omitempty"`
	// Sharding tags that control which gateways deploy this domain.
	Tags []string `json:"tags,omitempty"`
	// OAuth 2.0 Token Exchange (RFC 8693) configuration for the domain, covering impersonation and delegation.
	TokenExchangeSettings *TokenExchangeSettings `json:"tokenExchangeSettings,omitempty"`
	// Configuration of the domain's User-Managed Access (UMA 2.0) authorization features.
	Uma *UMASettings `json:"uma,omitempty"`
	// Last-update timestamp (epoch milliseconds). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Virtual hosts the domain is exposed on, overriding the default context path.
	Vhosts []VirtualHost `json:"vhosts,omitempty"`
	// WebAuthn (FIDO2) relying-party configuration governing passwordless and multi-factor authentication for the domain.
	WebAuthnSettings *WebAuthnSettings `json:"webAuthnSettings,omitempty"`
}

func (a AutomationDomain) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationDomain) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationDomain) GetAccountSettings() *AutomationAccountSettings {
	if a == nil {
		return nil
	}
	return a.AccountSettings
}

func (a *AutomationDomain) GetCertificateSettings() *AutomationCertificateSettings {
	if a == nil {
		return nil
	}
	return a.CertificateSettings
}

func (a *AutomationDomain) GetCorsSettings() *CorsSettings {
	if a == nil {
		return nil
	}
	return a.CorsSettings
}

func (a *AutomationDomain) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AutomationDomain) GetDataPlaneID() string {
	if a == nil {
		return ""
	}
	return a.DataPlaneID
}

func (a *AutomationDomain) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AutomationDomain) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *AutomationDomain) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

func (a *AutomationDomain) GetLoginSettings() *LoginSettings {
	if a == nil {
		return nil
	}
	return a.LoginSettings
}

func (a *AutomationDomain) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AutomationDomain) GetOidc() *AutomationOidcSettings {
	if a == nil {
		return nil
	}
	return a.Oidc
}

func (a *AutomationDomain) GetPasswordSettings() *PasswordSettings {
	if a == nil {
		return nil
	}
	return a.PasswordSettings
}

func (a *AutomationDomain) GetPath() string {
	if a == nil {
		return ""
	}
	return a.Path
}

func (a *AutomationDomain) GetSaml() *AutomationSamlSettings {
	if a == nil {
		return nil
	}
	return a.Saml
}

func (a *AutomationDomain) GetScim() *SCIMSettings {
	if a == nil {
		return nil
	}
	return a.Scim
}

func (a *AutomationDomain) GetSecretExpirationSettings() *SecretExpirationSettings {
	if a == nil {
		return nil
	}
	return a.SecretExpirationSettings
}

func (a *AutomationDomain) GetSelfServiceAccountManagementSettings() *SelfServiceAccountManagementSettings {
	if a == nil {
		return nil
	}
	return a.SelfServiceAccountManagementSettings
}

func (a *AutomationDomain) GetTags() []string {
	if a == nil {
		return nil
	}
	return a.Tags
}

func (a *AutomationDomain) GetTokenExchangeSettings() *TokenExchangeSettings {
	if a == nil {
		return nil
	}
	return a.TokenExchangeSettings
}

func (a *AutomationDomain) GetUma() *UMASettings {
	if a == nil {
		return nil
	}
	return a.Uma
}

func (a *AutomationDomain) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *AutomationDomain) GetVhosts() []VirtualHost {
	if a == nil {
		return nil
	}
	return a.Vhosts
}

func (a *AutomationDomain) GetWebAuthnSettings() *WebAuthnSettings {
	if a == nil {
		return nil
	}
	return a.WebAuthnSettings
}
