// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: eac811c36090

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// AutomationClientRegistrationSettings - OpenID Connect Dynamic Client Registration configuration for the domain.
type AutomationClientRegistrationSettings struct {
	// Whether the unsecured http scheme is permitted in redirect URIs.
	AllowHTTPSchemeRedirectURI *bool `default:"false" json:"allowHttpSchemeRedirectUri"`
	// Whether localhost is permitted as a redirect URI host.
	AllowLocalhostRedirectURI *bool `default:"false" json:"allowLocalhostRedirectUri"`
	// Whether expression language is permitted in redirect URI parameters.
	AllowRedirectURIParamsExpressionLanguage *bool `default:"false" json:"allowRedirectUriParamsExpressionLanguage"`
	// Whether wildcards are permitted in redirect URIs.
	AllowWildCardRedirectURI *bool `default:"false" json:"allowWildCardRedirectUri"`
	// Scopes permitted on client registration requests when the allowed list is enabled.
	AllowedScopes []string `json:"allowedScopes,omitempty"`
	// Whether registered client scopes are restricted to an allowed list.
	AllowedScopesEnabled *bool `default:"false" json:"allowedScopesEnabled"`
	// Whether a client may be used as a template for dynamic client registration.
	ClientTemplateEnabled *bool `default:"false" json:"clientTemplateEnabled"`
	// Default scopes added to every client registration request.
	DefaultScopes []string `json:"defaultScopes,omitempty"`
	// Whether Dynamic Client Registration is enabled for the domain.
	DynamicClientRegistrationEnabled *bool `default:"false" json:"dynamicClientRegistrationEnabled"`
	// Whether open (unauthenticated) Dynamic Client Registration is enabled for the domain.
	OpenDynamicClientRegistrationEnabled *bool `default:"false" json:"openDynamicClientRegistrationEnabled"`
}

func (a AutomationClientRegistrationSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationClientRegistrationSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationClientRegistrationSettings) GetAllowHTTPSchemeRedirectURI() *bool {
	if a == nil {
		return nil
	}
	return a.AllowHTTPSchemeRedirectURI
}

func (a *AutomationClientRegistrationSettings) GetAllowLocalhostRedirectURI() *bool {
	if a == nil {
		return nil
	}
	return a.AllowLocalhostRedirectURI
}

func (a *AutomationClientRegistrationSettings) GetAllowRedirectURIParamsExpressionLanguage() *bool {
	if a == nil {
		return nil
	}
	return a.AllowRedirectURIParamsExpressionLanguage
}

func (a *AutomationClientRegistrationSettings) GetAllowWildCardRedirectURI() *bool {
	if a == nil {
		return nil
	}
	return a.AllowWildCardRedirectURI
}

func (a *AutomationClientRegistrationSettings) GetAllowedScopes() []string {
	if a == nil {
		return nil
	}
	return a.AllowedScopes
}

func (a *AutomationClientRegistrationSettings) GetAllowedScopesEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.AllowedScopesEnabled
}

func (a *AutomationClientRegistrationSettings) GetClientTemplateEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.ClientTemplateEnabled
}

func (a *AutomationClientRegistrationSettings) GetDefaultScopes() []string {
	if a == nil {
		return nil
	}
	return a.DefaultScopes
}

func (a *AutomationClientRegistrationSettings) GetDynamicClientRegistrationEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.DynamicClientRegistrationEnabled
}

func (a *AutomationClientRegistrationSettings) GetOpenDynamicClientRegistrationEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.OpenDynamicClientRegistrationEnabled
}
