// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ceac6a75783b

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
	"time"
)

// AutomationDataPlaneOutput - A data plane managed by the Automation API. Data planes store the runtime data of the domains bound to them. The id field is the stable, immutable identity used for idempotent create-or-update.
type AutomationDataPlaneOutput struct {
	// Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Name of the database the configuration points at. Read-only.
	Database *string `json:"database,omitempty"`
	// Identifier of the environment the data plane belongs to. Read-only.
	EnvironmentID *string `json:"environmentId,omitempty"`
	// Base URL of the gateway serving the domains bound to this data plane. Must be an absolute http(s) URL with a lowercase scheme; omitted or empty leaves it unset.
	GatewayURL *string `json:"gatewayUrl,omitempty"`
	// Hosts the configuration points at, as host:port. Read-only.
	Hosts []string `json:"hosts,omitempty"`
	// Stable, immutable identifier for the data plane within its environment. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. This is the value a domain's dataPlaneId refers to.
	ID string `json:"id"`
	// Human-readable name of the data plane.
	Name *string `json:"name,omitempty"`
	// Identifier of the organization the data plane belongs to. Read-only.
	OrganizationID *string `json:"organizationId,omitempty"`
	// Data plane plugin type identifier, matching the dataplane-am-<type> plugin. Immutable after creation.
	Type *string `json:"type,omitempty"`
	// Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

func (a AutomationDataPlaneOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationDataPlaneOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationDataPlaneOutput) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AutomationDataPlaneOutput) GetDatabase() *string {
	if a == nil {
		return nil
	}
	return a.Database
}

func (a *AutomationDataPlaneOutput) GetEnvironmentID() *string {
	if a == nil {
		return nil
	}
	return a.EnvironmentID
}

func (a *AutomationDataPlaneOutput) GetGatewayURL() *string {
	if a == nil {
		return nil
	}
	return a.GatewayURL
}

func (a *AutomationDataPlaneOutput) GetHosts() []string {
	if a == nil {
		return nil
	}
	return a.Hosts
}

func (a *AutomationDataPlaneOutput) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AutomationDataPlaneOutput) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AutomationDataPlaneOutput) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AutomationDataPlaneOutput) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AutomationDataPlaneOutput) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}
