// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0c5730d31fae

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// AutomationAccountSettings - User account settings for the domain: brute-force protection, registration, password reset, remember-me, and MFA challenge behavior.
type AutomationAccountSettings struct {
	// Duration, in seconds, for which the account remains blocked after too many failed login attempts.
	AccountBlockedDuration *int `json:"accountBlockedDuration,omitempty"`
	// Whether the user is automatically logged in after completing registration.
	AutoLoginAfterRegistration *bool `default:"false" json:"autoLoginAfterRegistration"`
	// Whether the user is automatically logged in after a password reset.
	AutoLoginAfterResetPassword *bool `default:"false" json:"autoLoginAfterResetPassword"`
	// Whether resetting a password also completes a pending registration.
	CompleteRegistrationWhenResetPassword *bool `default:"false" json:"completeRegistrationWhenResetPassword"`
	// Key of an identity provider that exists under this domain, used as the default for user registration. Resolved against the domain's identity providers when applied; a value that does not match an existing identity provider is rejected with a 400 response.
	DefaultIdentityProviderForRegistration *string `json:"defaultIdentityProviderForRegistration,omitempty"`
	// Whether passwordless (WebAuthn) devices are deleted when the password is reset.
	DeletePasswordlessDevicesAfterResetPassword *bool `default:"false" json:"deletePasswordlessDevicesAfterResetPassword"`
	// Whether dynamic (self-service) user registration is enabled.
	DynamicUserRegistration *bool `default:"false" json:"dynamicUserRegistration"`
	// Whether account settings are inherited from the parent (the environment). When true, the other fields are ignored.
	Inherited *bool `default:"true" json:"inherited"`
	// Whether brute-force authentication attempts are detected and blocked.
	LoginAttemptsDetectionEnabled *bool `default:"false" json:"loginAttemptsDetectionEnabled"`
	// Time, in seconds, after which the login attempt counter is reset when the maximum has not been reached.
	LoginAttemptsResetTime *int `json:"loginAttemptsResetTime,omitempty"`
	// Maximum number of failed login attempts before the account is blocked.
	MaxLoginAttempts *int `json:"maxLoginAttempts,omitempty"`
	// Whether failed MFA challenge attempts are detected and blocked.
	MfaChallengeAttemptsDetectionEnabled *bool `default:"false" json:"mfaChallengeAttemptsDetectionEnabled"`
	// Time, in seconds, after which the MFA challenge attempt counter is reset.
	MfaChallengeAttemptsResetTime *int `json:"mfaChallengeAttemptsResetTime,omitempty"`
	// Maximum number of failed MFA challenge attempts before the user is blocked.
	MfaChallengeMaxAttempts *int `json:"mfaChallengeMaxAttempts,omitempty"`
	// Whether to send an alert email after too many failed MFA challenge attempts.
	MfaChallengeSendVerifyAlertEmail *bool `default:"false" json:"mfaChallengeSendVerifyAlertEmail"`
	// URL the user is redirected to after registration.
	RedirectURIAfterRegistration *string `json:"redirectUriAfterRegistration,omitempty"`
	// URL the user is redirected to after a password reset.
	RedirectURIAfterResetPassword *string `json:"redirectUriAfterResetPassword,omitempty"`
	// Whether users can remain logged in for a fixed duration (remember-me).
	RememberMe *bool `default:"false" json:"rememberMe"`
	// Duration, in seconds, for which a remembered session stays valid.
	RememberMeDuration *int `json:"rememberMeDuration,omitempty"`
	// Whether the user must confirm their identity before resetting a password.
	ResetPasswordConfirmIdentity *bool `default:"false" json:"resetPasswordConfirmIdentity"`
	// Whether a custom form is used for the password-reset step.
	ResetPasswordCustomForm *bool `default:"false" json:"resetPasswordCustomForm"`
	// Custom fields rendered on the password-reset form.
	ResetPasswordCustomFormFields []FormField `json:"resetPasswordCustomFormFields,omitempty"`
	// Whether existing tokens are invalidated when the password is reset.
	ResetPasswordInvalidateTokens *bool `default:"false" json:"resetPasswordInvalidateTokens"`
	// Whether to send an account-recovery email.
	SendRecoverAccountEmail *bool `default:"false" json:"sendRecoverAccountEmail"`
	// Whether to send a registration-verification email.
	SendVerifyRegistrationAccountEmail *bool `default:"false" json:"sendVerifyRegistrationAccountEmail"`
}

func (a AutomationAccountSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationAccountSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationAccountSettings) GetAccountBlockedDuration() *int {
	if a == nil {
		return nil
	}
	return a.AccountBlockedDuration
}

func (a *AutomationAccountSettings) GetAutoLoginAfterRegistration() *bool {
	if a == nil {
		return nil
	}
	return a.AutoLoginAfterRegistration
}

func (a *AutomationAccountSettings) GetAutoLoginAfterResetPassword() *bool {
	if a == nil {
		return nil
	}
	return a.AutoLoginAfterResetPassword
}

func (a *AutomationAccountSettings) GetCompleteRegistrationWhenResetPassword() *bool {
	if a == nil {
		return nil
	}
	return a.CompleteRegistrationWhenResetPassword
}

func (a *AutomationAccountSettings) GetDefaultIdentityProviderForRegistration() *string {
	if a == nil {
		return nil
	}
	return a.DefaultIdentityProviderForRegistration
}

func (a *AutomationAccountSettings) GetDeletePasswordlessDevicesAfterResetPassword() *bool {
	if a == nil {
		return nil
	}
	return a.DeletePasswordlessDevicesAfterResetPassword
}

func (a *AutomationAccountSettings) GetDynamicUserRegistration() *bool {
	if a == nil {
		return nil
	}
	return a.DynamicUserRegistration
}

func (a *AutomationAccountSettings) GetInherited() *bool {
	if a == nil {
		return nil
	}
	return a.Inherited
}

func (a *AutomationAccountSettings) GetLoginAttemptsDetectionEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.LoginAttemptsDetectionEnabled
}

func (a *AutomationAccountSettings) GetLoginAttemptsResetTime() *int {
	if a == nil {
		return nil
	}
	return a.LoginAttemptsResetTime
}

func (a *AutomationAccountSettings) GetMaxLoginAttempts() *int {
	if a == nil {
		return nil
	}
	return a.MaxLoginAttempts
}

func (a *AutomationAccountSettings) GetMfaChallengeAttemptsDetectionEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.MfaChallengeAttemptsDetectionEnabled
}

func (a *AutomationAccountSettings) GetMfaChallengeAttemptsResetTime() *int {
	if a == nil {
		return nil
	}
	return a.MfaChallengeAttemptsResetTime
}

func (a *AutomationAccountSettings) GetMfaChallengeMaxAttempts() *int {
	if a == nil {
		return nil
	}
	return a.MfaChallengeMaxAttempts
}

func (a *AutomationAccountSettings) GetMfaChallengeSendVerifyAlertEmail() *bool {
	if a == nil {
		return nil
	}
	return a.MfaChallengeSendVerifyAlertEmail
}

func (a *AutomationAccountSettings) GetRedirectURIAfterRegistration() *string {
	if a == nil {
		return nil
	}
	return a.RedirectURIAfterRegistration
}

func (a *AutomationAccountSettings) GetRedirectURIAfterResetPassword() *string {
	if a == nil {
		return nil
	}
	return a.RedirectURIAfterResetPassword
}

func (a *AutomationAccountSettings) GetRememberMe() *bool {
	if a == nil {
		return nil
	}
	return a.RememberMe
}

func (a *AutomationAccountSettings) GetRememberMeDuration() *int {
	if a == nil {
		return nil
	}
	return a.RememberMeDuration
}

func (a *AutomationAccountSettings) GetResetPasswordConfirmIdentity() *bool {
	if a == nil {
		return nil
	}
	return a.ResetPasswordConfirmIdentity
}

func (a *AutomationAccountSettings) GetResetPasswordCustomForm() *bool {
	if a == nil {
		return nil
	}
	return a.ResetPasswordCustomForm
}

func (a *AutomationAccountSettings) GetResetPasswordCustomFormFields() []FormField {
	if a == nil {
		return nil
	}
	return a.ResetPasswordCustomFormFields
}

func (a *AutomationAccountSettings) GetResetPasswordInvalidateTokens() *bool {
	if a == nil {
		return nil
	}
	return a.ResetPasswordInvalidateTokens
}

func (a *AutomationAccountSettings) GetSendRecoverAccountEmail() *bool {
	if a == nil {
		return nil
	}
	return a.SendRecoverAccountEmail
}

func (a *AutomationAccountSettings) GetSendVerifyRegistrationAccountEmail() *bool {
	if a == nil {
		return nil
	}
	return a.SendVerifyRegistrationAccountEmail
}
