// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0d5bf1f72801

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
	"time"
)

// AutomationCertificate - A certificate managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
type AutomationCertificate struct {
	// Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected certificate type.
	Configuration *string `json:"configuration,omitempty"`
	// Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Expiry timestamp (ISO-8601 / RFC 3339, UTC), when known for the certificate type. Read-only.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// Stable, immutable identifier for the certificate within its domain. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the certificate on create-or-update.
	Key string `json:"key"`
	// Human-readable name of the certificate.
	Name *string `json:"name,omitempty"`
	// Whether this is the domain's system certificate. Immutable after creation. When true, only key is required; the certificate is built from the domains.certificates.default.* system settings and the name, type, and configuration fields are ignored.
	System *bool `default:"false" json:"system"`
	// Certificate plugin type identifier. Immutable after creation.
	Type *string `json:"type,omitempty"`
	// Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

func (a AutomationCertificate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationCertificate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationCertificate) GetConfiguration() *string {
	if a == nil {
		return nil
	}
	return a.Configuration
}

func (a *AutomationCertificate) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AutomationCertificate) GetExpiresAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.ExpiresAt
}

func (a *AutomationCertificate) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

func (a *AutomationCertificate) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AutomationCertificate) GetSystem() *bool {
	if a == nil {
		return nil
	}
	return a.System
}

func (a *AutomationCertificate) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AutomationCertificate) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}
