// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dc2d2f7e9cea

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// AutomationSamlSettings - Settings for the domain acting as a SAML 2.0 identity provider (IdP).
type AutomationSamlSettings struct {
	// Key of a certificate managed under this domain, used to sign SAML responses. Must reference a certificate created via the domain's certificate endpoints.
	Certificate *string `json:"certificate,omitempty"`
	// Whether the domain exposes the SAML 2.0 IdP protocol.
	Enabled *bool `default:"false" json:"enabled"`
	// URL or URN that uniquely identifies this IdP (the SAML entity ID).
	EntityID *string `json:"entityId,omitempty"`
}

func (a AutomationSamlSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationSamlSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationSamlSettings) GetCertificate() *string {
	if a == nil {
		return nil
	}
	return a.Certificate
}

func (a *AutomationSamlSettings) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *AutomationSamlSettings) GetEntityID() *string {
	if a == nil {
		return nil
	}
	return a.EntityID
}
