// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f1a0b7ddc82b

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// AutomationCertificateInput - A certificate managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
type AutomationCertificateInput struct {
	// Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected certificate type.
	Configuration *string `json:"configuration,omitempty"`
	// Stable, immutable identifier for the certificate within its domain. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the certificate on create-or-update.
	Key string `json:"key"`
	// Human-readable name of the certificate.
	Name *string `json:"name,omitempty"`
	// Whether this is the domain's system certificate. Immutable after creation. When true, only key is required; the certificate is built from the domains.certificates.default.* system settings and the name, type, and configuration fields are ignored.
	System *bool `default:"false" json:"system"`
	// Certificate plugin type identifier (the certificate provider to use).
	Type *string `json:"type,omitempty"`
}

func (a AutomationCertificateInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationCertificateInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationCertificateInput) GetConfiguration() *string {
	if a == nil {
		return nil
	}
	return a.Configuration
}

func (a *AutomationCertificateInput) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

func (a *AutomationCertificateInput) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AutomationCertificateInput) GetSystem() *bool {
	if a == nil {
		return nil
	}
	return a.System
}

func (a *AutomationCertificateInput) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}
