// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6ce39e02283f

package shared

// AutomationCertificateSettings - Domain-level certificate settings.
type AutomationCertificateSettings struct {
	// Key of a certificate managed under this domain, used as the fallback certificate when a client does not specify one. The reference is not checked against existing certificates: it can name one created after the domain or since deleted, and resolves whenever a certificate with that key exists.
	FallbackCertificate *string `json:"fallbackCertificate,omitempty"`
}

func (a *AutomationCertificateSettings) GetFallbackCertificate() *string {
	if a == nil {
		return nil
	}
	return a.FallbackCertificate
}
