// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5f62505f1197

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// AutomationOidcSettings - OpenID Connect settings for the domain. CIMD (client identity metadata document) settings are not exposed by the Automation API and are reset on update.
type AutomationOidcSettings struct {
	// Client-Initiated Backchannel Authentication (CIBA) settings for the domain. CIBA lets a relying party initiate end-user authentication from a separate consumption device, without redirecting the user through the browser. Authentication device notifiers are not managed by the Automation API and are not exposed here.
	CibaSettings *AutomationCIBASettings `json:"cibaSettings,omitempty"`
	// OpenID Connect Dynamic Client Registration configuration for the domain.
	ClientRegistrationSettings *ClientRegistrationSettings `json:"clientRegistrationSettings,omitempty"`
	// URLs the user may be redirected to after sign-out (post_logout_redirect_uri).
	PostLogoutRedirectUris []string `json:"postLogoutRedirectUris,omitempty"`
	// Whether redirect_uri and post_logout_redirect_uri values are matched strictly during OpenID Connect flows.
	RedirectURIStrictMatching *bool `default:"false" json:"redirectUriStrictMatching"`
	// Allowed request_uri values for passing OpenID Connect request objects by reference.
	RequestUris []string `json:"requestUris,omitempty"`
	// Financial-grade API (FAPI) security profile configuration for the domain.
	SecurityProfileSettings *SecurityProfileSettings `json:"securityProfileSettings,omitempty"`
}

func (a AutomationOidcSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationOidcSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationOidcSettings) GetCibaSettings() *AutomationCIBASettings {
	if a == nil {
		return nil
	}
	return a.CibaSettings
}

func (a *AutomationOidcSettings) GetClientRegistrationSettings() *ClientRegistrationSettings {
	if a == nil {
		return nil
	}
	return a.ClientRegistrationSettings
}

func (a *AutomationOidcSettings) GetPostLogoutRedirectUris() []string {
	if a == nil {
		return nil
	}
	return a.PostLogoutRedirectUris
}

func (a *AutomationOidcSettings) GetRedirectURIStrictMatching() *bool {
	if a == nil {
		return nil
	}
	return a.RedirectURIStrictMatching
}

func (a *AutomationOidcSettings) GetRequestUris() []string {
	if a == nil {
		return nil
	}
	return a.RequestUris
}

func (a *AutomationOidcSettings) GetSecurityProfileSettings() *SecurityProfileSettings {
	if a == nil {
		return nil
	}
	return a.SecurityProfileSettings
}
