// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4af22cb7d891

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// ClientRegistrationSettings - OpenID Connect Dynamic Client Registration configuration for the domain.
type ClientRegistrationSettings struct {
	// Whether the unsecured http scheme is permitted in redirect URIs.
	AllowHTTPSchemeRedirectURI *bool `default:"false" json:"allowHttpSchemeRedirectUri"`
	// Whether localhost is permitted as a redirect URI host.
	AllowLocalhostRedirectURI *bool `default:"false" json:"allowLocalhostRedirectUri"`
	// Whether expression language is permitted in redirect URI parameters.
	AllowRedirectURIParamsExpressionLanguage *bool `default:"false" json:"allowRedirectUriParamsExpressionLanguage"`
	// Whether wildcards are permitted in redirect URIs.
	AllowWildCardRedirectURI *bool `default:"false" json:"allowWildCardRedirectUri"`
	// Scopes permitted on client registration requests when the allowed list is enabled.
	AllowedScopes         []string `json:"allowedScopes,omitempty"`
	AllowedScopesEnabled  *bool    `json:"allowedScopesEnabled,omitempty"`
	ClientTemplateEnabled *bool    `json:"clientTemplateEnabled,omitempty"`
	// Default scopes added to every client registration request.
	DefaultScopes                        []string `json:"defaultScopes,omitempty"`
	DynamicClientRegistrationEnabled     *bool    `json:"dynamicClientRegistrationEnabled,omitempty"`
	OpenDynamicClientRegistrationEnabled *bool    `json:"openDynamicClientRegistrationEnabled,omitempty"`
}

func (c ClientRegistrationSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientRegistrationSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientRegistrationSettings) GetAllowHTTPSchemeRedirectURI() *bool {
	if c == nil {
		return nil
	}
	return c.AllowHTTPSchemeRedirectURI
}

func (c *ClientRegistrationSettings) GetAllowLocalhostRedirectURI() *bool {
	if c == nil {
		return nil
	}
	return c.AllowLocalhostRedirectURI
}

func (c *ClientRegistrationSettings) GetAllowRedirectURIParamsExpressionLanguage() *bool {
	if c == nil {
		return nil
	}
	return c.AllowRedirectURIParamsExpressionLanguage
}

func (c *ClientRegistrationSettings) GetAllowWildCardRedirectURI() *bool {
	if c == nil {
		return nil
	}
	return c.AllowWildCardRedirectURI
}

func (c *ClientRegistrationSettings) GetAllowedScopes() []string {
	if c == nil {
		return nil
	}
	return c.AllowedScopes
}

func (c *ClientRegistrationSettings) GetAllowedScopesEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.AllowedScopesEnabled
}

func (c *ClientRegistrationSettings) GetClientTemplateEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.ClientTemplateEnabled
}

func (c *ClientRegistrationSettings) GetDefaultScopes() []string {
	if c == nil {
		return nil
	}
	return c.DefaultScopes
}

func (c *ClientRegistrationSettings) GetDynamicClientRegistrationEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.DynamicClientRegistrationEnabled
}

func (c *ClientRegistrationSettings) GetOpenDynamicClientRegistrationEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.OpenDynamicClientRegistrationEnabled
}
