// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b3dd5116ab76

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// CorsSettings - Cross-Origin Resource Sharing configuration controlling which web origins may call the domain's endpoints from a browser.
type CorsSettings struct {
	// Whether the browser may send credentials (cookies, authorization headers) with cross-origin requests.
	AllowCredentials *bool `default:"false" json:"allowCredentials"`
	// Request headers permitted on cross-origin requests.
	AllowedHeaders []string `json:"allowedHeaders,omitempty"`
	// HTTP methods permitted on cross-origin requests.
	AllowedMethods []string `json:"allowedMethods,omitempty"`
	// Origins permitted to make cross-origin requests. Use "*" to allow any origin.
	AllowedOrigins []string `json:"allowedOrigins,omitempty"`
	// Whether CORS handling is enabled for the domain.
	Enabled *bool `default:"false" json:"enabled"`
	// How long, in seconds, a browser may cache the result of a preflight request.
	MaxAge *int `default:"86400" json:"maxAge"`
}

func (c CorsSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CorsSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CorsSettings) GetAllowCredentials() *bool {
	if c == nil {
		return nil
	}
	return c.AllowCredentials
}

func (c *CorsSettings) GetAllowedHeaders() []string {
	if c == nil {
		return nil
	}
	return c.AllowedHeaders
}

func (c *CorsSettings) GetAllowedMethods() []string {
	if c == nil {
		return nil
	}
	return c.AllowedMethods
}

func (c *CorsSettings) GetAllowedOrigins() []string {
	if c == nil {
		return nil
	}
	return c.AllowedOrigins
}

func (c *CorsSettings) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}

func (c *CorsSettings) GetMaxAge() *int {
	if c == nil {
		return nil
	}
	return c.MaxAge
}
