// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d25ea68011dc

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// CspSettings - Content Security Policy configuration for the domain's login and consent pages.
type CspSettings struct {
	// CSP directives, one per entry, in the form "directive-name value". A trailing semicolon is optional. Directive names must be valid CSP tokens and must not repeat; values are not interpreted. Directives that take no value, such as "upgrade-insecure-requests", may be supplied on their own. When reportOnly is enabled, a "report-uri" or "report-to" directive is required.
	Directives []string `json:"directives,omitempty"`
	// Whether CSP is enabled for the domain when not inherited.
	Enabled *bool `default:"false" json:"enabled"`
	// Whether CSP settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	Inherited *bool `default:"true" json:"inherited"`
	// When true, the policy is delivered as Content-Security-Policy-Report-Only.
	ReportOnly *bool `default:"false" json:"reportOnly"`
	// Whether inline scripts are allowed via a per-request nonce.
	ScriptInlineNonce *bool `default:"true" json:"scriptInlineNonce"`
}

func (c CspSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CspSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CspSettings) GetDirectives() []string {
	if c == nil {
		return nil
	}
	return c.Directives
}

func (c *CspSettings) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}

func (c *CspSettings) GetInherited() *bool {
	if c == nil {
		return nil
	}
	return c.Inherited
}

func (c *CspSettings) GetReportOnly() *bool {
	if c == nil {
		return nil
	}
	return c.ReportOnly
}

func (c *CspSettings) GetScriptInlineNonce() *bool {
	if c == nil {
		return nil
	}
	return c.ScriptInlineNonce
}
