// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 40328fb9ce5e

package shared

// FormField - A single field shown on a user-facing form, such as registration.
type FormField struct {
	// Identifier of the field, mapped to a user attribute.
	Key *string `json:"key,omitempty"`
	// Label displayed for the field.
	Label *string `json:"label,omitempty"`
	// Input type of the field.
	Type *string `json:"type,omitempty"`
}

func (f *FormField) GetKey() *string {
	if f == nil {
		return nil
	}
	return f.Key
}

func (f *FormField) GetLabel() *string {
	if f == nil {
		return nil
	}
	return f.Label
}

func (f *FormField) GetType() *string {
	if f == nil {
		return nil
	}
	return f.Type
}
