// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b492665c4117

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// KeyRetrievalSettings - Fetch, SSRF and cache limits applied to every trusted domain in the security domain.
type KeyRetrievalSettings struct {
	// Whether key material can be fetched from private IP addresses.
	AllowPrivateIPAddress *bool `default:"false" json:"allowPrivateIpAddress"`
	// Whether key material can be fetched over unsecured HTTP URIs.
	AllowUnsecuredHTTPURI *bool `default:"false" json:"allowUnsecuredHttpUri"`
	// Maximum number of key material entries retained in the cache.
	CacheMaxEntries *int `default:"50" json:"cacheMaxEntries"`
	// Time-to-live, in seconds, for cached key material.
	CacheTTLSeconds *int `default:"300" json:"cacheTtlSeconds"`
	// Timeout, in milliseconds, for fetching key material.
	FetchTimeoutMs *int `default:"5000" json:"fetchTimeoutMs"`
	// Maximum key material response size, in kilobytes.
	MaxResponseSizeKb *int `default:"32" json:"maxResponseSizeKb"`
}

func (k KeyRetrievalSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KeyRetrievalSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KeyRetrievalSettings) GetAllowPrivateIPAddress() *bool {
	if k == nil {
		return nil
	}
	return k.AllowPrivateIPAddress
}

func (k *KeyRetrievalSettings) GetAllowUnsecuredHTTPURI() *bool {
	if k == nil {
		return nil
	}
	return k.AllowUnsecuredHTTPURI
}

func (k *KeyRetrievalSettings) GetCacheMaxEntries() *int {
	if k == nil {
		return nil
	}
	return k.CacheMaxEntries
}

func (k *KeyRetrievalSettings) GetCacheTTLSeconds() *int {
	if k == nil {
		return nil
	}
	return k.CacheTTLSeconds
}

func (k *KeyRetrievalSettings) GetFetchTimeoutMs() *int {
	if k == nil {
		return nil
	}
	return k.FetchTimeoutMs
}

func (k *KeyRetrievalSettings) GetMaxResponseSizeKb() *int {
	if k == nil {
		return nil
	}
	return k.MaxResponseSizeKb
}
