// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e6c02318e24a

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// LoginSettings - Configuration of the domain's login flow and the features offered on the sign-in page.
type LoginSettings struct {
	// Whether certificate-based authentication is offered.
	CertificateBasedAuthEnabled *bool `default:"false" json:"certificateBasedAuthEnabled"`
	// URL used for certificate-based authentication.
	CertificateBasedAuthURL *string `json:"certificateBasedAuthUrl,omitempty"`
	// Whether users can initiate a forgot-password flow from the login page.
	ForgotPasswordEnabled *bool `default:"false" json:"forgotPasswordEnabled"`
	// Whether the login form is hidden (for example when only social or identifier-first login is offered).
	HideForm *bool `default:"false" json:"hideForm"`
	// Whether identifier-first login is enabled, prompting for the username before the password.
	IdentifierFirstEnabled *bool `default:"false" json:"identifierFirstEnabled"`
	// Whether these login settings are inherited from a parent scope rather than defined here. When true, the other fields are ignored.
	Inherited *bool `default:"true" json:"inherited"`
	// Whether magic-link authentication is offered.
	MagicLinkAuthEnabled *bool `default:"false" json:"magicLinkAuthEnabled"`
	// Whether users can name their passwordless devices.
	PasswordlessDeviceNamingEnabled *bool `default:"false" json:"passwordlessDeviceNamingEnabled"`
	// Whether passwordless (WebAuthn) authentication is offered.
	PasswordlessEnabled *bool `default:"false" json:"passwordlessEnabled"`
	// Whether a password is still required alongside passwordless authentication.
	PasswordlessEnforcePasswordEnabled *bool `default:"false" json:"passwordlessEnforcePasswordEnabled"`
	// Period, in seconds, after which the user's credentials must be re-entered to keep using passwordless authentication.
	PasswordlessEnforcePasswordMaxAge *int `json:"passwordlessEnforcePasswordMaxAge,omitempty"`
	// Whether a passwordless device can be remembered to skip future challenges.
	PasswordlessRememberDeviceEnabled *bool `default:"false" json:"passwordlessRememberDeviceEnabled"`
	// Whether users can self-register from the login page.
	RegisterEnabled *bool `default:"false" json:"registerEnabled"`
	// Whether the login page offers a remember-me option.
	RememberMeEnabled *bool `default:"false" json:"rememberMeEnabled"`
	// Whether the user is forced to reset their password once it expires.
	ResetPasswordOnExpiration *bool `json:"resetPasswordOnExpiration,omitempty"`
}

func (l LoginSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LoginSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LoginSettings) GetCertificateBasedAuthEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.CertificateBasedAuthEnabled
}

func (l *LoginSettings) GetCertificateBasedAuthURL() *string {
	if l == nil {
		return nil
	}
	return l.CertificateBasedAuthURL
}

func (l *LoginSettings) GetForgotPasswordEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.ForgotPasswordEnabled
}

func (l *LoginSettings) GetHideForm() *bool {
	if l == nil {
		return nil
	}
	return l.HideForm
}

func (l *LoginSettings) GetIdentifierFirstEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.IdentifierFirstEnabled
}

func (l *LoginSettings) GetInherited() *bool {
	if l == nil {
		return nil
	}
	return l.Inherited
}

func (l *LoginSettings) GetMagicLinkAuthEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.MagicLinkAuthEnabled
}

func (l *LoginSettings) GetPasswordlessDeviceNamingEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.PasswordlessDeviceNamingEnabled
}

func (l *LoginSettings) GetPasswordlessEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.PasswordlessEnabled
}

func (l *LoginSettings) GetPasswordlessEnforcePasswordEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.PasswordlessEnforcePasswordEnabled
}

func (l *LoginSettings) GetPasswordlessEnforcePasswordMaxAge() *int {
	if l == nil {
		return nil
	}
	return l.PasswordlessEnforcePasswordMaxAge
}

func (l *LoginSettings) GetPasswordlessRememberDeviceEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.PasswordlessRememberDeviceEnabled
}

func (l *LoginSettings) GetRegisterEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.RegisterEnabled
}

func (l *LoginSettings) GetRememberMeEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.RememberMeEnabled
}

func (l *LoginSettings) GetResetPasswordOnExpiration() *bool {
	if l == nil {
		return nil
	}
	return l.ResetPasswordOnExpiration
}
