// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 28cdd0f19d56

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// PasswordSettings - Password policy applied to users of the domain: complexity requirements, expiry, and history.
type PasswordSettings struct {
	// Whether passwords found in a common-password dictionary are rejected.
	ExcludePasswordsInDictionary *bool `json:"excludePasswordsInDictionary,omitempty"`
	// Whether passwords containing the user's profile information are rejected.
	ExcludeUserProfileInfoInPassword *bool `json:"excludeUserProfileInfoInPassword,omitempty"`
	// Number of days after which a password expires and must be changed.
	ExpiryDuration *int `json:"expiryDuration,omitempty"`
	// Whether a password must contain at least one number.
	IncludeNumbers *bool `json:"includeNumbers,omitempty"`
	// Whether a password must contain at least one special character.
	IncludeSpecialCharacters *bool `json:"includeSpecialCharacters,omitempty"`
	// Whether these password settings are inherited from a parent scope rather than defined here. When true, the other fields are ignored.
	Inherited *bool `default:"true" json:"inherited"`
	// Whether a password must contain both uppercase and lowercase letters.
	LettersInMixedCase *bool `json:"lettersInMixedCase,omitempty"`
	// Maximum number of identical consecutive characters allowed in a password.
	MaxConsecutiveLetters *int `json:"maxConsecutiveLetters,omitempty"`
	// Maximum number of characters a password may contain.
	MaxLength *int `default:"128" json:"maxLength"`
	// Minimum number of characters a password must contain.
	MinLength *int `default:"8" json:"minLength"`
	// Number of previous passwords retained in history and barred from reuse.
	OldPasswords *int `json:"oldPasswords,omitempty"`
	// Whether password history is enforced to prevent reuse of recent passwords.
	PasswordHistoryEnabled *bool `default:"false" json:"passwordHistoryEnabled"`
}

func (p PasswordSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PasswordSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PasswordSettings) GetExcludePasswordsInDictionary() *bool {
	if p == nil {
		return nil
	}
	return p.ExcludePasswordsInDictionary
}

func (p *PasswordSettings) GetExcludeUserProfileInfoInPassword() *bool {
	if p == nil {
		return nil
	}
	return p.ExcludeUserProfileInfoInPassword
}

func (p *PasswordSettings) GetExpiryDuration() *int {
	if p == nil {
		return nil
	}
	return p.ExpiryDuration
}

func (p *PasswordSettings) GetIncludeNumbers() *bool {
	if p == nil {
		return nil
	}
	return p.IncludeNumbers
}

func (p *PasswordSettings) GetIncludeSpecialCharacters() *bool {
	if p == nil {
		return nil
	}
	return p.IncludeSpecialCharacters
}

func (p *PasswordSettings) GetInherited() *bool {
	if p == nil {
		return nil
	}
	return p.Inherited
}

func (p *PasswordSettings) GetLettersInMixedCase() *bool {
	if p == nil {
		return nil
	}
	return p.LettersInMixedCase
}

func (p *PasswordSettings) GetMaxConsecutiveLetters() *int {
	if p == nil {
		return nil
	}
	return p.MaxConsecutiveLetters
}

func (p *PasswordSettings) GetMaxLength() *int {
	if p == nil {
		return nil
	}
	return p.MaxLength
}

func (p *PasswordSettings) GetMinLength() *int {
	if p == nil {
		return nil
	}
	return p.MinLength
}

func (p *PasswordSettings) GetOldPasswords() *int {
	if p == nil {
		return nil
	}
	return p.OldPasswords
}

func (p *PasswordSettings) GetPasswordHistoryEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.PasswordHistoryEnabled
}
