// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d87742e208b6

package shared

// ReporterAttributeMapping - Exports one additional attribute, read from the audit context by expression, under a chosen field name.
type ReporterAttributeMapping struct {
	// The name the evaluated value takes on the exported payload.
	ExportedName *string `json:"exportedName,omitempty"`
	// Expression evaluated against the audit context.
	Expression *string `json:"expression,omitempty"`
}

func (r *ReporterAttributeMapping) GetExportedName() *string {
	if r == nil {
		return nil
	}
	return r.ExportedName
}

func (r *ReporterAttributeMapping) GetExpression() *string {
	if r == nil {
		return nil
	}
	return r.Expression
}
