// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 97ba717b0693

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// ResetPasswordSettings - Rules applied to a self-service password reset.
type ResetPasswordSettings struct {
	// Whether the user must supply their current password to set a new one.
	OldPasswordRequired *bool `default:"false" json:"oldPasswordRequired"`
	// Lifetime, in seconds, of the password-reset token.
	TokenAge *int `json:"tokenAge,omitempty"`
}

func (r ResetPasswordSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResetPasswordSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ResetPasswordSettings) GetOldPasswordRequired() *bool {
	if r == nil {
		return nil
	}
	return r.OldPasswordRequired
}

func (r *ResetPasswordSettings) GetTokenAge() *int {
	if r == nil {
		return nil
	}
	return r.TokenAge
}
