// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9faaab379ff2

package shared

// SecretExpirationSettings - Controls whether client secrets in the domain expire and after how long.
type SecretExpirationSettings struct {
	// Whether client-secret expiration is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// Lifetime, in seconds, of a client secret before it expires.
	ExpiryTimeSeconds *int64 `json:"expiryTimeSeconds,omitempty"`
}

func (s *SecretExpirationSettings) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

func (s *SecretExpirationSettings) GetExpiryTimeSeconds() *int64 {
	if s == nil {
		return nil
	}
	return s.ExpiryTimeSeconds
}
