// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b0322598792f

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// SecurityProfileSettings - Financial-grade API (FAPI) security profile configuration for the domain.
type SecurityProfileSettings struct {
	// Whether the Open Banking Brasil Financial-grade API security profile (version 1.0) is applied.
	EnableFapiBrazil *bool `default:"false" json:"enableFapiBrazil"`
	// Whether the standard Financial-grade API security profile (version 1.0) is applied.
	EnablePlainFapi *bool `default:"false" json:"enablePlainFapi"`
}

func (s SecurityProfileSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SecurityProfileSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SecurityProfileSettings) GetEnableFapiBrazil() *bool {
	if s == nil {
		return nil
	}
	return s.EnableFapiBrazil
}

func (s *SecurityProfileSettings) GetEnablePlainFapi() *bool {
	if s == nil {
		return nil
	}
	return s.EnablePlainFapi
}
