// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a64e733c45f9

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// SelfServiceAccountManagementSettings - Controls whether end users can manage their own account (for example, reset their password) and the rules that apply.
type SelfServiceAccountManagementSettings struct {
	// Whether self-service account management is enabled for end users.
	Enabled *bool `default:"false" json:"enabled"`
	// Rules applied to a self-service password reset.
	ResetPassword *ResetPasswordSettings `json:"resetPassword,omitempty"`
}

func (s SelfServiceAccountManagementSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SelfServiceAccountManagementSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SelfServiceAccountManagementSettings) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

func (s *SelfServiceAccountManagementSettings) GetResetPassword() *ResetPasswordSettings {
	if s == nil {
		return nil
	}
	return s.ResetPassword
}
