// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ef93140c5a39

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// SpiffeDomainSettings - Workload identity (SPIFFE) settings for the domain.
type SpiffeDomainSettings struct {
	// Deprecated: moved to keyRetrievalSettings.allowPrivateIpAddress.
	//
	// Deprecated: Use key_retrieval_settings.allow_private_ip_address instead..
	AllowPrivateIPAddress *bool `json:"allowPrivateIpAddress,omitempty"`
	// Deprecated: moved to keyRetrievalSettings.allowUnsecuredHttpUri.
	//
	// Deprecated: Use key_retrieval_settings.allow_unsecured_http_uri instead..
	AllowUnsecuredHTTPURI *bool `json:"allowUnsecuredHttpUri,omitempty"`
	// Deprecated: moved to keyRetrievalSettings.cacheMaxEntries.
	//
	// Deprecated: Use key_retrieval_settings.cache_max_entries instead..
	CacheMaxEntries *int `json:"cacheMaxEntries,omitempty"`
	// Deprecated: moved to keyRetrievalSettings.cacheTtlSeconds.
	//
	// Deprecated: Use key_retrieval_settings.cache_ttl_seconds instead..
	CacheTTLSeconds *int `json:"cacheTtlSeconds,omitempty"`
	// Allowed clock skew, in seconds, when validating JWT temporal claims.
	ClockSkewSeconds *int `default:"30" json:"clockSkewSeconds"`
	// Default allowlist of signature algorithms accepted for SPIFFE JWT validation.
	DefaultAllowedAlgorithms []string `json:"defaultAllowedAlgorithms,omitempty"`
	// Whether SPIFFE workload identity support is enabled for the domain.
	Enabled *bool `default:"false" json:"enabled"`
	// Deprecated: moved to keyRetrievalSettings.fetchTimeoutMs.
	//
	// Deprecated: Use key_retrieval_settings.fetch_timeout_ms instead..
	FetchTimeoutMs *int `json:"fetchTimeoutMs,omitempty"`
	// Maximum accepted JWT lifetime, in seconds, computed as exp minus iat.
	MaxJwtLifetimeSeconds *int `default:"300" json:"maxJwtLifetimeSeconds"`
	// Deprecated: moved to keyRetrievalSettings.maxResponseSizeKb.
	//
	// Deprecated: Use key_retrieval_settings.max_response_size_kb instead..
	MaxResponseSizeKb *int `json:"maxResponseSizeKb,omitempty"`
}

func (s SpiffeDomainSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SpiffeDomainSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SpiffeDomainSettings) GetAllowPrivateIPAddress() *bool {
	if s == nil {
		return nil
	}
	return s.AllowPrivateIPAddress
}

func (s *SpiffeDomainSettings) GetAllowUnsecuredHTTPURI() *bool {
	if s == nil {
		return nil
	}
	return s.AllowUnsecuredHTTPURI
}

func (s *SpiffeDomainSettings) GetCacheMaxEntries() *int {
	if s == nil {
		return nil
	}
	return s.CacheMaxEntries
}

func (s *SpiffeDomainSettings) GetCacheTTLSeconds() *int {
	if s == nil {
		return nil
	}
	return s.CacheTTLSeconds
}

func (s *SpiffeDomainSettings) GetClockSkewSeconds() *int {
	if s == nil {
		return nil
	}
	return s.ClockSkewSeconds
}

func (s *SpiffeDomainSettings) GetDefaultAllowedAlgorithms() []string {
	if s == nil {
		return nil
	}
	return s.DefaultAllowedAlgorithms
}

func (s *SpiffeDomainSettings) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

func (s *SpiffeDomainSettings) GetFetchTimeoutMs() *int {
	if s == nil {
		return nil
	}
	return s.FetchTimeoutMs
}

func (s *SpiffeDomainSettings) GetMaxJwtLifetimeSeconds() *int {
	if s == nil {
		return nil
	}
	return s.MaxJwtLifetimeSeconds
}

func (s *SpiffeDomainSettings) GetMaxResponseSizeKb() *int {
	if s == nil {
		return nil
	}
	return s.MaxResponseSizeKb
}
