// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 80d0cbfeb686

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// ScopeHandling - How scopes are handled when issuing the exchanged token. downscoping restricts the issued token to a subset of the original scopes.
type ScopeHandling string

const (
	ScopeHandlingDownscoping ScopeHandling = "downscoping"
	ScopeHandlingPermissive  ScopeHandling = "permissive"
)

func (e ScopeHandling) ToPointer() *ScopeHandling {
	return &e
}
func (e *ScopeHandling) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "downscoping":
		fallthrough
	case "permissive":
		*e = ScopeHandling(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ScopeHandling: %v", v)
	}
}

// TokenExchangeOAuthSettings - OAuth-specific token-exchange behavior, such as how scopes are handled, with optional inheritance from domain defaults.
type TokenExchangeOAuthSettings struct {
	// Whether these settings are inherited from the domain defaults rather than defined here.
	Inherited *bool `default:"true" json:"inherited"`
	// How scopes are handled when issuing the exchanged token. downscoping restricts the issued token to a subset of the original scopes.
	ScopeHandling *ScopeHandling `default:"downscoping" json:"scopeHandling"`
}

func (t TokenExchangeOAuthSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TokenExchangeOAuthSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TokenExchangeOAuthSettings) GetInherited() *bool {
	if t == nil {
		return nil
	}
	return t.Inherited
}

func (t *TokenExchangeOAuthSettings) GetScopeHandling() *ScopeHandling {
	if t == nil {
		return nil
	}
	return t.ScopeHandling
}
