// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a95f72893ad7

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// KeyResolutionMethod - How the issuer's signing key is resolved. JWKS_URL fetches keys from a JWKS endpoint; PEM uses an inline X.509 certificate.
type KeyResolutionMethod string

const (
	KeyResolutionMethodJwksURL KeyResolutionMethod = "JWKS_URL"
	KeyResolutionMethodPem     KeyResolutionMethod = "PEM"
)

func (e KeyResolutionMethod) ToPointer() *KeyResolutionMethod {
	return &e
}
func (e *KeyResolutionMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "JWKS_URL":
		fallthrough
	case "PEM":
		*e = KeyResolutionMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KeyResolutionMethod: %v", v)
	}
}

// TrustedIssuer - An external token issuer whose JWTs are accepted as subject or actor tokens during token exchange, validated with the configured key material.
type TrustedIssuer struct {
	// PEM-encoded X.509 certificate. Required when keyResolutionMethod is PEM.
	Certificate *string `json:"certificate,omitempty"`
	// Expected value of the "iss" claim in the external JWT.
	Issuer *string `json:"issuer,omitempty"`
	// JWKS endpoint URL. Required when keyResolutionMethod is JWKS_URL.
	JwksURI *string `json:"jwksUri,omitempty"`
	// How the issuer's signing key is resolved. JWKS_URL fetches keys from a JWKS endpoint; PEM uses an inline X.509 certificate.
	KeyResolutionMethod *KeyResolutionMethod `json:"keyResolutionMethod,omitempty"`
	// One-to-one mapping from external scope to domain scope. Unmapped issuer scopes are dropped (fail-closed).
	ScopeMappings map[string]string `json:"scopeMappings,omitempty"`
	// Criteria used to locate a domain user when user binding is enabled. All criteria are combined with AND.
	UserBindingCriteria []UserBindingCriterion `json:"userBindingCriteria,omitempty"`
	// Whether the external JWT subject is resolved to a single domain user using the user binding criteria. When false, a virtual user is built from the token claims only.
	UserBindingEnabled *bool `default:"false" json:"userBindingEnabled"`
}

func (t TrustedIssuer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TrustedIssuer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TrustedIssuer) GetCertificate() *string {
	if t == nil {
		return nil
	}
	return t.Certificate
}

func (t *TrustedIssuer) GetIssuer() *string {
	if t == nil {
		return nil
	}
	return t.Issuer
}

func (t *TrustedIssuer) GetJwksURI() *string {
	if t == nil {
		return nil
	}
	return t.JwksURI
}

func (t *TrustedIssuer) GetKeyResolutionMethod() *KeyResolutionMethod {
	if t == nil {
		return nil
	}
	return t.KeyResolutionMethod
}

func (t *TrustedIssuer) GetScopeMappings() map[string]string {
	if t == nil {
		return nil
	}
	return t.ScopeMappings
}

func (t *TrustedIssuer) GetUserBindingCriteria() []UserBindingCriterion {
	if t == nil {
		return nil
	}
	return t.UserBindingCriteria
}

func (t *TrustedIssuer) GetUserBindingEnabled() *bool {
	if t == nil {
		return nil
	}
	return t.UserBindingEnabled
}
