// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8d7a09e99b91

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// UMASettings - Configuration of the domain's User-Managed Access (UMA 2.0) authorization features.
type UMASettings struct {
	// Whether User-Managed Access is enabled for the domain.
	Enabled *bool `default:"false" json:"enabled"`
}

func (u UMASettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UMASettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UMASettings) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}
