// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f8c794e87a3b

package shared

// UserBindingCriterion - A single rule that matches a domain user attribute against a value derived from the external token claims.
type UserBindingCriterion struct {
	// Domain user attribute used for the lookup. Must match a field supported by the user repository search.
	Attribute *string `json:"attribute,omitempty"`
	// Expression evaluated against the validated token claims (variable "token") to produce the value to match.
	Expression *string `json:"expression,omitempty"`
}

func (u *UserBindingCriterion) GetAttribute() *string {
	if u == nil {
		return nil
	}
	return u.Attribute
}

func (u *UserBindingCriterion) GetExpression() *string {
	if u == nil {
		return nil
	}
	return u.Expression
}
