// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2c374dd9657b

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// AttestationConveyancePreference - Relying-party preference for attestation conveyance during credential creation. NONE requests no attestation, INDIRECT allows anonymized attestation, and DIRECT requests the authenticator's attestation statement.
type AttestationConveyancePreference string

const (
	AttestationConveyancePreferenceNone     AttestationConveyancePreference = "NONE"
	AttestationConveyancePreferenceIndirect AttestationConveyancePreference = "INDIRECT"
	AttestationConveyancePreferenceDirect   AttestationConveyancePreference = "DIRECT"
)

func (e AttestationConveyancePreference) ToPointer() *AttestationConveyancePreference {
	return &e
}
func (e *AttestationConveyancePreference) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "INDIRECT":
		fallthrough
	case "DIRECT":
		*e = AttestationConveyancePreference(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AttestationConveyancePreference: %v", v)
	}
}

// AuthenticatorAttachment - Preferred authenticator attachment. PLATFORM selects authenticators bound to the device (such as a fingerprint reader); CROSS_PLATFORM selects roaming authenticators (such as a security key).
type AuthenticatorAttachment string

const (
	AuthenticatorAttachmentCrossPlatform AuthenticatorAttachment = "CROSS_PLATFORM"
	AuthenticatorAttachmentPlatform      AuthenticatorAttachment = "PLATFORM"
)

func (e AuthenticatorAttachment) ToPointer() *AuthenticatorAttachment {
	return &e
}
func (e *AuthenticatorAttachment) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CROSS_PLATFORM":
		fallthrough
	case "PLATFORM":
		*e = AuthenticatorAttachment(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthenticatorAttachment: %v", v)
	}
}

// Certificates - Trusted device-attestation X.509 certificates, keyed by name.
type Certificates struct {
}

// UserVerification - Relying-party requirement regarding user verification during a ceremony. REQUIRED enforces verification, PREFERRED requests it when available, and DISCOURAGED avoids it.
type UserVerification string

const (
	UserVerificationRequired    UserVerification = "REQUIRED"
	UserVerificationPreferred   UserVerification = "PREFERRED"
	UserVerificationDiscouraged UserVerification = "DISCOURAGED"
)

func (e UserVerification) ToPointer() *UserVerification {
	return &e
}
func (e *UserVerification) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "REQUIRED":
		fallthrough
	case "PREFERRED":
		fallthrough
	case "DISCOURAGED":
		*e = UserVerification(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserVerification: %v", v)
	}
}

// WebAuthnSettings - WebAuthn (FIDO2) relying-party configuration governing passwordless and multi-factor authentication for the domain.
type WebAuthnSettings struct {
	// Relying-party preference for attestation conveyance during credential creation. NONE requests no attestation, INDIRECT allows anonymized attestation, and DIRECT requests the authenticator's attestation statement.
	AttestationConveyancePreference *AttestationConveyancePreference `default:"NONE" json:"attestationConveyancePreference"`
	// Preferred authenticator attachment. PLATFORM selects authenticators bound to the device (such as a fingerprint reader); CROSS_PLATFORM selects roaming authenticators (such as a security key).
	AuthenticatorAttachment *AuthenticatorAttachment `json:"authenticatorAttachment,omitempty"`
	// Trusted device-attestation X.509 certificates, keyed by name.
	Certificates map[string]Certificates `json:"certificates,omitempty"`
	// Whether to periodically re-verify that registered authenticators remain valid against the FIDO2 Metadata Service.
	EnforceAuthenticatorIntegrity *bool `default:"false" json:"enforceAuthenticatorIntegrity"`
	// Maximum elapsed time, in seconds, since an authenticator was last verified before it is re-checked on the next passwordless login.
	EnforceAuthenticatorIntegrityMaxAge *int `json:"enforceAuthenticatorIntegrityMaxAge,omitempty"`
	// Whether to reject registration of a credential already registered to a different user.
	ForceRegistration *bool `default:"false" json:"forceRegistration"`
	// Relying-party origin; must match the browser's window.location.origin during registration and authentication ceremonies.
	Origin *string `json:"origin,omitempty"`
	// Relying-party identifier: a domain string that scopes credentials to this entity. A credential can only be used with the relying party it was registered against.
	RelyingPartyID *string `json:"relyingPartyId,omitempty"`
	// Human-readable relying-party name shown to users during ceremonies.
	RelyingPartyName *string `json:"relyingPartyName,omitempty"`
	// Whether the authenticator must create a client-side resident (discoverable) credential.
	RequireResidentKey *bool `default:"false" json:"requireResidentKey"`
	// Relying-party requirement regarding user verification during a ceremony. REQUIRED enforces verification, PREFERRED requests it when available, and DISCOURAGED avoids it.
	UserVerification *UserVerification `default:"PREFERRED" json:"userVerification"`
}

func (w WebAuthnSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebAuthnSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebAuthnSettings) GetAttestationConveyancePreference() *AttestationConveyancePreference {
	if w == nil {
		return nil
	}
	return w.AttestationConveyancePreference
}

func (w *WebAuthnSettings) GetAuthenticatorAttachment() *AuthenticatorAttachment {
	if w == nil {
		return nil
	}
	return w.AuthenticatorAttachment
}

func (w *WebAuthnSettings) GetCertificates() map[string]Certificates {
	if w == nil {
		return nil
	}
	return w.Certificates
}

func (w *WebAuthnSettings) GetEnforceAuthenticatorIntegrity() *bool {
	if w == nil {
		return nil
	}
	return w.EnforceAuthenticatorIntegrity
}

func (w *WebAuthnSettings) GetEnforceAuthenticatorIntegrityMaxAge() *int {
	if w == nil {
		return nil
	}
	return w.EnforceAuthenticatorIntegrityMaxAge
}

func (w *WebAuthnSettings) GetForceRegistration() *bool {
	if w == nil {
		return nil
	}
	return w.ForceRegistration
}

func (w *WebAuthnSettings) GetOrigin() *string {
	if w == nil {
		return nil
	}
	return w.Origin
}

func (w *WebAuthnSettings) GetRelyingPartyID() *string {
	if w == nil {
		return nil
	}
	return w.RelyingPartyID
}

func (w *WebAuthnSettings) GetRelyingPartyName() *string {
	if w == nil {
		return nil
	}
	return w.RelyingPartyName
}

func (w *WebAuthnSettings) GetRequireResidentKey() *bool {
	if w == nil {
		return nil
	}
	return w.RequireResidentKey
}

func (w *WebAuthnSettings) GetUserVerification() *UserVerification {
	if w == nil {
		return nil
	}
	return w.UserVerification
}
