// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e88dc42840f7

package shared

// WebProtectionSettings - HTTP security headers applied to the domain's login and consent pages.
type WebProtectionSettings struct {
	// Content Security Policy configuration for the domain's login and consent pages.
	Csp *CspSettings `json:"csp,omitempty"`
	// Controls whether the domain's pages may be embedded in frames on other origins.
	Xframe *XFrameSettings `json:"xframe,omitempty"`
	// Controls the legacy X-XSS-Protection response header.
	XSS *XSSProtectionSettings `json:"xss,omitempty"`
}

func (w *WebProtectionSettings) GetCsp() *CspSettings {
	if w == nil {
		return nil
	}
	return w.Csp
}

func (w *WebProtectionSettings) GetXframe() *XFrameSettings {
	if w == nil {
		return nil
	}
	return w.Xframe
}

func (w *WebProtectionSettings) GetXSS() *XSSProtectionSettings {
	if w == nil {
		return nil
	}
	return w.XSS
}
