// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ab87b1edf9dc

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// XFrameSettings - Controls whether the domain's pages may be embedded in frames on other origins.
type XFrameSettings struct {
	// X-Frame-Options action. Supported values: DENY, SAMEORIGIN. Leave empty to omit the header.
	Action *string `json:"action,omitempty"`
	// Whether X-Frame-Options is enabled for the domain when not inherited.
	Enabled *bool `default:"false" json:"enabled"`
	// Whether X-Frame-Options settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	Inherited *bool `default:"true" json:"inherited"`
}

func (x XFrameSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(x, "", false)
}

func (x *XFrameSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &x, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (x *XFrameSettings) GetAction() *string {
	if x == nil {
		return nil
	}
	return x.Action
}

func (x *XFrameSettings) GetEnabled() *bool {
	if x == nil {
		return nil
	}
	return x.Enabled
}

func (x *XFrameSettings) GetInherited() *bool {
	if x == nil {
		return nil
	}
	return x.Inherited
}
