// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1f120880c625

package shared

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

// XSSProtectionSettings - Controls the legacy X-XSS-Protection response header.
type XSSProtectionSettings struct {
	// Value of the X-XSS-Protection header.
	Action *string `json:"action,omitempty"`
	// Whether X-XSS-Protection is enabled for the domain when not inherited.
	Enabled *bool `default:"false" json:"enabled"`
	// Whether X-XSS-Protection settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	Inherited *bool `default:"true" json:"inherited"`
}

func (x XSSProtectionSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(x, "", false)
}

func (x *XSSProtectionSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &x, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (x *XSSProtectionSettings) GetAction() *string {
	if x == nil {
		return nil
	}
	return x.Action
}

func (x *XSSProtectionSettings) GetEnabled() *bool {
	if x == nil {
		return nil
	}
	return x.Enabled
}

func (x *XSSProtectionSettings) GetInherited() *bool {
	if x == nil {
		return nil
	}
	return x.Inherited
}
