// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d3dff8a7fae1

package provider

import (
	"context"
	"github.com/gravitee-io/terraform-provider-am/internal/provider/typeconvert"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *CertificateDataSourceModel) RefreshFromSharedAutomationCertificate(ctx context.Context, resp *shared.AutomationCertificate) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Configuration = types.StringPointerValue(resp.Configuration)
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.ExpiresAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ExpiresAt))
		r.Key = types.StringValue(resp.Key)
		r.Name = types.StringPointerValue(resp.Name)
		r.System = types.BoolPointerValue(resp.System)
		r.Type = types.StringPointerValue(resp.Type)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *CertificateDataSourceModel) ToOperationsAutomationGetCertificateRequest(ctx context.Context) (*operations.AutomationGetCertificateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var domainKey string
	domainKey = r.DomainKey.ValueString()

	var key string
	key = r.Key.ValueString()

	out := operations.AutomationGetCertificateRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		DomainKey:      domainKey,
		Key:            key,
	}

	return &out, diags
}
