// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a94ce61290bb

package provider

import (
	"context"
	"github.com/gravitee-io/terraform-provider-am/internal/provider/typeconvert"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *DataPlaneDataSourceModel) RefreshFromSharedAutomationDataPlaneOutput(ctx context.Context, resp *shared.AutomationDataPlaneOutput) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.Database = types.StringPointerValue(resp.Database)
		r.EnvironmentID = types.StringPointerValue(resp.EnvironmentID)
		r.GatewayURL = types.StringPointerValue(resp.GatewayURL)
		r.Hosts = make([]types.String, 0, len(resp.Hosts))
		for _, v := range resp.Hosts {
			r.Hosts = append(r.Hosts, types.StringValue(v))
		}
		r.ID = types.StringValue(resp.ID)
		r.Name = types.StringValue(resp.Name)
		r.OrganizationID = types.StringPointerValue(resp.OrganizationID)
		r.Type = types.StringValue(resp.Type)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *DataPlaneDataSourceModel) ToOperationsAutomationGetDataPlaneRequest(ctx context.Context) (*operations.AutomationGetDataPlaneRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var id string
	id = r.ID.ValueString()

	out := operations.AutomationGetDataPlaneRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		ID:             id,
	}

	return &out, diags
}
