// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f79994bba231

package provider

import (
	"context"
	"github.com/gravitee-io/terraform-provider-am/internal/provider/typeconvert"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *DataPlaneResourceModel) RefreshFromSharedAutomationDataPlaneOutput(ctx context.Context, resp *shared.AutomationDataPlaneOutput) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.Database = types.StringPointerValue(resp.Database)
		r.EnvironmentID = types.StringPointerValue(resp.EnvironmentID)
		r.GatewayURL = types.StringPointerValue(resp.GatewayURL)
		r.Hosts = make([]types.String, 0, len(resp.Hosts))
		for _, v := range resp.Hosts {
			r.Hosts = append(r.Hosts, types.StringValue(v))
		}
		r.ID = types.StringValue(resp.ID)
		r.Name = types.StringPointerValue(resp.Name)
		r.OrganizationID = types.StringPointerValue(resp.OrganizationID)
		r.Type = types.StringPointerValue(resp.Type)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *DataPlaneResourceModel) ToOperationsAutomationCreateOrUpdateDataPlaneRequest(ctx context.Context) (*operations.AutomationCreateOrUpdateDataPlaneRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	automationDataPlane, automationDataPlaneDiags := r.ToSharedAutomationDataPlaneInput(ctx)
	diags.Append(automationDataPlaneDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.AutomationCreateOrUpdateDataPlaneRequest{
		OrganizationID:      organizationID,
		EnvironmentID:       environmentID,
		AutomationDataPlane: *automationDataPlane,
	}

	return &out, diags
}

func (r *DataPlaneResourceModel) ToOperationsAutomationDeleteDataPlaneRequest(ctx context.Context) (*operations.AutomationDeleteDataPlaneRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var id string
	id = r.ID.ValueString()

	out := operations.AutomationDeleteDataPlaneRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		ID:             id,
	}

	return &out, diags
}

func (r *DataPlaneResourceModel) ToOperationsAutomationGetDataPlaneRequest(ctx context.Context) (*operations.AutomationGetDataPlaneRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var id string
	id = r.ID.ValueString()

	out := operations.AutomationGetDataPlaneRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		ID:             id,
	}

	return &out, diags
}

func (r *DataPlaneResourceModel) ToSharedAutomationDataPlaneInput(ctx context.Context) (*shared.AutomationDataPlaneInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	var configuration *shared.Configuration
	if r.Configuration != nil {
		configuration = &shared.Configuration{}
	}
	gatewayURL := new(string)
	if !r.GatewayURL.IsUnknown() && !r.GatewayURL.IsNull() {
		*gatewayURL = r.GatewayURL.ValueString()
	} else {
		gatewayURL = nil
	}
	var id string
	id = r.ID.ValueString()

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	typeVar := new(string)
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		*typeVar = r.Type.ValueString()
	} else {
		typeVar = nil
	}
	out := shared.AutomationDataPlaneInput{
		Configuration: configuration,
		GatewayURL:    gatewayURL,
		ID:            id,
		Name:          name,
		Type:          typeVar,
	}

	return &out, diags
}
