// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4942f28340ad

package provider

import (
	"context"
	"github.com/gravitee-io/terraform-provider-am/internal/provider/typeconvert"
	tfTypes "github.com/gravitee-io/terraform-provider-am/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *DomainResourceModel) RefreshFromSharedAutomationDomain(ctx context.Context, resp *shared.AutomationDomain) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.AccountSettings == nil {
			r.AccountSettings = nil
		} else {
			r.AccountSettings = &tfTypes.AutomationAccountSettings{}
			r.AccountSettings.AccountBlockedDuration = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.AccountSettings.AccountBlockedDuration))
			r.AccountSettings.AutoLoginAfterRegistration = types.BoolPointerValue(resp.AccountSettings.AutoLoginAfterRegistration)
			r.AccountSettings.AutoLoginAfterResetPassword = types.BoolPointerValue(resp.AccountSettings.AutoLoginAfterResetPassword)
			r.AccountSettings.CompleteRegistrationWhenResetPassword = types.BoolPointerValue(resp.AccountSettings.CompleteRegistrationWhenResetPassword)
			r.AccountSettings.DefaultIdentityProviderForRegistration = types.StringPointerValue(resp.AccountSettings.DefaultIdentityProviderForRegistration)
			r.AccountSettings.DeletePasswordlessDevicesAfterResetPassword = types.BoolPointerValue(resp.AccountSettings.DeletePasswordlessDevicesAfterResetPassword)
			r.AccountSettings.DynamicUserRegistration = types.BoolPointerValue(resp.AccountSettings.DynamicUserRegistration)
			r.AccountSettings.Inherited = types.BoolPointerValue(resp.AccountSettings.Inherited)
			r.AccountSettings.LoginAttemptsDetectionEnabled = types.BoolPointerValue(resp.AccountSettings.LoginAttemptsDetectionEnabled)
			r.AccountSettings.LoginAttemptsResetTime = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.AccountSettings.LoginAttemptsResetTime))
			r.AccountSettings.MaxLoginAttempts = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.AccountSettings.MaxLoginAttempts))
			r.AccountSettings.MfaChallengeAttemptsDetectionEnabled = types.BoolPointerValue(resp.AccountSettings.MfaChallengeAttemptsDetectionEnabled)
			r.AccountSettings.MfaChallengeAttemptsResetTime = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.AccountSettings.MfaChallengeAttemptsResetTime))
			r.AccountSettings.MfaChallengeMaxAttempts = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.AccountSettings.MfaChallengeMaxAttempts))
			r.AccountSettings.MfaChallengeSendVerifyAlertEmail = types.BoolPointerValue(resp.AccountSettings.MfaChallengeSendVerifyAlertEmail)
			r.AccountSettings.RedirectURIAfterRegistration = types.StringPointerValue(resp.AccountSettings.RedirectURIAfterRegistration)
			r.AccountSettings.RedirectURIAfterResetPassword = types.StringPointerValue(resp.AccountSettings.RedirectURIAfterResetPassword)
			r.AccountSettings.RememberMe = types.BoolPointerValue(resp.AccountSettings.RememberMe)
			r.AccountSettings.RememberMeDuration = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.AccountSettings.RememberMeDuration))
			r.AccountSettings.ResetPasswordConfirmIdentity = types.BoolPointerValue(resp.AccountSettings.ResetPasswordConfirmIdentity)
			r.AccountSettings.ResetPasswordCustomForm = types.BoolPointerValue(resp.AccountSettings.ResetPasswordCustomForm)
			r.AccountSettings.ResetPasswordCustomFormFields = []tfTypes.FormField{}

			for _, resetPasswordCustomFormFieldsItem := range resp.AccountSettings.ResetPasswordCustomFormFields {
				var resetPasswordCustomFormFields tfTypes.FormField

				resetPasswordCustomFormFields.Key = types.StringPointerValue(resetPasswordCustomFormFieldsItem.Key)
				resetPasswordCustomFormFields.Label = types.StringPointerValue(resetPasswordCustomFormFieldsItem.Label)
				resetPasswordCustomFormFields.Type = types.StringPointerValue(resetPasswordCustomFormFieldsItem.Type)

				r.AccountSettings.ResetPasswordCustomFormFields = append(r.AccountSettings.ResetPasswordCustomFormFields, resetPasswordCustomFormFields)
			}
			r.AccountSettings.ResetPasswordInvalidateTokens = types.BoolPointerValue(resp.AccountSettings.ResetPasswordInvalidateTokens)
			r.AccountSettings.SendRecoverAccountEmail = types.BoolPointerValue(resp.AccountSettings.SendRecoverAccountEmail)
			r.AccountSettings.SendVerifyRegistrationAccountEmail = types.BoolPointerValue(resp.AccountSettings.SendVerifyRegistrationAccountEmail)
		}
		r.AlertEnabled = types.BoolPointerValue(resp.AlertEnabled)
		if resp.CertificateSettings == nil {
			r.CertificateSettings = nil
		} else {
			r.CertificateSettings = &tfTypes.AutomationCertificateSettings{}
			r.CertificateSettings.FallbackCertificate = types.StringPointerValue(resp.CertificateSettings.FallbackCertificate)
		}
		if resp.CorsSettings == nil {
			r.CorsSettings = nil
		} else {
			r.CorsSettings = &tfTypes.CorsSettings{}
			r.CorsSettings.AllowCredentials = types.BoolPointerValue(resp.CorsSettings.AllowCredentials)
			r.CorsSettings.AllowedHeaders = make([]types.String, 0, len(resp.CorsSettings.AllowedHeaders))
			for _, v := range resp.CorsSettings.AllowedHeaders {
				r.CorsSettings.AllowedHeaders = append(r.CorsSettings.AllowedHeaders, types.StringValue(v))
			}
			r.CorsSettings.AllowedMethods = make([]types.String, 0, len(resp.CorsSettings.AllowedMethods))
			for _, v := range resp.CorsSettings.AllowedMethods {
				r.CorsSettings.AllowedMethods = append(r.CorsSettings.AllowedMethods, types.StringValue(v))
			}
			r.CorsSettings.AllowedOrigins = make([]types.String, 0, len(resp.CorsSettings.AllowedOrigins))
			for _, v := range resp.CorsSettings.AllowedOrigins {
				r.CorsSettings.AllowedOrigins = append(r.CorsSettings.AllowedOrigins, types.StringValue(v))
			}
			r.CorsSettings.Enabled = types.BoolPointerValue(resp.CorsSettings.Enabled)
			r.CorsSettings.MaxAge = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.CorsSettings.MaxAge))
		}
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.DataPlaneID = types.StringValue(resp.DataPlaneID)
		r.Description = types.StringPointerValue(resp.Description)
		r.Enabled = types.BoolPointerValue(resp.Enabled)
		r.Key = types.StringValue(resp.Key)
		if resp.LoginSettings == nil {
			r.LoginSettings = nil
		} else {
			r.LoginSettings = &tfTypes.LoginSettings{}
			r.LoginSettings.CertificateBasedAuthEnabled = types.BoolPointerValue(resp.LoginSettings.CertificateBasedAuthEnabled)
			r.LoginSettings.CertificateBasedAuthURL = types.StringPointerValue(resp.LoginSettings.CertificateBasedAuthURL)
			r.LoginSettings.EnforcePasswordPolicyEnabled = types.BoolPointerValue(resp.LoginSettings.EnforcePasswordPolicyEnabled)
			r.LoginSettings.ForgotPasswordEnabled = types.BoolPointerValue(resp.LoginSettings.ForgotPasswordEnabled)
			r.LoginSettings.HideForm = types.BoolPointerValue(resp.LoginSettings.HideForm)
			r.LoginSettings.IdentifierFirstEnabled = types.BoolPointerValue(resp.LoginSettings.IdentifierFirstEnabled)
			r.LoginSettings.Inherited = types.BoolPointerValue(resp.LoginSettings.Inherited)
			r.LoginSettings.MagicLinkAuthEnabled = types.BoolPointerValue(resp.LoginSettings.MagicLinkAuthEnabled)
			r.LoginSettings.PasswordlessDeviceNamingEnabled = types.BoolPointerValue(resp.LoginSettings.PasswordlessDeviceNamingEnabled)
			r.LoginSettings.PasswordlessEnabled = types.BoolPointerValue(resp.LoginSettings.PasswordlessEnabled)
			r.LoginSettings.PasswordlessEnforcePasswordEnabled = types.BoolPointerValue(resp.LoginSettings.PasswordlessEnforcePasswordEnabled)
			r.LoginSettings.PasswordlessEnforcePasswordMaxAge = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.LoginSettings.PasswordlessEnforcePasswordMaxAge))
			r.LoginSettings.PasswordlessRememberDeviceEnabled = types.BoolPointerValue(resp.LoginSettings.PasswordlessRememberDeviceEnabled)
			r.LoginSettings.RegisterEnabled = types.BoolPointerValue(resp.LoginSettings.RegisterEnabled)
			r.LoginSettings.RememberMeEnabled = types.BoolPointerValue(resp.LoginSettings.RememberMeEnabled)
			r.LoginSettings.ResetPasswordOnExpiration = types.BoolPointerValue(resp.LoginSettings.ResetPasswordOnExpiration)
		}
		r.Master = types.BoolPointerValue(resp.Master)
		r.Name = types.StringValue(resp.Name)
		if resp.Oidc == nil {
			r.Oidc = nil
		} else {
			r.Oidc = &tfTypes.AutomationOidcSettings{}
			if resp.Oidc.CibaSettings == nil {
				r.Oidc.CibaSettings = nil
			} else {
				r.Oidc.CibaSettings = &tfTypes.AutomationCIBASettings{}
				r.Oidc.CibaSettings.AuthReqExpiry = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Oidc.CibaSettings.AuthReqExpiry))
				r.Oidc.CibaSettings.BindingMessageLength = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Oidc.CibaSettings.BindingMessageLength))
				r.Oidc.CibaSettings.Enabled = types.BoolPointerValue(resp.Oidc.CibaSettings.Enabled)
				r.Oidc.CibaSettings.TokenReqInterval = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Oidc.CibaSettings.TokenReqInterval))
			}
			if resp.Oidc.ClientRegistrationSettings == nil {
				r.Oidc.ClientRegistrationSettings = nil
			} else {
				r.Oidc.ClientRegistrationSettings = &tfTypes.AutomationClientRegistrationSettings{}
				r.Oidc.ClientRegistrationSettings.AllowedScopes = make([]types.String, 0, len(resp.Oidc.ClientRegistrationSettings.AllowedScopes))
				for _, v := range resp.Oidc.ClientRegistrationSettings.AllowedScopes {
					r.Oidc.ClientRegistrationSettings.AllowedScopes = append(r.Oidc.ClientRegistrationSettings.AllowedScopes, types.StringValue(v))
				}
				r.Oidc.ClientRegistrationSettings.AllowedScopesEnabled = types.BoolPointerValue(resp.Oidc.ClientRegistrationSettings.AllowedScopesEnabled)
				r.Oidc.ClientRegistrationSettings.AllowHTTPSchemeRedirectURI = types.BoolPointerValue(resp.Oidc.ClientRegistrationSettings.AllowHTTPSchemeRedirectURI)
				r.Oidc.ClientRegistrationSettings.AllowLocalhostRedirectURI = types.BoolPointerValue(resp.Oidc.ClientRegistrationSettings.AllowLocalhostRedirectURI)
				r.Oidc.ClientRegistrationSettings.AllowRedirectURIParamsExpressionLanguage = types.BoolPointerValue(resp.Oidc.ClientRegistrationSettings.AllowRedirectURIParamsExpressionLanguage)
				r.Oidc.ClientRegistrationSettings.AllowWildCardRedirectURI = types.BoolPointerValue(resp.Oidc.ClientRegistrationSettings.AllowWildCardRedirectURI)
				r.Oidc.ClientRegistrationSettings.ClientTemplateEnabled = types.BoolPointerValue(resp.Oidc.ClientRegistrationSettings.ClientTemplateEnabled)
				r.Oidc.ClientRegistrationSettings.DefaultScopes = make([]types.String, 0, len(resp.Oidc.ClientRegistrationSettings.DefaultScopes))
				for _, v := range resp.Oidc.ClientRegistrationSettings.DefaultScopes {
					r.Oidc.ClientRegistrationSettings.DefaultScopes = append(r.Oidc.ClientRegistrationSettings.DefaultScopes, types.StringValue(v))
				}
				r.Oidc.ClientRegistrationSettings.DynamicClientRegistrationEnabled = types.BoolPointerValue(resp.Oidc.ClientRegistrationSettings.DynamicClientRegistrationEnabled)
				r.Oidc.ClientRegistrationSettings.OpenDynamicClientRegistrationEnabled = types.BoolPointerValue(resp.Oidc.ClientRegistrationSettings.OpenDynamicClientRegistrationEnabled)
			}
			r.Oidc.PostLogoutRedirectUris = make([]types.String, 0, len(resp.Oidc.PostLogoutRedirectUris))
			for _, v := range resp.Oidc.PostLogoutRedirectUris {
				r.Oidc.PostLogoutRedirectUris = append(r.Oidc.PostLogoutRedirectUris, types.StringValue(v))
			}
			r.Oidc.RedirectURIStrictMatching = types.BoolPointerValue(resp.Oidc.RedirectURIStrictMatching)
			r.Oidc.RequestUris = make([]types.String, 0, len(resp.Oidc.RequestUris))
			for _, v := range resp.Oidc.RequestUris {
				r.Oidc.RequestUris = append(r.Oidc.RequestUris, types.StringValue(v))
			}
			if resp.Oidc.SecurityProfileSettings == nil {
				r.Oidc.SecurityProfileSettings = nil
			} else {
				r.Oidc.SecurityProfileSettings = &tfTypes.SecurityProfileSettings{}
				r.Oidc.SecurityProfileSettings.EnableFapiBrazil = types.BoolPointerValue(resp.Oidc.SecurityProfileSettings.EnableFapiBrazil)
				r.Oidc.SecurityProfileSettings.EnablePlainFapi = types.BoolPointerValue(resp.Oidc.SecurityProfileSettings.EnablePlainFapi)
			}
			if resp.Oidc.WorkloadIdentitySettings == nil {
				r.Oidc.WorkloadIdentitySettings = nil
			} else {
				r.Oidc.WorkloadIdentitySettings = &tfTypes.SpiffeDomainSettings{}
				r.Oidc.WorkloadIdentitySettings.AllowPrivateIPAddress = types.BoolPointerValue(resp.Oidc.WorkloadIdentitySettings.AllowPrivateIPAddress)
				r.Oidc.WorkloadIdentitySettings.AllowUnsecuredHTTPURI = types.BoolPointerValue(resp.Oidc.WorkloadIdentitySettings.AllowUnsecuredHTTPURI)
				r.Oidc.WorkloadIdentitySettings.CacheMaxEntries = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Oidc.WorkloadIdentitySettings.CacheMaxEntries))
				r.Oidc.WorkloadIdentitySettings.CacheTTLSeconds = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Oidc.WorkloadIdentitySettings.CacheTTLSeconds))
				r.Oidc.WorkloadIdentitySettings.ClockSkewSeconds = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Oidc.WorkloadIdentitySettings.ClockSkewSeconds))
				r.Oidc.WorkloadIdentitySettings.DefaultAllowedAlgorithms = make([]types.String, 0, len(resp.Oidc.WorkloadIdentitySettings.DefaultAllowedAlgorithms))
				for _, v := range resp.Oidc.WorkloadIdentitySettings.DefaultAllowedAlgorithms {
					r.Oidc.WorkloadIdentitySettings.DefaultAllowedAlgorithms = append(r.Oidc.WorkloadIdentitySettings.DefaultAllowedAlgorithms, types.StringValue(v))
				}
				r.Oidc.WorkloadIdentitySettings.Enabled = types.BoolPointerValue(resp.Oidc.WorkloadIdentitySettings.Enabled)
				r.Oidc.WorkloadIdentitySettings.FetchTimeoutMs = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Oidc.WorkloadIdentitySettings.FetchTimeoutMs))
				r.Oidc.WorkloadIdentitySettings.MaxJwtLifetimeSeconds = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Oidc.WorkloadIdentitySettings.MaxJwtLifetimeSeconds))
				r.Oidc.WorkloadIdentitySettings.MaxResponseSizeKb = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Oidc.WorkloadIdentitySettings.MaxResponseSizeKb))
			}
		}
		if resp.PasswordSettings == nil {
			r.PasswordSettings = nil
		} else {
			r.PasswordSettings = &tfTypes.PasswordSettings{}
			r.PasswordSettings.ExcludePasswordsInDictionary = types.BoolPointerValue(resp.PasswordSettings.ExcludePasswordsInDictionary)
			r.PasswordSettings.ExcludeUserProfileInfoInPassword = types.BoolPointerValue(resp.PasswordSettings.ExcludeUserProfileInfoInPassword)
			r.PasswordSettings.ExpiryDuration = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.PasswordSettings.ExpiryDuration))
			r.PasswordSettings.IncludeNumbers = types.BoolPointerValue(resp.PasswordSettings.IncludeNumbers)
			r.PasswordSettings.IncludeSpecialCharacters = types.BoolPointerValue(resp.PasswordSettings.IncludeSpecialCharacters)
			r.PasswordSettings.Inherited = types.BoolPointerValue(resp.PasswordSettings.Inherited)
			r.PasswordSettings.LettersInMixedCase = types.BoolPointerValue(resp.PasswordSettings.LettersInMixedCase)
			r.PasswordSettings.MaxConsecutiveLetters = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.PasswordSettings.MaxConsecutiveLetters))
			r.PasswordSettings.MaxLength = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.PasswordSettings.MaxLength))
			r.PasswordSettings.MinLength = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.PasswordSettings.MinLength))
			r.PasswordSettings.OldPasswords = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.PasswordSettings.OldPasswords))
			r.PasswordSettings.PasswordHistoryEnabled = types.BoolPointerValue(resp.PasswordSettings.PasswordHistoryEnabled)
		}
		r.Path = types.StringValue(resp.Path)
		if resp.Saml == nil {
			r.Saml = nil
		} else {
			r.Saml = &tfTypes.AutomationSamlSettings{}
			r.Saml.Certificate = types.StringPointerValue(resp.Saml.Certificate)
			r.Saml.Enabled = types.BoolPointerValue(resp.Saml.Enabled)
			r.Saml.EntityID = types.StringPointerValue(resp.Saml.EntityID)
		}
		if resp.Scim == nil {
			r.Scim = nil
		} else {
			r.Scim = &tfTypes.SCIMSettings{}
			r.Scim.Enabled = types.BoolPointerValue(resp.Scim.Enabled)
			r.Scim.IdpSelectionEnabled = types.BoolPointerValue(resp.Scim.IdpSelectionEnabled)
			r.Scim.IdpSelectionRule = types.StringPointerValue(resp.Scim.IdpSelectionRule)
		}
		if resp.SecretExpirationSettings == nil {
			r.SecretExpirationSettings = nil
		} else {
			r.SecretExpirationSettings = &tfTypes.SecretExpirationSettings{}
			r.SecretExpirationSettings.Enabled = types.BoolPointerValue(resp.SecretExpirationSettings.Enabled)
			r.SecretExpirationSettings.ExpiryTimeSeconds = types.Int64PointerValue(resp.SecretExpirationSettings.ExpiryTimeSeconds)
		}
		if resp.SelfServiceAccountManagementSettings == nil {
			r.SelfServiceAccountManagementSettings = nil
		} else {
			r.SelfServiceAccountManagementSettings = &tfTypes.SelfServiceAccountManagementSettings{}
			r.SelfServiceAccountManagementSettings.Enabled = types.BoolPointerValue(resp.SelfServiceAccountManagementSettings.Enabled)
			if resp.SelfServiceAccountManagementSettings.ResetPassword == nil {
				r.SelfServiceAccountManagementSettings.ResetPassword = nil
			} else {
				r.SelfServiceAccountManagementSettings.ResetPassword = &tfTypes.ResetPasswordSettings{}
				r.SelfServiceAccountManagementSettings.ResetPassword.OldPasswordRequired = types.BoolPointerValue(resp.SelfServiceAccountManagementSettings.ResetPassword.OldPasswordRequired)
				r.SelfServiceAccountManagementSettings.ResetPassword.TokenAge = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.SelfServiceAccountManagementSettings.ResetPassword.TokenAge))
			}
		}
		r.Tags = make([]types.String, 0, len(resp.Tags))
		for _, v := range resp.Tags {
			r.Tags = append(r.Tags, types.StringValue(v))
		}
		if resp.TokenExchangeSettings == nil {
			r.TokenExchangeSettings = nil
		} else {
			r.TokenExchangeSettings = &tfTypes.TokenExchangeSettings{}
			r.TokenExchangeSettings.AllowDelegation = types.BoolPointerValue(resp.TokenExchangeSettings.AllowDelegation)
			r.TokenExchangeSettings.AllowedActorTokenTypes = make([]types.String, 0, len(resp.TokenExchangeSettings.AllowedActorTokenTypes))
			for _, v := range resp.TokenExchangeSettings.AllowedActorTokenTypes {
				r.TokenExchangeSettings.AllowedActorTokenTypes = append(r.TokenExchangeSettings.AllowedActorTokenTypes, types.StringValue(v))
			}
			r.TokenExchangeSettings.AllowedRequestedTokenTypes = make([]types.String, 0, len(resp.TokenExchangeSettings.AllowedRequestedTokenTypes))
			for _, v := range resp.TokenExchangeSettings.AllowedRequestedTokenTypes {
				r.TokenExchangeSettings.AllowedRequestedTokenTypes = append(r.TokenExchangeSettings.AllowedRequestedTokenTypes, types.StringValue(v))
			}
			r.TokenExchangeSettings.AllowedSubjectTokenTypes = make([]types.String, 0, len(resp.TokenExchangeSettings.AllowedSubjectTokenTypes))
			for _, v := range resp.TokenExchangeSettings.AllowedSubjectTokenTypes {
				r.TokenExchangeSettings.AllowedSubjectTokenTypes = append(r.TokenExchangeSettings.AllowedSubjectTokenTypes, types.StringValue(v))
			}
			r.TokenExchangeSettings.AllowImpersonation = types.BoolPointerValue(resp.TokenExchangeSettings.AllowImpersonation)
			r.TokenExchangeSettings.Enabled = types.BoolPointerValue(resp.TokenExchangeSettings.Enabled)
			r.TokenExchangeSettings.MaxDelegationDepth = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.TokenExchangeSettings.MaxDelegationDepth))
			if resp.TokenExchangeSettings.TokenExchangeOAuthSettings == nil {
				r.TokenExchangeSettings.TokenExchangeOAuthSettings = nil
			} else {
				r.TokenExchangeSettings.TokenExchangeOAuthSettings = &tfTypes.TokenExchangeOAuthSettings{}
				r.TokenExchangeSettings.TokenExchangeOAuthSettings.Inherited = types.BoolPointerValue(resp.TokenExchangeSettings.TokenExchangeOAuthSettings.Inherited)
				if resp.TokenExchangeSettings.TokenExchangeOAuthSettings.ScopeHandling != nil {
					r.TokenExchangeSettings.TokenExchangeOAuthSettings.ScopeHandling = types.StringValue(string(*resp.TokenExchangeSettings.TokenExchangeOAuthSettings.ScopeHandling))
				} else {
					r.TokenExchangeSettings.TokenExchangeOAuthSettings.ScopeHandling = types.StringNull()
				}
			}
			r.TokenExchangeSettings.TrustedIssuers = []tfTypes.TrustedIssuer{}

			for _, trustedIssuersItem := range resp.TokenExchangeSettings.TrustedIssuers {
				var trustedIssuers tfTypes.TrustedIssuer

				trustedIssuers.Certificate = types.StringPointerValue(trustedIssuersItem.Certificate)
				trustedIssuers.Issuer = types.StringPointerValue(trustedIssuersItem.Issuer)
				trustedIssuers.JwksURI = types.StringPointerValue(trustedIssuersItem.JwksURI)
				if trustedIssuersItem.KeyResolutionMethod != nil {
					trustedIssuers.KeyResolutionMethod = types.StringValue(string(*trustedIssuersItem.KeyResolutionMethod))
				} else {
					trustedIssuers.KeyResolutionMethod = types.StringNull()
				}
				if len(trustedIssuersItem.ScopeMappings) > 0 {
					trustedIssuers.ScopeMappings = make(map[string]types.String, len(trustedIssuersItem.ScopeMappings))
					for key, value := range trustedIssuersItem.ScopeMappings {
						trustedIssuers.ScopeMappings[key] = types.StringValue(value)
					}
				}
				trustedIssuers.UserBindingCriteria = []tfTypes.UserBindingCriterion{}

				for _, userBindingCriteriaItem := range trustedIssuersItem.UserBindingCriteria {
					var userBindingCriteria tfTypes.UserBindingCriterion

					userBindingCriteria.Attribute = types.StringPointerValue(userBindingCriteriaItem.Attribute)
					userBindingCriteria.Expression = types.StringPointerValue(userBindingCriteriaItem.Expression)

					trustedIssuers.UserBindingCriteria = append(trustedIssuers.UserBindingCriteria, userBindingCriteria)
				}
				trustedIssuers.UserBindingEnabled = types.BoolPointerValue(trustedIssuersItem.UserBindingEnabled)

				r.TokenExchangeSettings.TrustedIssuers = append(r.TokenExchangeSettings.TrustedIssuers, trustedIssuers)
			}
		}
		if resp.Uma == nil {
			r.Uma = nil
		} else {
			r.Uma = &tfTypes.UMASettings{}
			r.Uma.Enabled = types.BoolPointerValue(resp.Uma.Enabled)
		}
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		r.VhostMode = types.BoolPointerValue(resp.VhostMode)
		r.Vhosts = []tfTypes.VirtualHost{}

		for _, vhostsItem := range resp.Vhosts {
			var vhosts tfTypes.VirtualHost

			vhosts.Host = types.StringPointerValue(vhostsItem.Host)
			vhosts.OverrideEntrypoint = types.BoolPointerValue(vhostsItem.OverrideEntrypoint)
			vhosts.Path = types.StringPointerValue(vhostsItem.Path)

			r.Vhosts = append(r.Vhosts, vhosts)
		}
		if resp.WebAuthnSettings == nil {
			r.WebAuthnSettings = nil
		} else {
			r.WebAuthnSettings = &tfTypes.WebAuthnSettings{}
			if resp.WebAuthnSettings.AttestationConveyancePreference != nil {
				r.WebAuthnSettings.AttestationConveyancePreference = types.StringValue(string(*resp.WebAuthnSettings.AttestationConveyancePreference))
			} else {
				r.WebAuthnSettings.AttestationConveyancePreference = types.StringNull()
			}
			if resp.WebAuthnSettings.AuthenticatorAttachment != nil {
				r.WebAuthnSettings.AuthenticatorAttachment = types.StringValue(string(*resp.WebAuthnSettings.AuthenticatorAttachment))
			} else {
				r.WebAuthnSettings.AuthenticatorAttachment = types.StringNull()
			}
			if len(resp.WebAuthnSettings.Certificates) > 0 {
				r.WebAuthnSettings.Certificates = make(map[string]tfTypes.Certificates, len(resp.WebAuthnSettings.Certificates))
				for certificatesKey, _ := range resp.WebAuthnSettings.Certificates {
					var certificatesResult tfTypes.Certificates

					r.WebAuthnSettings.Certificates[certificatesKey] = certificatesResult
				}
			}
			r.WebAuthnSettings.EnforceAuthenticatorIntegrity = types.BoolPointerValue(resp.WebAuthnSettings.EnforceAuthenticatorIntegrity)
			r.WebAuthnSettings.EnforceAuthenticatorIntegrityMaxAge = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.WebAuthnSettings.EnforceAuthenticatorIntegrityMaxAge))
			r.WebAuthnSettings.ForceRegistration = types.BoolPointerValue(resp.WebAuthnSettings.ForceRegistration)
			r.WebAuthnSettings.Origin = types.StringPointerValue(resp.WebAuthnSettings.Origin)
			r.WebAuthnSettings.RelyingPartyID = types.StringPointerValue(resp.WebAuthnSettings.RelyingPartyID)
			r.WebAuthnSettings.RelyingPartyName = types.StringPointerValue(resp.WebAuthnSettings.RelyingPartyName)
			r.WebAuthnSettings.RequireResidentKey = types.BoolPointerValue(resp.WebAuthnSettings.RequireResidentKey)
			if resp.WebAuthnSettings.UserVerification != nil {
				r.WebAuthnSettings.UserVerification = types.StringValue(string(*resp.WebAuthnSettings.UserVerification))
			} else {
				r.WebAuthnSettings.UserVerification = types.StringNull()
			}
		}
	}

	return diags
}

func (r *DomainResourceModel) ToOperationsAutomationCreateOrUpdateDomainRequest(ctx context.Context) (*operations.AutomationCreateOrUpdateDomainRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	automationDomain, automationDomainDiags := r.ToSharedAutomationDomainInput(ctx)
	diags.Append(automationDomainDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.AutomationCreateOrUpdateDomainRequest{
		OrganizationID:   organizationID,
		EnvironmentID:    environmentID,
		AutomationDomain: *automationDomain,
	}

	return &out, diags
}

func (r *DomainResourceModel) ToOperationsAutomationDeleteDomainRequest(ctx context.Context) (*operations.AutomationDeleteDomainRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var key string
	key = r.Key.ValueString()

	out := operations.AutomationDeleteDomainRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		Key:            key,
	}

	return &out, diags
}

func (r *DomainResourceModel) ToOperationsAutomationGetDomainRequest(ctx context.Context) (*operations.AutomationGetDomainRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var key string
	key = r.Key.ValueString()

	out := operations.AutomationGetDomainRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		Key:            key,
	}

	return &out, diags
}

func (r *DomainResourceModel) ToSharedAutomationDomainInput(ctx context.Context) (*shared.AutomationDomainInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	var accountSettings *shared.AutomationAccountSettings
	if r.AccountSettings != nil {
		accountBlockedDuration := new(int)
		if !r.AccountSettings.AccountBlockedDuration.IsUnknown() && !r.AccountSettings.AccountBlockedDuration.IsNull() {
			*accountBlockedDuration = int(r.AccountSettings.AccountBlockedDuration.ValueInt32())
		} else {
			accountBlockedDuration = nil
		}
		autoLoginAfterRegistration := new(bool)
		if !r.AccountSettings.AutoLoginAfterRegistration.IsUnknown() && !r.AccountSettings.AutoLoginAfterRegistration.IsNull() {
			*autoLoginAfterRegistration = r.AccountSettings.AutoLoginAfterRegistration.ValueBool()
		} else {
			autoLoginAfterRegistration = nil
		}
		autoLoginAfterResetPassword := new(bool)
		if !r.AccountSettings.AutoLoginAfterResetPassword.IsUnknown() && !r.AccountSettings.AutoLoginAfterResetPassword.IsNull() {
			*autoLoginAfterResetPassword = r.AccountSettings.AutoLoginAfterResetPassword.ValueBool()
		} else {
			autoLoginAfterResetPassword = nil
		}
		completeRegistrationWhenResetPassword := new(bool)
		if !r.AccountSettings.CompleteRegistrationWhenResetPassword.IsUnknown() && !r.AccountSettings.CompleteRegistrationWhenResetPassword.IsNull() {
			*completeRegistrationWhenResetPassword = r.AccountSettings.CompleteRegistrationWhenResetPassword.ValueBool()
		} else {
			completeRegistrationWhenResetPassword = nil
		}
		defaultIdentityProviderForRegistration := new(string)
		if !r.AccountSettings.DefaultIdentityProviderForRegistration.IsUnknown() && !r.AccountSettings.DefaultIdentityProviderForRegistration.IsNull() {
			*defaultIdentityProviderForRegistration = r.AccountSettings.DefaultIdentityProviderForRegistration.ValueString()
		} else {
			defaultIdentityProviderForRegistration = nil
		}
		deletePasswordlessDevicesAfterResetPassword := new(bool)
		if !r.AccountSettings.DeletePasswordlessDevicesAfterResetPassword.IsUnknown() && !r.AccountSettings.DeletePasswordlessDevicesAfterResetPassword.IsNull() {
			*deletePasswordlessDevicesAfterResetPassword = r.AccountSettings.DeletePasswordlessDevicesAfterResetPassword.ValueBool()
		} else {
			deletePasswordlessDevicesAfterResetPassword = nil
		}
		dynamicUserRegistration := new(bool)
		if !r.AccountSettings.DynamicUserRegistration.IsUnknown() && !r.AccountSettings.DynamicUserRegistration.IsNull() {
			*dynamicUserRegistration = r.AccountSettings.DynamicUserRegistration.ValueBool()
		} else {
			dynamicUserRegistration = nil
		}
		inherited := new(bool)
		if !r.AccountSettings.Inherited.IsUnknown() && !r.AccountSettings.Inherited.IsNull() {
			*inherited = r.AccountSettings.Inherited.ValueBool()
		} else {
			inherited = nil
		}
		loginAttemptsDetectionEnabled := new(bool)
		if !r.AccountSettings.LoginAttemptsDetectionEnabled.IsUnknown() && !r.AccountSettings.LoginAttemptsDetectionEnabled.IsNull() {
			*loginAttemptsDetectionEnabled = r.AccountSettings.LoginAttemptsDetectionEnabled.ValueBool()
		} else {
			loginAttemptsDetectionEnabled = nil
		}
		loginAttemptsResetTime := new(int)
		if !r.AccountSettings.LoginAttemptsResetTime.IsUnknown() && !r.AccountSettings.LoginAttemptsResetTime.IsNull() {
			*loginAttemptsResetTime = int(r.AccountSettings.LoginAttemptsResetTime.ValueInt32())
		} else {
			loginAttemptsResetTime = nil
		}
		maxLoginAttempts := new(int)
		if !r.AccountSettings.MaxLoginAttempts.IsUnknown() && !r.AccountSettings.MaxLoginAttempts.IsNull() {
			*maxLoginAttempts = int(r.AccountSettings.MaxLoginAttempts.ValueInt32())
		} else {
			maxLoginAttempts = nil
		}
		mfaChallengeAttemptsDetectionEnabled := new(bool)
		if !r.AccountSettings.MfaChallengeAttemptsDetectionEnabled.IsUnknown() && !r.AccountSettings.MfaChallengeAttemptsDetectionEnabled.IsNull() {
			*mfaChallengeAttemptsDetectionEnabled = r.AccountSettings.MfaChallengeAttemptsDetectionEnabled.ValueBool()
		} else {
			mfaChallengeAttemptsDetectionEnabled = nil
		}
		mfaChallengeAttemptsResetTime := new(int)
		if !r.AccountSettings.MfaChallengeAttemptsResetTime.IsUnknown() && !r.AccountSettings.MfaChallengeAttemptsResetTime.IsNull() {
			*mfaChallengeAttemptsResetTime = int(r.AccountSettings.MfaChallengeAttemptsResetTime.ValueInt32())
		} else {
			mfaChallengeAttemptsResetTime = nil
		}
		mfaChallengeMaxAttempts := new(int)
		if !r.AccountSettings.MfaChallengeMaxAttempts.IsUnknown() && !r.AccountSettings.MfaChallengeMaxAttempts.IsNull() {
			*mfaChallengeMaxAttempts = int(r.AccountSettings.MfaChallengeMaxAttempts.ValueInt32())
		} else {
			mfaChallengeMaxAttempts = nil
		}
		mfaChallengeSendVerifyAlertEmail := new(bool)
		if !r.AccountSettings.MfaChallengeSendVerifyAlertEmail.IsUnknown() && !r.AccountSettings.MfaChallengeSendVerifyAlertEmail.IsNull() {
			*mfaChallengeSendVerifyAlertEmail = r.AccountSettings.MfaChallengeSendVerifyAlertEmail.ValueBool()
		} else {
			mfaChallengeSendVerifyAlertEmail = nil
		}
		redirectURIAfterRegistration := new(string)
		if !r.AccountSettings.RedirectURIAfterRegistration.IsUnknown() && !r.AccountSettings.RedirectURIAfterRegistration.IsNull() {
			*redirectURIAfterRegistration = r.AccountSettings.RedirectURIAfterRegistration.ValueString()
		} else {
			redirectURIAfterRegistration = nil
		}
		redirectURIAfterResetPassword := new(string)
		if !r.AccountSettings.RedirectURIAfterResetPassword.IsUnknown() && !r.AccountSettings.RedirectURIAfterResetPassword.IsNull() {
			*redirectURIAfterResetPassword = r.AccountSettings.RedirectURIAfterResetPassword.ValueString()
		} else {
			redirectURIAfterResetPassword = nil
		}
		rememberMe := new(bool)
		if !r.AccountSettings.RememberMe.IsUnknown() && !r.AccountSettings.RememberMe.IsNull() {
			*rememberMe = r.AccountSettings.RememberMe.ValueBool()
		} else {
			rememberMe = nil
		}
		rememberMeDuration := new(int)
		if !r.AccountSettings.RememberMeDuration.IsUnknown() && !r.AccountSettings.RememberMeDuration.IsNull() {
			*rememberMeDuration = int(r.AccountSettings.RememberMeDuration.ValueInt32())
		} else {
			rememberMeDuration = nil
		}
		resetPasswordConfirmIdentity := new(bool)
		if !r.AccountSettings.ResetPasswordConfirmIdentity.IsUnknown() && !r.AccountSettings.ResetPasswordConfirmIdentity.IsNull() {
			*resetPasswordConfirmIdentity = r.AccountSettings.ResetPasswordConfirmIdentity.ValueBool()
		} else {
			resetPasswordConfirmIdentity = nil
		}
		resetPasswordCustomForm := new(bool)
		if !r.AccountSettings.ResetPasswordCustomForm.IsUnknown() && !r.AccountSettings.ResetPasswordCustomForm.IsNull() {
			*resetPasswordCustomForm = r.AccountSettings.ResetPasswordCustomForm.ValueBool()
		} else {
			resetPasswordCustomForm = nil
		}
		resetPasswordCustomFormFields := make([]shared.FormField, 0, len(r.AccountSettings.ResetPasswordCustomFormFields))
		for resetPasswordCustomFormFieldsIndex := range r.AccountSettings.ResetPasswordCustomFormFields {
			key := new(string)
			if !r.AccountSettings.ResetPasswordCustomFormFields[resetPasswordCustomFormFieldsIndex].Key.IsUnknown() && !r.AccountSettings.ResetPasswordCustomFormFields[resetPasswordCustomFormFieldsIndex].Key.IsNull() {
				*key = r.AccountSettings.ResetPasswordCustomFormFields[resetPasswordCustomFormFieldsIndex].Key.ValueString()
			} else {
				key = nil
			}
			label := new(string)
			if !r.AccountSettings.ResetPasswordCustomFormFields[resetPasswordCustomFormFieldsIndex].Label.IsUnknown() && !r.AccountSettings.ResetPasswordCustomFormFields[resetPasswordCustomFormFieldsIndex].Label.IsNull() {
				*label = r.AccountSettings.ResetPasswordCustomFormFields[resetPasswordCustomFormFieldsIndex].Label.ValueString()
			} else {
				label = nil
			}
			typeVar := new(string)
			if !r.AccountSettings.ResetPasswordCustomFormFields[resetPasswordCustomFormFieldsIndex].Type.IsUnknown() && !r.AccountSettings.ResetPasswordCustomFormFields[resetPasswordCustomFormFieldsIndex].Type.IsNull() {
				*typeVar = r.AccountSettings.ResetPasswordCustomFormFields[resetPasswordCustomFormFieldsIndex].Type.ValueString()
			} else {
				typeVar = nil
			}
			resetPasswordCustomFormFields = append(resetPasswordCustomFormFields, shared.FormField{
				Key:   key,
				Label: label,
				Type:  typeVar,
			})
		}
		resetPasswordInvalidateTokens := new(bool)
		if !r.AccountSettings.ResetPasswordInvalidateTokens.IsUnknown() && !r.AccountSettings.ResetPasswordInvalidateTokens.IsNull() {
			*resetPasswordInvalidateTokens = r.AccountSettings.ResetPasswordInvalidateTokens.ValueBool()
		} else {
			resetPasswordInvalidateTokens = nil
		}
		sendRecoverAccountEmail := new(bool)
		if !r.AccountSettings.SendRecoverAccountEmail.IsUnknown() && !r.AccountSettings.SendRecoverAccountEmail.IsNull() {
			*sendRecoverAccountEmail = r.AccountSettings.SendRecoverAccountEmail.ValueBool()
		} else {
			sendRecoverAccountEmail = nil
		}
		sendVerifyRegistrationAccountEmail := new(bool)
		if !r.AccountSettings.SendVerifyRegistrationAccountEmail.IsUnknown() && !r.AccountSettings.SendVerifyRegistrationAccountEmail.IsNull() {
			*sendVerifyRegistrationAccountEmail = r.AccountSettings.SendVerifyRegistrationAccountEmail.ValueBool()
		} else {
			sendVerifyRegistrationAccountEmail = nil
		}
		accountSettings = &shared.AutomationAccountSettings{
			AccountBlockedDuration:                      accountBlockedDuration,
			AutoLoginAfterRegistration:                  autoLoginAfterRegistration,
			AutoLoginAfterResetPassword:                 autoLoginAfterResetPassword,
			CompleteRegistrationWhenResetPassword:       completeRegistrationWhenResetPassword,
			DefaultIdentityProviderForRegistration:      defaultIdentityProviderForRegistration,
			DeletePasswordlessDevicesAfterResetPassword: deletePasswordlessDevicesAfterResetPassword,
			DynamicUserRegistration:                     dynamicUserRegistration,
			Inherited:                                   inherited,
			LoginAttemptsDetectionEnabled:               loginAttemptsDetectionEnabled,
			LoginAttemptsResetTime:                      loginAttemptsResetTime,
			MaxLoginAttempts:                            maxLoginAttempts,
			MfaChallengeAttemptsDetectionEnabled:        mfaChallengeAttemptsDetectionEnabled,
			MfaChallengeAttemptsResetTime:               mfaChallengeAttemptsResetTime,
			MfaChallengeMaxAttempts:                     mfaChallengeMaxAttempts,
			MfaChallengeSendVerifyAlertEmail:            mfaChallengeSendVerifyAlertEmail,
			RedirectURIAfterRegistration:                redirectURIAfterRegistration,
			RedirectURIAfterResetPassword:               redirectURIAfterResetPassword,
			RememberMe:                                  rememberMe,
			RememberMeDuration:                          rememberMeDuration,
			ResetPasswordConfirmIdentity:                resetPasswordConfirmIdentity,
			ResetPasswordCustomForm:                     resetPasswordCustomForm,
			ResetPasswordCustomFormFields:               resetPasswordCustomFormFields,
			ResetPasswordInvalidateTokens:               resetPasswordInvalidateTokens,
			SendRecoverAccountEmail:                     sendRecoverAccountEmail,
			SendVerifyRegistrationAccountEmail:          sendVerifyRegistrationAccountEmail,
		}
	}
	alertEnabled := new(bool)
	if !r.AlertEnabled.IsUnknown() && !r.AlertEnabled.IsNull() {
		*alertEnabled = r.AlertEnabled.ValueBool()
	} else {
		alertEnabled = nil
	}
	var certificateSettings *shared.AutomationCertificateSettings
	if r.CertificateSettings != nil {
		fallbackCertificate := new(string)
		if !r.CertificateSettings.FallbackCertificate.IsUnknown() && !r.CertificateSettings.FallbackCertificate.IsNull() {
			*fallbackCertificate = r.CertificateSettings.FallbackCertificate.ValueString()
		} else {
			fallbackCertificate = nil
		}
		certificateSettings = &shared.AutomationCertificateSettings{
			FallbackCertificate: fallbackCertificate,
		}
	}
	var corsSettings *shared.CorsSettings
	if r.CorsSettings != nil {
		allowCredentials := new(bool)
		if !r.CorsSettings.AllowCredentials.IsUnknown() && !r.CorsSettings.AllowCredentials.IsNull() {
			*allowCredentials = r.CorsSettings.AllowCredentials.ValueBool()
		} else {
			allowCredentials = nil
		}
		allowedHeaders := make([]string, 0, len(r.CorsSettings.AllowedHeaders))
		for allowedHeadersIndex := range r.CorsSettings.AllowedHeaders {
			allowedHeaders = append(allowedHeaders, r.CorsSettings.AllowedHeaders[allowedHeadersIndex].ValueString())
		}
		allowedMethods := make([]string, 0, len(r.CorsSettings.AllowedMethods))
		for allowedMethodsIndex := range r.CorsSettings.AllowedMethods {
			allowedMethods = append(allowedMethods, r.CorsSettings.AllowedMethods[allowedMethodsIndex].ValueString())
		}
		allowedOrigins := make([]string, 0, len(r.CorsSettings.AllowedOrigins))
		for allowedOriginsIndex := range r.CorsSettings.AllowedOrigins {
			allowedOrigins = append(allowedOrigins, r.CorsSettings.AllowedOrigins[allowedOriginsIndex].ValueString())
		}
		enabled := new(bool)
		if !r.CorsSettings.Enabled.IsUnknown() && !r.CorsSettings.Enabled.IsNull() {
			*enabled = r.CorsSettings.Enabled.ValueBool()
		} else {
			enabled = nil
		}
		maxAge := new(int)
		if !r.CorsSettings.MaxAge.IsUnknown() && !r.CorsSettings.MaxAge.IsNull() {
			*maxAge = int(r.CorsSettings.MaxAge.ValueInt32())
		} else {
			maxAge = nil
		}
		corsSettings = &shared.CorsSettings{
			AllowCredentials: allowCredentials,
			AllowedHeaders:   allowedHeaders,
			AllowedMethods:   allowedMethods,
			AllowedOrigins:   allowedOrigins,
			Enabled:          enabled,
			MaxAge:           maxAge,
		}
	}
	var dataPlaneID string
	dataPlaneID = r.DataPlaneID.ValueString()

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	enabled1 := new(bool)
	if !r.Enabled.IsUnknown() && !r.Enabled.IsNull() {
		*enabled1 = r.Enabled.ValueBool()
	} else {
		enabled1 = nil
	}
	var key1 string
	key1 = r.Key.ValueString()

	var loginSettings *shared.LoginSettingsInput
	if r.LoginSettings != nil {
		certificateBasedAuthEnabled := new(bool)
		if !r.LoginSettings.CertificateBasedAuthEnabled.IsUnknown() && !r.LoginSettings.CertificateBasedAuthEnabled.IsNull() {
			*certificateBasedAuthEnabled = r.LoginSettings.CertificateBasedAuthEnabled.ValueBool()
		} else {
			certificateBasedAuthEnabled = nil
		}
		certificateBasedAuthURL := new(string)
		if !r.LoginSettings.CertificateBasedAuthURL.IsUnknown() && !r.LoginSettings.CertificateBasedAuthURL.IsNull() {
			*certificateBasedAuthURL = r.LoginSettings.CertificateBasedAuthURL.ValueString()
		} else {
			certificateBasedAuthURL = nil
		}
		forgotPasswordEnabled := new(bool)
		if !r.LoginSettings.ForgotPasswordEnabled.IsUnknown() && !r.LoginSettings.ForgotPasswordEnabled.IsNull() {
			*forgotPasswordEnabled = r.LoginSettings.ForgotPasswordEnabled.ValueBool()
		} else {
			forgotPasswordEnabled = nil
		}
		hideForm := new(bool)
		if !r.LoginSettings.HideForm.IsUnknown() && !r.LoginSettings.HideForm.IsNull() {
			*hideForm = r.LoginSettings.HideForm.ValueBool()
		} else {
			hideForm = nil
		}
		identifierFirstEnabled := new(bool)
		if !r.LoginSettings.IdentifierFirstEnabled.IsUnknown() && !r.LoginSettings.IdentifierFirstEnabled.IsNull() {
			*identifierFirstEnabled = r.LoginSettings.IdentifierFirstEnabled.ValueBool()
		} else {
			identifierFirstEnabled = nil
		}
		inherited1 := new(bool)
		if !r.LoginSettings.Inherited.IsUnknown() && !r.LoginSettings.Inherited.IsNull() {
			*inherited1 = r.LoginSettings.Inherited.ValueBool()
		} else {
			inherited1 = nil
		}
		magicLinkAuthEnabled := new(bool)
		if !r.LoginSettings.MagicLinkAuthEnabled.IsUnknown() && !r.LoginSettings.MagicLinkAuthEnabled.IsNull() {
			*magicLinkAuthEnabled = r.LoginSettings.MagicLinkAuthEnabled.ValueBool()
		} else {
			magicLinkAuthEnabled = nil
		}
		passwordlessDeviceNamingEnabled := new(bool)
		if !r.LoginSettings.PasswordlessDeviceNamingEnabled.IsUnknown() && !r.LoginSettings.PasswordlessDeviceNamingEnabled.IsNull() {
			*passwordlessDeviceNamingEnabled = r.LoginSettings.PasswordlessDeviceNamingEnabled.ValueBool()
		} else {
			passwordlessDeviceNamingEnabled = nil
		}
		passwordlessEnabled := new(bool)
		if !r.LoginSettings.PasswordlessEnabled.IsUnknown() && !r.LoginSettings.PasswordlessEnabled.IsNull() {
			*passwordlessEnabled = r.LoginSettings.PasswordlessEnabled.ValueBool()
		} else {
			passwordlessEnabled = nil
		}
		passwordlessEnforcePasswordEnabled := new(bool)
		if !r.LoginSettings.PasswordlessEnforcePasswordEnabled.IsUnknown() && !r.LoginSettings.PasswordlessEnforcePasswordEnabled.IsNull() {
			*passwordlessEnforcePasswordEnabled = r.LoginSettings.PasswordlessEnforcePasswordEnabled.ValueBool()
		} else {
			passwordlessEnforcePasswordEnabled = nil
		}
		passwordlessEnforcePasswordMaxAge := new(int)
		if !r.LoginSettings.PasswordlessEnforcePasswordMaxAge.IsUnknown() && !r.LoginSettings.PasswordlessEnforcePasswordMaxAge.IsNull() {
			*passwordlessEnforcePasswordMaxAge = int(r.LoginSettings.PasswordlessEnforcePasswordMaxAge.ValueInt32())
		} else {
			passwordlessEnforcePasswordMaxAge = nil
		}
		passwordlessRememberDeviceEnabled := new(bool)
		if !r.LoginSettings.PasswordlessRememberDeviceEnabled.IsUnknown() && !r.LoginSettings.PasswordlessRememberDeviceEnabled.IsNull() {
			*passwordlessRememberDeviceEnabled = r.LoginSettings.PasswordlessRememberDeviceEnabled.ValueBool()
		} else {
			passwordlessRememberDeviceEnabled = nil
		}
		registerEnabled := new(bool)
		if !r.LoginSettings.RegisterEnabled.IsUnknown() && !r.LoginSettings.RegisterEnabled.IsNull() {
			*registerEnabled = r.LoginSettings.RegisterEnabled.ValueBool()
		} else {
			registerEnabled = nil
		}
		rememberMeEnabled := new(bool)
		if !r.LoginSettings.RememberMeEnabled.IsUnknown() && !r.LoginSettings.RememberMeEnabled.IsNull() {
			*rememberMeEnabled = r.LoginSettings.RememberMeEnabled.ValueBool()
		} else {
			rememberMeEnabled = nil
		}
		resetPasswordOnExpiration := new(bool)
		if !r.LoginSettings.ResetPasswordOnExpiration.IsUnknown() && !r.LoginSettings.ResetPasswordOnExpiration.IsNull() {
			*resetPasswordOnExpiration = r.LoginSettings.ResetPasswordOnExpiration.ValueBool()
		} else {
			resetPasswordOnExpiration = nil
		}
		loginSettings = &shared.LoginSettingsInput{
			CertificateBasedAuthEnabled:        certificateBasedAuthEnabled,
			CertificateBasedAuthURL:            certificateBasedAuthURL,
			ForgotPasswordEnabled:              forgotPasswordEnabled,
			HideForm:                           hideForm,
			IdentifierFirstEnabled:             identifierFirstEnabled,
			Inherited:                          inherited1,
			MagicLinkAuthEnabled:               magicLinkAuthEnabled,
			PasswordlessDeviceNamingEnabled:    passwordlessDeviceNamingEnabled,
			PasswordlessEnabled:                passwordlessEnabled,
			PasswordlessEnforcePasswordEnabled: passwordlessEnforcePasswordEnabled,
			PasswordlessEnforcePasswordMaxAge:  passwordlessEnforcePasswordMaxAge,
			PasswordlessRememberDeviceEnabled:  passwordlessRememberDeviceEnabled,
			RegisterEnabled:                    registerEnabled,
			RememberMeEnabled:                  rememberMeEnabled,
			ResetPasswordOnExpiration:          resetPasswordOnExpiration,
		}
	}
	master := new(bool)
	if !r.Master.IsUnknown() && !r.Master.IsNull() {
		*master = r.Master.ValueBool()
	} else {
		master = nil
	}
	var name string
	name = r.Name.ValueString()

	var oidc *shared.AutomationOidcSettings
	if r.Oidc != nil {
		var cibaSettings *shared.AutomationCIBASettings
		if r.Oidc.CibaSettings != nil {
			authReqExpiry := new(int)
			if !r.Oidc.CibaSettings.AuthReqExpiry.IsUnknown() && !r.Oidc.CibaSettings.AuthReqExpiry.IsNull() {
				*authReqExpiry = int(r.Oidc.CibaSettings.AuthReqExpiry.ValueInt32())
			} else {
				authReqExpiry = nil
			}
			bindingMessageLength := new(int)
			if !r.Oidc.CibaSettings.BindingMessageLength.IsUnknown() && !r.Oidc.CibaSettings.BindingMessageLength.IsNull() {
				*bindingMessageLength = int(r.Oidc.CibaSettings.BindingMessageLength.ValueInt32())
			} else {
				bindingMessageLength = nil
			}
			enabled2 := new(bool)
			if !r.Oidc.CibaSettings.Enabled.IsUnknown() && !r.Oidc.CibaSettings.Enabled.IsNull() {
				*enabled2 = r.Oidc.CibaSettings.Enabled.ValueBool()
			} else {
				enabled2 = nil
			}
			tokenReqInterval := new(int)
			if !r.Oidc.CibaSettings.TokenReqInterval.IsUnknown() && !r.Oidc.CibaSettings.TokenReqInterval.IsNull() {
				*tokenReqInterval = int(r.Oidc.CibaSettings.TokenReqInterval.ValueInt32())
			} else {
				tokenReqInterval = nil
			}
			cibaSettings = &shared.AutomationCIBASettings{
				AuthReqExpiry:        authReqExpiry,
				BindingMessageLength: bindingMessageLength,
				Enabled:              enabled2,
				TokenReqInterval:     tokenReqInterval,
			}
		}
		var clientRegistrationSettings *shared.AutomationClientRegistrationSettings
		if r.Oidc.ClientRegistrationSettings != nil {
			allowHTTPSchemeRedirectURI := new(bool)
			if !r.Oidc.ClientRegistrationSettings.AllowHTTPSchemeRedirectURI.IsUnknown() && !r.Oidc.ClientRegistrationSettings.AllowHTTPSchemeRedirectURI.IsNull() {
				*allowHTTPSchemeRedirectURI = r.Oidc.ClientRegistrationSettings.AllowHTTPSchemeRedirectURI.ValueBool()
			} else {
				allowHTTPSchemeRedirectURI = nil
			}
			allowLocalhostRedirectURI := new(bool)
			if !r.Oidc.ClientRegistrationSettings.AllowLocalhostRedirectURI.IsUnknown() && !r.Oidc.ClientRegistrationSettings.AllowLocalhostRedirectURI.IsNull() {
				*allowLocalhostRedirectURI = r.Oidc.ClientRegistrationSettings.AllowLocalhostRedirectURI.ValueBool()
			} else {
				allowLocalhostRedirectURI = nil
			}
			allowRedirectURIParamsExpressionLanguage := new(bool)
			if !r.Oidc.ClientRegistrationSettings.AllowRedirectURIParamsExpressionLanguage.IsUnknown() && !r.Oidc.ClientRegistrationSettings.AllowRedirectURIParamsExpressionLanguage.IsNull() {
				*allowRedirectURIParamsExpressionLanguage = r.Oidc.ClientRegistrationSettings.AllowRedirectURIParamsExpressionLanguage.ValueBool()
			} else {
				allowRedirectURIParamsExpressionLanguage = nil
			}
			allowWildCardRedirectURI := new(bool)
			if !r.Oidc.ClientRegistrationSettings.AllowWildCardRedirectURI.IsUnknown() && !r.Oidc.ClientRegistrationSettings.AllowWildCardRedirectURI.IsNull() {
				*allowWildCardRedirectURI = r.Oidc.ClientRegistrationSettings.AllowWildCardRedirectURI.ValueBool()
			} else {
				allowWildCardRedirectURI = nil
			}
			allowedScopes := make([]string, 0, len(r.Oidc.ClientRegistrationSettings.AllowedScopes))
			for allowedScopesIndex := range r.Oidc.ClientRegistrationSettings.AllowedScopes {
				allowedScopes = append(allowedScopes, r.Oidc.ClientRegistrationSettings.AllowedScopes[allowedScopesIndex].ValueString())
			}
			allowedScopesEnabled := new(bool)
			if !r.Oidc.ClientRegistrationSettings.AllowedScopesEnabled.IsUnknown() && !r.Oidc.ClientRegistrationSettings.AllowedScopesEnabled.IsNull() {
				*allowedScopesEnabled = r.Oidc.ClientRegistrationSettings.AllowedScopesEnabled.ValueBool()
			} else {
				allowedScopesEnabled = nil
			}
			clientTemplateEnabled := new(bool)
			if !r.Oidc.ClientRegistrationSettings.ClientTemplateEnabled.IsUnknown() && !r.Oidc.ClientRegistrationSettings.ClientTemplateEnabled.IsNull() {
				*clientTemplateEnabled = r.Oidc.ClientRegistrationSettings.ClientTemplateEnabled.ValueBool()
			} else {
				clientTemplateEnabled = nil
			}
			defaultScopes := make([]string, 0, len(r.Oidc.ClientRegistrationSettings.DefaultScopes))
			for defaultScopesIndex := range r.Oidc.ClientRegistrationSettings.DefaultScopes {
				defaultScopes = append(defaultScopes, r.Oidc.ClientRegistrationSettings.DefaultScopes[defaultScopesIndex].ValueString())
			}
			dynamicClientRegistrationEnabled := new(bool)
			if !r.Oidc.ClientRegistrationSettings.DynamicClientRegistrationEnabled.IsUnknown() && !r.Oidc.ClientRegistrationSettings.DynamicClientRegistrationEnabled.IsNull() {
				*dynamicClientRegistrationEnabled = r.Oidc.ClientRegistrationSettings.DynamicClientRegistrationEnabled.ValueBool()
			} else {
				dynamicClientRegistrationEnabled = nil
			}
			openDynamicClientRegistrationEnabled := new(bool)
			if !r.Oidc.ClientRegistrationSettings.OpenDynamicClientRegistrationEnabled.IsUnknown() && !r.Oidc.ClientRegistrationSettings.OpenDynamicClientRegistrationEnabled.IsNull() {
				*openDynamicClientRegistrationEnabled = r.Oidc.ClientRegistrationSettings.OpenDynamicClientRegistrationEnabled.ValueBool()
			} else {
				openDynamicClientRegistrationEnabled = nil
			}
			clientRegistrationSettings = &shared.AutomationClientRegistrationSettings{
				AllowHTTPSchemeRedirectURI:               allowHTTPSchemeRedirectURI,
				AllowLocalhostRedirectURI:                allowLocalhostRedirectURI,
				AllowRedirectURIParamsExpressionLanguage: allowRedirectURIParamsExpressionLanguage,
				AllowWildCardRedirectURI:                 allowWildCardRedirectURI,
				AllowedScopes:                            allowedScopes,
				AllowedScopesEnabled:                     allowedScopesEnabled,
				ClientTemplateEnabled:                    clientTemplateEnabled,
				DefaultScopes:                            defaultScopes,
				DynamicClientRegistrationEnabled:         dynamicClientRegistrationEnabled,
				OpenDynamicClientRegistrationEnabled:     openDynamicClientRegistrationEnabled,
			}
		}
		postLogoutRedirectUris := make([]string, 0, len(r.Oidc.PostLogoutRedirectUris))
		for postLogoutRedirectUrisIndex := range r.Oidc.PostLogoutRedirectUris {
			postLogoutRedirectUris = append(postLogoutRedirectUris, r.Oidc.PostLogoutRedirectUris[postLogoutRedirectUrisIndex].ValueString())
		}
		redirectURIStrictMatching := new(bool)
		if !r.Oidc.RedirectURIStrictMatching.IsUnknown() && !r.Oidc.RedirectURIStrictMatching.IsNull() {
			*redirectURIStrictMatching = r.Oidc.RedirectURIStrictMatching.ValueBool()
		} else {
			redirectURIStrictMatching = nil
		}
		requestUris := make([]string, 0, len(r.Oidc.RequestUris))
		for requestUrisIndex := range r.Oidc.RequestUris {
			requestUris = append(requestUris, r.Oidc.RequestUris[requestUrisIndex].ValueString())
		}
		var securityProfileSettings *shared.SecurityProfileSettings
		if r.Oidc.SecurityProfileSettings != nil {
			enableFapiBrazil := new(bool)
			if !r.Oidc.SecurityProfileSettings.EnableFapiBrazil.IsUnknown() && !r.Oidc.SecurityProfileSettings.EnableFapiBrazil.IsNull() {
				*enableFapiBrazil = r.Oidc.SecurityProfileSettings.EnableFapiBrazil.ValueBool()
			} else {
				enableFapiBrazil = nil
			}
			enablePlainFapi := new(bool)
			if !r.Oidc.SecurityProfileSettings.EnablePlainFapi.IsUnknown() && !r.Oidc.SecurityProfileSettings.EnablePlainFapi.IsNull() {
				*enablePlainFapi = r.Oidc.SecurityProfileSettings.EnablePlainFapi.ValueBool()
			} else {
				enablePlainFapi = nil
			}
			securityProfileSettings = &shared.SecurityProfileSettings{
				EnableFapiBrazil: enableFapiBrazil,
				EnablePlainFapi:  enablePlainFapi,
			}
		}
		var workloadIdentitySettings *shared.SpiffeDomainSettings
		if r.Oidc.WorkloadIdentitySettings != nil {
			allowPrivateIPAddress := new(bool)
			if !r.Oidc.WorkloadIdentitySettings.AllowPrivateIPAddress.IsUnknown() && !r.Oidc.WorkloadIdentitySettings.AllowPrivateIPAddress.IsNull() {
				*allowPrivateIPAddress = r.Oidc.WorkloadIdentitySettings.AllowPrivateIPAddress.ValueBool()
			} else {
				allowPrivateIPAddress = nil
			}
			allowUnsecuredHTTPURI := new(bool)
			if !r.Oidc.WorkloadIdentitySettings.AllowUnsecuredHTTPURI.IsUnknown() && !r.Oidc.WorkloadIdentitySettings.AllowUnsecuredHTTPURI.IsNull() {
				*allowUnsecuredHTTPURI = r.Oidc.WorkloadIdentitySettings.AllowUnsecuredHTTPURI.ValueBool()
			} else {
				allowUnsecuredHTTPURI = nil
			}
			cacheMaxEntries := new(int)
			if !r.Oidc.WorkloadIdentitySettings.CacheMaxEntries.IsUnknown() && !r.Oidc.WorkloadIdentitySettings.CacheMaxEntries.IsNull() {
				*cacheMaxEntries = int(r.Oidc.WorkloadIdentitySettings.CacheMaxEntries.ValueInt32())
			} else {
				cacheMaxEntries = nil
			}
			cacheTTLSeconds := new(int)
			if !r.Oidc.WorkloadIdentitySettings.CacheTTLSeconds.IsUnknown() && !r.Oidc.WorkloadIdentitySettings.CacheTTLSeconds.IsNull() {
				*cacheTTLSeconds = int(r.Oidc.WorkloadIdentitySettings.CacheTTLSeconds.ValueInt32())
			} else {
				cacheTTLSeconds = nil
			}
			clockSkewSeconds := new(int)
			if !r.Oidc.WorkloadIdentitySettings.ClockSkewSeconds.IsUnknown() && !r.Oidc.WorkloadIdentitySettings.ClockSkewSeconds.IsNull() {
				*clockSkewSeconds = int(r.Oidc.WorkloadIdentitySettings.ClockSkewSeconds.ValueInt32())
			} else {
				clockSkewSeconds = nil
			}
			defaultAllowedAlgorithms := make([]string, 0, len(r.Oidc.WorkloadIdentitySettings.DefaultAllowedAlgorithms))
			for defaultAllowedAlgorithmsIndex := range r.Oidc.WorkloadIdentitySettings.DefaultAllowedAlgorithms {
				defaultAllowedAlgorithms = append(defaultAllowedAlgorithms, r.Oidc.WorkloadIdentitySettings.DefaultAllowedAlgorithms[defaultAllowedAlgorithmsIndex].ValueString())
			}
			enabled3 := new(bool)
			if !r.Oidc.WorkloadIdentitySettings.Enabled.IsUnknown() && !r.Oidc.WorkloadIdentitySettings.Enabled.IsNull() {
				*enabled3 = r.Oidc.WorkloadIdentitySettings.Enabled.ValueBool()
			} else {
				enabled3 = nil
			}
			fetchTimeoutMs := new(int)
			if !r.Oidc.WorkloadIdentitySettings.FetchTimeoutMs.IsUnknown() && !r.Oidc.WorkloadIdentitySettings.FetchTimeoutMs.IsNull() {
				*fetchTimeoutMs = int(r.Oidc.WorkloadIdentitySettings.FetchTimeoutMs.ValueInt32())
			} else {
				fetchTimeoutMs = nil
			}
			maxJwtLifetimeSeconds := new(int)
			if !r.Oidc.WorkloadIdentitySettings.MaxJwtLifetimeSeconds.IsUnknown() && !r.Oidc.WorkloadIdentitySettings.MaxJwtLifetimeSeconds.IsNull() {
				*maxJwtLifetimeSeconds = int(r.Oidc.WorkloadIdentitySettings.MaxJwtLifetimeSeconds.ValueInt32())
			} else {
				maxJwtLifetimeSeconds = nil
			}
			maxResponseSizeKb := new(int)
			if !r.Oidc.WorkloadIdentitySettings.MaxResponseSizeKb.IsUnknown() && !r.Oidc.WorkloadIdentitySettings.MaxResponseSizeKb.IsNull() {
				*maxResponseSizeKb = int(r.Oidc.WorkloadIdentitySettings.MaxResponseSizeKb.ValueInt32())
			} else {
				maxResponseSizeKb = nil
			}
			workloadIdentitySettings = &shared.SpiffeDomainSettings{
				AllowPrivateIPAddress:    allowPrivateIPAddress,
				AllowUnsecuredHTTPURI:    allowUnsecuredHTTPURI,
				CacheMaxEntries:          cacheMaxEntries,
				CacheTTLSeconds:          cacheTTLSeconds,
				ClockSkewSeconds:         clockSkewSeconds,
				DefaultAllowedAlgorithms: defaultAllowedAlgorithms,
				Enabled:                  enabled3,
				FetchTimeoutMs:           fetchTimeoutMs,
				MaxJwtLifetimeSeconds:    maxJwtLifetimeSeconds,
				MaxResponseSizeKb:        maxResponseSizeKb,
			}
		}
		oidc = &shared.AutomationOidcSettings{
			CibaSettings:               cibaSettings,
			ClientRegistrationSettings: clientRegistrationSettings,
			PostLogoutRedirectUris:     postLogoutRedirectUris,
			RedirectURIStrictMatching:  redirectURIStrictMatching,
			RequestUris:                requestUris,
			SecurityProfileSettings:    securityProfileSettings,
			WorkloadIdentitySettings:   workloadIdentitySettings,
		}
	}
	var passwordSettings *shared.PasswordSettings
	if r.PasswordSettings != nil {
		excludePasswordsInDictionary := new(bool)
		if !r.PasswordSettings.ExcludePasswordsInDictionary.IsUnknown() && !r.PasswordSettings.ExcludePasswordsInDictionary.IsNull() {
			*excludePasswordsInDictionary = r.PasswordSettings.ExcludePasswordsInDictionary.ValueBool()
		} else {
			excludePasswordsInDictionary = nil
		}
		excludeUserProfileInfoInPassword := new(bool)
		if !r.PasswordSettings.ExcludeUserProfileInfoInPassword.IsUnknown() && !r.PasswordSettings.ExcludeUserProfileInfoInPassword.IsNull() {
			*excludeUserProfileInfoInPassword = r.PasswordSettings.ExcludeUserProfileInfoInPassword.ValueBool()
		} else {
			excludeUserProfileInfoInPassword = nil
		}
		expiryDuration := new(int)
		if !r.PasswordSettings.ExpiryDuration.IsUnknown() && !r.PasswordSettings.ExpiryDuration.IsNull() {
			*expiryDuration = int(r.PasswordSettings.ExpiryDuration.ValueInt32())
		} else {
			expiryDuration = nil
		}
		includeNumbers := new(bool)
		if !r.PasswordSettings.IncludeNumbers.IsUnknown() && !r.PasswordSettings.IncludeNumbers.IsNull() {
			*includeNumbers = r.PasswordSettings.IncludeNumbers.ValueBool()
		} else {
			includeNumbers = nil
		}
		includeSpecialCharacters := new(bool)
		if !r.PasswordSettings.IncludeSpecialCharacters.IsUnknown() && !r.PasswordSettings.IncludeSpecialCharacters.IsNull() {
			*includeSpecialCharacters = r.PasswordSettings.IncludeSpecialCharacters.ValueBool()
		} else {
			includeSpecialCharacters = nil
		}
		inherited2 := new(bool)
		if !r.PasswordSettings.Inherited.IsUnknown() && !r.PasswordSettings.Inherited.IsNull() {
			*inherited2 = r.PasswordSettings.Inherited.ValueBool()
		} else {
			inherited2 = nil
		}
		lettersInMixedCase := new(bool)
		if !r.PasswordSettings.LettersInMixedCase.IsUnknown() && !r.PasswordSettings.LettersInMixedCase.IsNull() {
			*lettersInMixedCase = r.PasswordSettings.LettersInMixedCase.ValueBool()
		} else {
			lettersInMixedCase = nil
		}
		maxConsecutiveLetters := new(int)
		if !r.PasswordSettings.MaxConsecutiveLetters.IsUnknown() && !r.PasswordSettings.MaxConsecutiveLetters.IsNull() {
			*maxConsecutiveLetters = int(r.PasswordSettings.MaxConsecutiveLetters.ValueInt32())
		} else {
			maxConsecutiveLetters = nil
		}
		maxLength := new(int)
		if !r.PasswordSettings.MaxLength.IsUnknown() && !r.PasswordSettings.MaxLength.IsNull() {
			*maxLength = int(r.PasswordSettings.MaxLength.ValueInt32())
		} else {
			maxLength = nil
		}
		minLength := new(int)
		if !r.PasswordSettings.MinLength.IsUnknown() && !r.PasswordSettings.MinLength.IsNull() {
			*minLength = int(r.PasswordSettings.MinLength.ValueInt32())
		} else {
			minLength = nil
		}
		oldPasswords := new(int)
		if !r.PasswordSettings.OldPasswords.IsUnknown() && !r.PasswordSettings.OldPasswords.IsNull() {
			*oldPasswords = int(r.PasswordSettings.OldPasswords.ValueInt32())
		} else {
			oldPasswords = nil
		}
		passwordHistoryEnabled := new(bool)
		if !r.PasswordSettings.PasswordHistoryEnabled.IsUnknown() && !r.PasswordSettings.PasswordHistoryEnabled.IsNull() {
			*passwordHistoryEnabled = r.PasswordSettings.PasswordHistoryEnabled.ValueBool()
		} else {
			passwordHistoryEnabled = nil
		}
		passwordSettings = &shared.PasswordSettings{
			ExcludePasswordsInDictionary:     excludePasswordsInDictionary,
			ExcludeUserProfileInfoInPassword: excludeUserProfileInfoInPassword,
			ExpiryDuration:                   expiryDuration,
			IncludeNumbers:                   includeNumbers,
			IncludeSpecialCharacters:         includeSpecialCharacters,
			Inherited:                        inherited2,
			LettersInMixedCase:               lettersInMixedCase,
			MaxConsecutiveLetters:            maxConsecutiveLetters,
			MaxLength:                        maxLength,
			MinLength:                        minLength,
			OldPasswords:                     oldPasswords,
			PasswordHistoryEnabled:           passwordHistoryEnabled,
		}
	}
	var path string
	path = r.Path.ValueString()

	var saml *shared.AutomationSamlSettings
	if r.Saml != nil {
		certificate := new(string)
		if !r.Saml.Certificate.IsUnknown() && !r.Saml.Certificate.IsNull() {
			*certificate = r.Saml.Certificate.ValueString()
		} else {
			certificate = nil
		}
		enabled4 := new(bool)
		if !r.Saml.Enabled.IsUnknown() && !r.Saml.Enabled.IsNull() {
			*enabled4 = r.Saml.Enabled.ValueBool()
		} else {
			enabled4 = nil
		}
		entityID := new(string)
		if !r.Saml.EntityID.IsUnknown() && !r.Saml.EntityID.IsNull() {
			*entityID = r.Saml.EntityID.ValueString()
		} else {
			entityID = nil
		}
		saml = &shared.AutomationSamlSettings{
			Certificate: certificate,
			Enabled:     enabled4,
			EntityID:    entityID,
		}
	}
	var scim *shared.SCIMSettings
	if r.Scim != nil {
		enabled5 := new(bool)
		if !r.Scim.Enabled.IsUnknown() && !r.Scim.Enabled.IsNull() {
			*enabled5 = r.Scim.Enabled.ValueBool()
		} else {
			enabled5 = nil
		}
		idpSelectionEnabled := new(bool)
		if !r.Scim.IdpSelectionEnabled.IsUnknown() && !r.Scim.IdpSelectionEnabled.IsNull() {
			*idpSelectionEnabled = r.Scim.IdpSelectionEnabled.ValueBool()
		} else {
			idpSelectionEnabled = nil
		}
		idpSelectionRule := new(string)
		if !r.Scim.IdpSelectionRule.IsUnknown() && !r.Scim.IdpSelectionRule.IsNull() {
			*idpSelectionRule = r.Scim.IdpSelectionRule.ValueString()
		} else {
			idpSelectionRule = nil
		}
		scim = &shared.SCIMSettings{
			Enabled:             enabled5,
			IdpSelectionEnabled: idpSelectionEnabled,
			IdpSelectionRule:    idpSelectionRule,
		}
	}
	var secretExpirationSettings *shared.SecretExpirationSettings
	if r.SecretExpirationSettings != nil {
		enabled6 := new(bool)
		if !r.SecretExpirationSettings.Enabled.IsUnknown() && !r.SecretExpirationSettings.Enabled.IsNull() {
			*enabled6 = r.SecretExpirationSettings.Enabled.ValueBool()
		} else {
			enabled6 = nil
		}
		expiryTimeSeconds := new(int64)
		if !r.SecretExpirationSettings.ExpiryTimeSeconds.IsUnknown() && !r.SecretExpirationSettings.ExpiryTimeSeconds.IsNull() {
			*expiryTimeSeconds = r.SecretExpirationSettings.ExpiryTimeSeconds.ValueInt64()
		} else {
			expiryTimeSeconds = nil
		}
		secretExpirationSettings = &shared.SecretExpirationSettings{
			Enabled:           enabled6,
			ExpiryTimeSeconds: expiryTimeSeconds,
		}
	}
	var selfServiceAccountManagementSettings *shared.SelfServiceAccountManagementSettings
	if r.SelfServiceAccountManagementSettings != nil {
		enabled7 := new(bool)
		if !r.SelfServiceAccountManagementSettings.Enabled.IsUnknown() && !r.SelfServiceAccountManagementSettings.Enabled.IsNull() {
			*enabled7 = r.SelfServiceAccountManagementSettings.Enabled.ValueBool()
		} else {
			enabled7 = nil
		}
		var resetPassword *shared.ResetPasswordSettings
		if r.SelfServiceAccountManagementSettings.ResetPassword != nil {
			oldPasswordRequired := new(bool)
			if !r.SelfServiceAccountManagementSettings.ResetPassword.OldPasswordRequired.IsUnknown() && !r.SelfServiceAccountManagementSettings.ResetPassword.OldPasswordRequired.IsNull() {
				*oldPasswordRequired = r.SelfServiceAccountManagementSettings.ResetPassword.OldPasswordRequired.ValueBool()
			} else {
				oldPasswordRequired = nil
			}
			tokenAge := new(int)
			if !r.SelfServiceAccountManagementSettings.ResetPassword.TokenAge.IsUnknown() && !r.SelfServiceAccountManagementSettings.ResetPassword.TokenAge.IsNull() {
				*tokenAge = int(r.SelfServiceAccountManagementSettings.ResetPassword.TokenAge.ValueInt32())
			} else {
				tokenAge = nil
			}
			resetPassword = &shared.ResetPasswordSettings{
				OldPasswordRequired: oldPasswordRequired,
				TokenAge:            tokenAge,
			}
		}
		selfServiceAccountManagementSettings = &shared.SelfServiceAccountManagementSettings{
			Enabled:       enabled7,
			ResetPassword: resetPassword,
		}
	}
	tags := make([]string, 0, len(r.Tags))
	for tagsIndex := range r.Tags {
		tags = append(tags, r.Tags[tagsIndex].ValueString())
	}
	var tokenExchangeSettings *shared.TokenExchangeSettings
	if r.TokenExchangeSettings != nil {
		allowDelegation := new(bool)
		if !r.TokenExchangeSettings.AllowDelegation.IsUnknown() && !r.TokenExchangeSettings.AllowDelegation.IsNull() {
			*allowDelegation = r.TokenExchangeSettings.AllowDelegation.ValueBool()
		} else {
			allowDelegation = nil
		}
		allowImpersonation := new(bool)
		if !r.TokenExchangeSettings.AllowImpersonation.IsUnknown() && !r.TokenExchangeSettings.AllowImpersonation.IsNull() {
			*allowImpersonation = r.TokenExchangeSettings.AllowImpersonation.ValueBool()
		} else {
			allowImpersonation = nil
		}
		allowedActorTokenTypes := make([]string, 0, len(r.TokenExchangeSettings.AllowedActorTokenTypes))
		for allowedActorTokenTypesIndex := range r.TokenExchangeSettings.AllowedActorTokenTypes {
			allowedActorTokenTypes = append(allowedActorTokenTypes, r.TokenExchangeSettings.AllowedActorTokenTypes[allowedActorTokenTypesIndex].ValueString())
		}
		allowedRequestedTokenTypes := make([]string, 0, len(r.TokenExchangeSettings.AllowedRequestedTokenTypes))
		for allowedRequestedTokenTypesIndex := range r.TokenExchangeSettings.AllowedRequestedTokenTypes {
			allowedRequestedTokenTypes = append(allowedRequestedTokenTypes, r.TokenExchangeSettings.AllowedRequestedTokenTypes[allowedRequestedTokenTypesIndex].ValueString())
		}
		allowedSubjectTokenTypes := make([]string, 0, len(r.TokenExchangeSettings.AllowedSubjectTokenTypes))
		for allowedSubjectTokenTypesIndex := range r.TokenExchangeSettings.AllowedSubjectTokenTypes {
			allowedSubjectTokenTypes = append(allowedSubjectTokenTypes, r.TokenExchangeSettings.AllowedSubjectTokenTypes[allowedSubjectTokenTypesIndex].ValueString())
		}
		enabled8 := new(bool)
		if !r.TokenExchangeSettings.Enabled.IsUnknown() && !r.TokenExchangeSettings.Enabled.IsNull() {
			*enabled8 = r.TokenExchangeSettings.Enabled.ValueBool()
		} else {
			enabled8 = nil
		}
		maxDelegationDepth := new(int)
		if !r.TokenExchangeSettings.MaxDelegationDepth.IsUnknown() && !r.TokenExchangeSettings.MaxDelegationDepth.IsNull() {
			*maxDelegationDepth = int(r.TokenExchangeSettings.MaxDelegationDepth.ValueInt32())
		} else {
			maxDelegationDepth = nil
		}
		var tokenExchangeOAuthSettings *shared.TokenExchangeOAuthSettings
		if r.TokenExchangeSettings.TokenExchangeOAuthSettings != nil {
			inherited3 := new(bool)
			if !r.TokenExchangeSettings.TokenExchangeOAuthSettings.Inherited.IsUnknown() && !r.TokenExchangeSettings.TokenExchangeOAuthSettings.Inherited.IsNull() {
				*inherited3 = r.TokenExchangeSettings.TokenExchangeOAuthSettings.Inherited.ValueBool()
			} else {
				inherited3 = nil
			}
			scopeHandling := new(shared.ScopeHandling)
			if !r.TokenExchangeSettings.TokenExchangeOAuthSettings.ScopeHandling.IsUnknown() && !r.TokenExchangeSettings.TokenExchangeOAuthSettings.ScopeHandling.IsNull() {
				*scopeHandling = shared.ScopeHandling(r.TokenExchangeSettings.TokenExchangeOAuthSettings.ScopeHandling.ValueString())
			} else {
				scopeHandling = nil
			}
			tokenExchangeOAuthSettings = &shared.TokenExchangeOAuthSettings{
				Inherited:     inherited3,
				ScopeHandling: scopeHandling,
			}
		}
		trustedIssuers := make([]shared.TrustedIssuer, 0, len(r.TokenExchangeSettings.TrustedIssuers))
		for trustedIssuersIndex := range r.TokenExchangeSettings.TrustedIssuers {
			certificate1 := new(string)
			if !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].Certificate.IsUnknown() && !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].Certificate.IsNull() {
				*certificate1 = r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].Certificate.ValueString()
			} else {
				certificate1 = nil
			}
			issuer := new(string)
			if !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].Issuer.IsUnknown() && !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].Issuer.IsNull() {
				*issuer = r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].Issuer.ValueString()
			} else {
				issuer = nil
			}
			jwksURI := new(string)
			if !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].JwksURI.IsUnknown() && !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].JwksURI.IsNull() {
				*jwksURI = r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].JwksURI.ValueString()
			} else {
				jwksURI = nil
			}
			keyResolutionMethod := new(shared.KeyResolutionMethod)
			if !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].KeyResolutionMethod.IsUnknown() && !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].KeyResolutionMethod.IsNull() {
				*keyResolutionMethod = shared.KeyResolutionMethod(r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].KeyResolutionMethod.ValueString())
			} else {
				keyResolutionMethod = nil
			}
			scopeMappings := make(map[string]string)
			for scopeMappingsKey := range r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].ScopeMappings {
				var scopeMappingsInst string
				scopeMappingsInst = r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].ScopeMappings[scopeMappingsKey].ValueString()

				scopeMappings[scopeMappingsKey] = scopeMappingsInst
			}
			userBindingCriteria := make([]shared.UserBindingCriterion, 0, len(r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingCriteria))
			for userBindingCriteriaIndex := range r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingCriteria {
				attribute := new(string)
				if !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingCriteria[userBindingCriteriaIndex].Attribute.IsUnknown() && !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingCriteria[userBindingCriteriaIndex].Attribute.IsNull() {
					*attribute = r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingCriteria[userBindingCriteriaIndex].Attribute.ValueString()
				} else {
					attribute = nil
				}
				expression := new(string)
				if !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingCriteria[userBindingCriteriaIndex].Expression.IsUnknown() && !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingCriteria[userBindingCriteriaIndex].Expression.IsNull() {
					*expression = r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingCriteria[userBindingCriteriaIndex].Expression.ValueString()
				} else {
					expression = nil
				}
				userBindingCriteria = append(userBindingCriteria, shared.UserBindingCriterion{
					Attribute:  attribute,
					Expression: expression,
				})
			}
			userBindingEnabled := new(bool)
			if !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingEnabled.IsUnknown() && !r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingEnabled.IsNull() {
				*userBindingEnabled = r.TokenExchangeSettings.TrustedIssuers[trustedIssuersIndex].UserBindingEnabled.ValueBool()
			} else {
				userBindingEnabled = nil
			}
			trustedIssuers = append(trustedIssuers, shared.TrustedIssuer{
				Certificate:         certificate1,
				Issuer:              issuer,
				JwksURI:             jwksURI,
				KeyResolutionMethod: keyResolutionMethod,
				ScopeMappings:       scopeMappings,
				UserBindingCriteria: userBindingCriteria,
				UserBindingEnabled:  userBindingEnabled,
			})
		}
		tokenExchangeSettings = &shared.TokenExchangeSettings{
			AllowDelegation:            allowDelegation,
			AllowImpersonation:         allowImpersonation,
			AllowedActorTokenTypes:     allowedActorTokenTypes,
			AllowedRequestedTokenTypes: allowedRequestedTokenTypes,
			AllowedSubjectTokenTypes:   allowedSubjectTokenTypes,
			Enabled:                    enabled8,
			MaxDelegationDepth:         maxDelegationDepth,
			TokenExchangeOAuthSettings: tokenExchangeOAuthSettings,
			TrustedIssuers:             trustedIssuers,
		}
	}
	var uma *shared.UMASettings
	if r.Uma != nil {
		enabled9 := new(bool)
		if !r.Uma.Enabled.IsUnknown() && !r.Uma.Enabled.IsNull() {
			*enabled9 = r.Uma.Enabled.ValueBool()
		} else {
			enabled9 = nil
		}
		uma = &shared.UMASettings{
			Enabled: enabled9,
		}
	}
	vhostMode := new(bool)
	if !r.VhostMode.IsUnknown() && !r.VhostMode.IsNull() {
		*vhostMode = r.VhostMode.ValueBool()
	} else {
		vhostMode = nil
	}
	vhosts := make([]shared.VirtualHost, 0, len(r.Vhosts))
	for vhostsIndex := range r.Vhosts {
		host := new(string)
		if !r.Vhosts[vhostsIndex].Host.IsUnknown() && !r.Vhosts[vhostsIndex].Host.IsNull() {
			*host = r.Vhosts[vhostsIndex].Host.ValueString()
		} else {
			host = nil
		}
		overrideEntrypoint := new(bool)
		if !r.Vhosts[vhostsIndex].OverrideEntrypoint.IsUnknown() && !r.Vhosts[vhostsIndex].OverrideEntrypoint.IsNull() {
			*overrideEntrypoint = r.Vhosts[vhostsIndex].OverrideEntrypoint.ValueBool()
		} else {
			overrideEntrypoint = nil
		}
		path1 := new(string)
		if !r.Vhosts[vhostsIndex].Path.IsUnknown() && !r.Vhosts[vhostsIndex].Path.IsNull() {
			*path1 = r.Vhosts[vhostsIndex].Path.ValueString()
		} else {
			path1 = nil
		}
		vhosts = append(vhosts, shared.VirtualHost{
			Host:               host,
			OverrideEntrypoint: overrideEntrypoint,
			Path:               path1,
		})
	}
	var webAuthnSettings *shared.WebAuthnSettings
	if r.WebAuthnSettings != nil {
		attestationConveyancePreference := new(shared.AttestationConveyancePreference)
		if !r.WebAuthnSettings.AttestationConveyancePreference.IsUnknown() && !r.WebAuthnSettings.AttestationConveyancePreference.IsNull() {
			*attestationConveyancePreference = shared.AttestationConveyancePreference(r.WebAuthnSettings.AttestationConveyancePreference.ValueString())
		} else {
			attestationConveyancePreference = nil
		}
		authenticatorAttachment := new(shared.AuthenticatorAttachment)
		if !r.WebAuthnSettings.AuthenticatorAttachment.IsUnknown() && !r.WebAuthnSettings.AuthenticatorAttachment.IsNull() {
			*authenticatorAttachment = shared.AuthenticatorAttachment(r.WebAuthnSettings.AuthenticatorAttachment.ValueString())
		} else {
			authenticatorAttachment = nil
		}
		certificates := make(map[string]shared.Certificates)
		for certificatesKey := range r.WebAuthnSettings.Certificates {
			certificatesInst := shared.Certificates{}
			certificates[certificatesKey] = certificatesInst
		}
		enforceAuthenticatorIntegrity := new(bool)
		if !r.WebAuthnSettings.EnforceAuthenticatorIntegrity.IsUnknown() && !r.WebAuthnSettings.EnforceAuthenticatorIntegrity.IsNull() {
			*enforceAuthenticatorIntegrity = r.WebAuthnSettings.EnforceAuthenticatorIntegrity.ValueBool()
		} else {
			enforceAuthenticatorIntegrity = nil
		}
		enforceAuthenticatorIntegrityMaxAge := new(int)
		if !r.WebAuthnSettings.EnforceAuthenticatorIntegrityMaxAge.IsUnknown() && !r.WebAuthnSettings.EnforceAuthenticatorIntegrityMaxAge.IsNull() {
			*enforceAuthenticatorIntegrityMaxAge = int(r.WebAuthnSettings.EnforceAuthenticatorIntegrityMaxAge.ValueInt32())
		} else {
			enforceAuthenticatorIntegrityMaxAge = nil
		}
		forceRegistration := new(bool)
		if !r.WebAuthnSettings.ForceRegistration.IsUnknown() && !r.WebAuthnSettings.ForceRegistration.IsNull() {
			*forceRegistration = r.WebAuthnSettings.ForceRegistration.ValueBool()
		} else {
			forceRegistration = nil
		}
		origin := new(string)
		if !r.WebAuthnSettings.Origin.IsUnknown() && !r.WebAuthnSettings.Origin.IsNull() {
			*origin = r.WebAuthnSettings.Origin.ValueString()
		} else {
			origin = nil
		}
		relyingPartyID := new(string)
		if !r.WebAuthnSettings.RelyingPartyID.IsUnknown() && !r.WebAuthnSettings.RelyingPartyID.IsNull() {
			*relyingPartyID = r.WebAuthnSettings.RelyingPartyID.ValueString()
		} else {
			relyingPartyID = nil
		}
		relyingPartyName := new(string)
		if !r.WebAuthnSettings.RelyingPartyName.IsUnknown() && !r.WebAuthnSettings.RelyingPartyName.IsNull() {
			*relyingPartyName = r.WebAuthnSettings.RelyingPartyName.ValueString()
		} else {
			relyingPartyName = nil
		}
		requireResidentKey := new(bool)
		if !r.WebAuthnSettings.RequireResidentKey.IsUnknown() && !r.WebAuthnSettings.RequireResidentKey.IsNull() {
			*requireResidentKey = r.WebAuthnSettings.RequireResidentKey.ValueBool()
		} else {
			requireResidentKey = nil
		}
		userVerification := new(shared.UserVerification)
		if !r.WebAuthnSettings.UserVerification.IsUnknown() && !r.WebAuthnSettings.UserVerification.IsNull() {
			*userVerification = shared.UserVerification(r.WebAuthnSettings.UserVerification.ValueString())
		} else {
			userVerification = nil
		}
		webAuthnSettings = &shared.WebAuthnSettings{
			AttestationConveyancePreference:     attestationConveyancePreference,
			AuthenticatorAttachment:             authenticatorAttachment,
			Certificates:                        certificates,
			EnforceAuthenticatorIntegrity:       enforceAuthenticatorIntegrity,
			EnforceAuthenticatorIntegrityMaxAge: enforceAuthenticatorIntegrityMaxAge,
			ForceRegistration:                   forceRegistration,
			Origin:                              origin,
			RelyingPartyID:                      relyingPartyID,
			RelyingPartyName:                    relyingPartyName,
			RequireResidentKey:                  requireResidentKey,
			UserVerification:                    userVerification,
		}
	}
	out := shared.AutomationDomainInput{
		AccountSettings:                      accountSettings,
		AlertEnabled:                         alertEnabled,
		CertificateSettings:                  certificateSettings,
		CorsSettings:                         corsSettings,
		DataPlaneID:                          dataPlaneID,
		Description:                          description,
		Enabled:                              enabled1,
		Key:                                  key1,
		LoginSettings:                        loginSettings,
		Master:                               master,
		Name:                                 name,
		Oidc:                                 oidc,
		PasswordSettings:                     passwordSettings,
		Path:                                 path,
		Saml:                                 saml,
		Scim:                                 scim,
		SecretExpirationSettings:             secretExpirationSettings,
		SelfServiceAccountManagementSettings: selfServiceAccountManagementSettings,
		Tags:                                 tags,
		TokenExchangeSettings:                tokenExchangeSettings,
		Uma:                                  uma,
		VhostMode:                            vhostMode,
		Vhosts:                               vhosts,
		WebAuthnSettings:                     webAuthnSettings,
	}

	return &out, diags
}
