// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 58c5a9b0f23d

package provider

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"regexp"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &IdentityProviderResource{}
var _ resource.ResourceWithImportState = &IdentityProviderResource{}

func NewIdentityProviderResource() resource.Resource {
	return &IdentityProviderResource{}
}

// IdentityProviderResource defines the resource implementation.
type IdentityProviderResource struct {
	// Provider configured SDK client.
	client *sdk.GraviteeAm
}

// IdentityProviderResourceModel describes the resource data model.
type IdentityProviderResourceModel struct {
	Configuration   types.String              `tfsdk:"configuration"`
	CreatedAt       types.String              `tfsdk:"created_at"`
	DomainKey       types.String              `tfsdk:"domain_key"`
	DomainWhitelist []types.String            `tfsdk:"domain_whitelist"`
	EnvID           types.String              `tfsdk:"env_id"`
	GroupMapper     map[string][]types.String `tfsdk:"group_mapper"`
	Key             types.String              `tfsdk:"key"`
	Mappers         map[string]types.String   `tfsdk:"mappers"`
	Name            types.String              `tfsdk:"name"`
	OrgID           types.String              `tfsdk:"org_id"`
	RoleMapper      map[string][]types.String `tfsdk:"role_mapper"`
	System          types.Bool                `tfsdk:"system"`
	Type            types.String              `tfsdk:"type"`
	UpdatedAt       types.String              `tfsdk:"updated_at"`
}

func (r *IdentityProviderResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_identity_provider"
}

func (r *IdentityProviderResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "IdentityProvider Resource",
		Attributes: map[string]schema.Attribute{
			"configuration": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: `Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected identity provider type.`,
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `Creation timestamp (epoch milliseconds). Read-only.`,
			},
			"domain_key": schema.StringAttribute{
				Required:    true,
				Description: `Key of the domain: its stable, immutable Automation identifier within the environment.`,
			},
			"domain_whitelist": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
				Description: `Email domains allowed to authenticate through this identity provider. When set, users whose email domain is not listed are rejected.`,
			},
			"env_id": schema.StringAttribute{
				Required:    true,
				Description: `Identifier of the environment the domain belongs to.`,
			},
			"group_mapper": schema.MapAttribute{
				Optional: true,
				ElementType: types.ListType{
					ElemType: types.StringType,
				},
				Description: `Group mapper: assigns AM groups based on provider attribute values. Each entry maps a group to the user attribute expressions that grant it.`,
			},
			"key": schema.StringAttribute{
				Required:    true,
				Description: `Stable, immutable identifier for the identity provider within its domain. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the identity provider on create-or-update.`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthBetween(1, 255),
					stringvalidator.RegexMatches(regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`), "must match pattern "+regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`).String()),
				},
			},
			"mappers": schema.MapAttribute{
				Optional:    true,
				ElementType: types.StringType,
				Description: `Attribute mappers: maps provider claims to AM user profile attributes.`,
			},
			"name": schema.StringAttribute{
				Optional:    true,
				Description: `Human-readable name of the identity provider.`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthBetween(1, 255),
				},
			},
			"org_id": schema.StringAttribute{
				Required:    true,
				Description: `Identifier of the organization that owns the environment.`,
			},
			"role_mapper": schema.MapAttribute{
				Optional: true,
				ElementType: types.ListType{
					ElemType: types.StringType,
				},
				Description: `Role mapper: assigns AM roles based on provider attribute values. Each entry maps a role to the user attribute expressions that grant it.`,
			},
			"system": schema.BoolAttribute{
				Computed:    true,
				Optional:    true,
				Default:     booldefault.StaticBool(false),
				Description: `Whether this is the domain's system identity provider. Immutable after creation. When true, only key is required; the identity provider is built from the domains.identities.default.* system settings and the name, type, and configuration fields are ignored. Default: false`,
			},
			"type": schema.StringAttribute{
				Optional:    true,
				Description: `Identity provider plugin type identifier (the provider to use).`,
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `Last-update timestamp (epoch milliseconds). Read-only.`,
			},
		},
	}
}

func (r *IdentityProviderResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*AmProviderConfigureData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AmProviderConfigureData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = providerData.SDKClient
}

func (r *IdentityProviderResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *IdentityProviderResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsAutomationCreateOrUpdateIdentityProviderRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.IdentityProviders.AutomationCreateOrUpdateIdentityProvider(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AutomationIdentityProvider != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedAutomationIdentityProvider(ctx, res.AutomationIdentityProvider)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IdentityProviderResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *IdentityProviderResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsAutomationGetIdentityProviderRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.IdentityProviders.AutomationGetIdentityProvider(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AutomationIdentityProvider != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedAutomationIdentityProvider(ctx, res.AutomationIdentityProvider)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IdentityProviderResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *IdentityProviderResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsAutomationCreateOrUpdateIdentityProviderRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.IdentityProviders.AutomationCreateOrUpdateIdentityProvider(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AutomationIdentityProvider != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedAutomationIdentityProvider(ctx, res.AutomationIdentityProvider)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IdentityProviderResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *IdentityProviderResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsAutomationDeleteIdentityProviderRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.IdentityProviders.AutomationDeleteIdentityProvider(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 204, 404:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *IdentityProviderResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	dec := json.NewDecoder(bytes.NewReader([]byte(req.ID)))
	dec.DisallowUnknownFields()
	var data struct {
		DomainKey string `json:"domain_key"`
		EnvID     string `json:"env_id"`
		Key       string `json:"key"`
		OrgID     string `json:"org_id"`
	}

	if err := dec.Decode(&data); err != nil {
		resp.Diagnostics.AddError("Invalid ID", `The import ID is not valid. It is expected to be a JSON object string with the format: '{"domain_key": "customers", "env_id": "DEFAULT", "key": "corporate-ldap", "org_id": "DEFAULT"}': `+err.Error())
		return
	}

	if len(data.DomainKey) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field domain_key is required but was not found in the json encoded ID. It's expected to be a value alike '"customers"'`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("domain_key"), data.DomainKey)...)
	if len(data.EnvID) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field env_id is required but was not found in the json encoded ID. It's expected to be a value alike '"DEFAULT"'`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("env_id"), data.EnvID)...)
	if len(data.Key) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field key is required but was not found in the json encoded ID. It's expected to be a value alike '"corporate-ldap"'`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("key"), data.Key)...)
	if len(data.OrgID) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field org_id is required but was not found in the json encoded ID. It's expected to be a value alike '"DEFAULT"'`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("org_id"), data.OrgID)...)
}
