// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2716363f6d1b

package provider

import (
	"context"
	"github.com/gravitee-io/terraform-provider-am/internal/provider/typeconvert"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *IdentityProviderResourceModel) RefreshFromSharedAutomationIdentityProvider(ctx context.Context, resp *shared.AutomationIdentityProvider) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Configuration = types.StringPointerValue(resp.Configuration)
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.DomainWhitelist = make([]types.String, 0, len(resp.DomainWhitelist))
		for _, v := range resp.DomainWhitelist {
			r.DomainWhitelist = append(r.DomainWhitelist, types.StringValue(v))
		}
		if len(resp.GroupMapper) > 0 {
			r.GroupMapper = make(map[string][]types.String, len(resp.GroupMapper))
			for groupMapperKey, groupMapperValue := range resp.GroupMapper {
				var groupMapperResult []types.String
				groupMapperResult = make([]types.String, 0, len(groupMapperValue))
				for _, v := range groupMapperValue {
					groupMapperResult = append(groupMapperResult, types.StringValue(v))
				}

				r.GroupMapper[groupMapperKey] = groupMapperResult
			}
		}
		r.Key = types.StringValue(resp.Key)
		if len(resp.Mappers) > 0 {
			r.Mappers = make(map[string]types.String, len(resp.Mappers))
			for key, value := range resp.Mappers {
				r.Mappers[key] = types.StringValue(value)
			}
		}
		r.Name = types.StringPointerValue(resp.Name)
		if len(resp.RoleMapper) > 0 {
			r.RoleMapper = make(map[string][]types.String, len(resp.RoleMapper))
			for roleMapperKey, roleMapperValue := range resp.RoleMapper {
				var roleMapperResult []types.String
				roleMapperResult = make([]types.String, 0, len(roleMapperValue))
				for _, v := range roleMapperValue {
					roleMapperResult = append(roleMapperResult, types.StringValue(v))
				}

				r.RoleMapper[roleMapperKey] = roleMapperResult
			}
		}
		r.System = types.BoolPointerValue(resp.System)
		r.Type = types.StringPointerValue(resp.Type)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *IdentityProviderResourceModel) ToOperationsAutomationCreateOrUpdateIdentityProviderRequest(ctx context.Context) (*operations.AutomationCreateOrUpdateIdentityProviderRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var domainKey string
	domainKey = r.DomainKey.ValueString()

	automationIdentityProvider, automationIdentityProviderDiags := r.ToSharedAutomationIdentityProviderInput(ctx)
	diags.Append(automationIdentityProviderDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.AutomationCreateOrUpdateIdentityProviderRequest{
		OrganizationID:             organizationID,
		EnvironmentID:              environmentID,
		DomainKey:                  domainKey,
		AutomationIdentityProvider: *automationIdentityProvider,
	}

	return &out, diags
}

func (r *IdentityProviderResourceModel) ToOperationsAutomationDeleteIdentityProviderRequest(ctx context.Context) (*operations.AutomationDeleteIdentityProviderRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var domainKey string
	domainKey = r.DomainKey.ValueString()

	var key string
	key = r.Key.ValueString()

	out := operations.AutomationDeleteIdentityProviderRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		DomainKey:      domainKey,
		Key:            key,
	}

	return &out, diags
}

func (r *IdentityProviderResourceModel) ToOperationsAutomationGetIdentityProviderRequest(ctx context.Context) (*operations.AutomationGetIdentityProviderRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var domainKey string
	domainKey = r.DomainKey.ValueString()

	var key string
	key = r.Key.ValueString()

	out := operations.AutomationGetIdentityProviderRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		DomainKey:      domainKey,
		Key:            key,
	}

	return &out, diags
}

func (r *IdentityProviderResourceModel) ToSharedAutomationIdentityProviderInput(ctx context.Context) (*shared.AutomationIdentityProviderInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	configuration := new(string)
	if !r.Configuration.IsUnknown() && !r.Configuration.IsNull() {
		*configuration = r.Configuration.ValueString()
	} else {
		configuration = nil
	}
	domainWhitelist := make([]string, 0, len(r.DomainWhitelist))
	for domainWhitelistIndex := range r.DomainWhitelist {
		domainWhitelist = append(domainWhitelist, r.DomainWhitelist[domainWhitelistIndex].ValueString())
	}
	groupMapper := make(map[string][]string)
	for groupMapperKey := range r.GroupMapper {
		groupMapperInst := make([]string, 0, len(r.GroupMapper[groupMapperKey]))
		for index := range r.GroupMapper[groupMapperKey] {
			groupMapperInst = append(groupMapperInst, r.GroupMapper[groupMapperKey][index].ValueString())
		}
		groupMapper[groupMapperKey] = groupMapperInst
	}
	var key string
	key = r.Key.ValueString()

	mappers := make(map[string]string)
	for mappersKey := range r.Mappers {
		var mappersInst string
		mappersInst = r.Mappers[mappersKey].ValueString()

		mappers[mappersKey] = mappersInst
	}
	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	roleMapper := make(map[string][]string)
	for roleMapperKey := range r.RoleMapper {
		roleMapperInst := make([]string, 0, len(r.RoleMapper[roleMapperKey]))
		for index1 := range r.RoleMapper[roleMapperKey] {
			roleMapperInst = append(roleMapperInst, r.RoleMapper[roleMapperKey][index1].ValueString())
		}
		roleMapper[roleMapperKey] = roleMapperInst
	}
	system := new(bool)
	if !r.System.IsUnknown() && !r.System.IsNull() {
		*system = r.System.ValueBool()
	} else {
		system = nil
	}
	typeVar := new(string)
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		*typeVar = r.Type.ValueString()
	} else {
		typeVar = nil
	}
	out := shared.AutomationIdentityProviderInput{
		Configuration:   configuration,
		DomainWhitelist: domainWhitelist,
		GroupMapper:     groupMapper,
		Key:             key,
		Mappers:         mappers,
		Name:            name,
		RoleMapper:      roleMapper,
		System:          system,
		Type:            typeVar,
	}

	return &out, diags
}
