// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1e7e86841cf3

package provider

import (
	"context"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/action"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/function"
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"
	"os"
)

var _ provider.Provider = (*AmProvider)(nil)
var _ provider.ProviderWithActions = (*AmProvider)(nil)
var _ provider.ProviderWithEphemeralResources = (*AmProvider)(nil)
var _ provider.ProviderWithFunctions = (*AmProvider)(nil)

type AmProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// AmProviderConfigureData describes provider configuration data passed to resources.
type AmProviderConfigureData struct {
	EnvironmentID  types.String `tfsdk:"environment_id"`
	OrganizationID types.String `tfsdk:"organization_id"`
	SDKClient      *sdk.GraviteeAm
}

// AmProviderModel describes the provider data model.
type AmProviderModel struct {
	BearerAuth     types.String `tfsdk:"bearer_auth"`
	EnvironmentID  types.String `tfsdk:"environment_id"`
	HTTPHeaders    types.Map    `tfsdk:"http_headers"`
	OrganizationID types.String `tfsdk:"organization_id"`
	ServerURL      types.String `tfsdk:"server_url"`
}

func (p *AmProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "am"
	resp.Version = p.version
}

func (p *AmProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bearer_auth": schema.StringAttribute{
				MarkdownDescription: `Authentication uses a bearer token: a JWT, or an opaque user service-account access token. Every operation is additionally permission-gated against the target organization, environment, and resource; a caller lacking the required permission receives a 403 response. Configurable via environment variable ` + "`" + `AM_SA_TOKEN` + "`" + `.`,
				Optional:            true,
				Sensitive:           true,
			},
			"environment_id": schema.StringAttribute{
				Description: `Identifier of the environment.`,
				Optional:    true,
			},
			"http_headers": schema.MapAttribute{
				Description: `HTTP headers to include in all requests`,
				ElementType: types.StringType,
				Optional:    true,
			},
			"organization_id": schema.StringAttribute{
				Description: `Identifier of the organization that owns the environment.`,
				Optional:    true,
			},
			"server_url": schema.StringAttribute{
				Description: `Server URL (defaults to http://localhost:8093/management/automation)`,
				Optional:    true,
			},
		},
		MarkdownDescription: `Gravitee: Gravitee Access Management Terraform Provider (alpha)` + "\n" +
			`` + "\n" +
			`You can manage with Terraform the following:` + "\n" +
			`* Domains` + "\n" +
			`* Certificates` + "\n" +
			`* Identity Providers` + "\n" +
			`* Reporters` + "\n" +
			`` + "\n" +
			`Compatible with Gravitee Access Management 4.12.0.`,
	}
}

func (p *AmProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data AmProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	serverUrl := data.ServerURL.ValueString()

	if serverUrl == "" && os.Getenv("AM_SERVER_URL") != "" {
		serverUrl = os.Getenv("AM_SERVER_URL")
	}

	if serverUrl == "" {
		serverUrl = "http://localhost:8093/management/automation"
	}

	if organizationIDEnvVar, ok := os.LookupEnv("AM_ORG_ID"); ok && data.OrganizationID.IsNull() {
		data.OrganizationID = types.StringValue(organizationIDEnvVar)
	}

	if data.OrganizationID.IsNull() {
		data.OrganizationID = types.StringValue(`DEFAULT`)
	}

	if environmentIDEnvVar, ok := os.LookupEnv("AM_ENV_ID"); ok && data.EnvironmentID.IsNull() {
		data.EnvironmentID = types.StringValue(environmentIDEnvVar)
	}

	if data.EnvironmentID.IsNull() {
		data.EnvironmentID = types.StringValue(`DEFAULT`)
	}
	security := shared.Security{}

	if !data.BearerAuth.IsUnknown() {
		security.BearerAuth = data.BearerAuth.ValueString()
	}

	if bearerAuthEnvVar := os.Getenv("AM_SA_TOKEN"); security.BearerAuth == "" && bearerAuthEnvVar != "" {
		security.BearerAuth = bearerAuthEnvVar
	}

	if security.BearerAuth == "" {
		resp.Diagnostics.AddError(
			"Missing Provider Security Configuration",
			"Either the environment variable AM_SA_TOKEN or provider configuration bearer_auth attribute must be configured.",
		)
	}

	providerHTTPTransportOpts := ProviderHTTPTransportOpts{
		SetHeaders: make(map[string]string),
		Transport:  http.DefaultTransport,
	}

	resp.Diagnostics.Append(data.HTTPHeaders.ElementsAs(ctx, &providerHTTPTransportOpts.SetHeaders, false)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpClient := http.DefaultClient
	httpClient.Transport = NewProviderHTTPTransport(providerHTTPTransportOpts)

	opts := []sdk.SDKOption{
		sdk.WithServerURL(serverUrl),
		sdk.WithSecurity(security),
		sdk.WithClient(httpClient),
	}

	if !data.OrganizationID.IsUnknown() && !data.OrganizationID.IsNull() {
		opts = append(opts, sdk.WithOrganizationID(data.OrganizationID.ValueString()))
	}

	if !data.EnvironmentID.IsUnknown() && !data.EnvironmentID.IsNull() {
		opts = append(opts, sdk.WithEnvironmentID(data.EnvironmentID.ValueString()))
	}

	client := sdk.New(opts...)
	configureData := &AmProviderConfigureData{
		EnvironmentID:  data.EnvironmentID,
		OrganizationID: data.OrganizationID,
		SDKClient:      client,
	}

	resp.ActionData = configureData
	resp.DataSourceData = configureData
	resp.EphemeralResourceData = configureData
	resp.ListResourceData = configureData
	resp.ResourceData = configureData
}

func (p *AmProvider) Functions(_ context.Context) []func() function.Function {
	return []func() function.Function{}
}

func (p *AmProvider) Actions(_ context.Context) []func() action.Action {
	return []func() action.Action{}
}

func (p *AmProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewCertificateResource,
		NewDomainResource,
		NewIdentityProviderResource,
		NewReporterResource,
	}
}

func (p *AmProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewCertificateDataSource,
		NewDomainDataSource,
		NewIdentityProviderDataSource,
		NewReporterDataSource,
	}
}

func (p *AmProvider) EphemeralResources(ctx context.Context) []func() ephemeral.EphemeralResource {
	return []func() ephemeral.EphemeralResource{}
}

func (p *AmProvider) ListResources(ctx context.Context) []func() list.ListResource {
	return []func() list.ListResource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &AmProvider{
			version: version,
		}
	}
}
