// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6aa5cc34a3da

package provider

import (
	"context"
	"github.com/gravitee-io/terraform-provider-am/internal/provider/typeconvert"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *ReporterResourceModel) RefreshFromSharedAutomationReporter(ctx context.Context, resp *shared.AutomationReporter) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Configuration = types.StringPointerValue(resp.Configuration)
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.DataType = types.StringPointerValue(resp.DataType)
		r.Enabled = types.BoolPointerValue(resp.Enabled)
		r.Key = types.StringValue(resp.Key)
		r.Name = types.StringPointerValue(resp.Name)
		r.System = types.BoolPointerValue(resp.System)
		r.Type = types.StringPointerValue(resp.Type)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *ReporterResourceModel) ToOperationsAutomationCreateOrUpdateReporterRequest(ctx context.Context) (*operations.AutomationCreateOrUpdateReporterRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var orgID string
	orgID = r.OrgID.ValueString()

	var envID string
	envID = r.EnvID.ValueString()

	var domainKey string
	domainKey = r.DomainKey.ValueString()

	automationReporter, automationReporterDiags := r.ToSharedAutomationReporterInput(ctx)
	diags.Append(automationReporterDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.AutomationCreateOrUpdateReporterRequest{
		OrgID:              orgID,
		EnvID:              envID,
		DomainKey:          domainKey,
		AutomationReporter: *automationReporter,
	}

	return &out, diags
}

func (r *ReporterResourceModel) ToOperationsAutomationDeleteReporterRequest(ctx context.Context) (*operations.AutomationDeleteReporterRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var orgID string
	orgID = r.OrgID.ValueString()

	var envID string
	envID = r.EnvID.ValueString()

	var domainKey string
	domainKey = r.DomainKey.ValueString()

	var key string
	key = r.Key.ValueString()

	out := operations.AutomationDeleteReporterRequest{
		OrgID:     orgID,
		EnvID:     envID,
		DomainKey: domainKey,
		Key:       key,
	}

	return &out, diags
}

func (r *ReporterResourceModel) ToOperationsAutomationGetReporterRequest(ctx context.Context) (*operations.AutomationGetReporterRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var orgID string
	orgID = r.OrgID.ValueString()

	var envID string
	envID = r.EnvID.ValueString()

	var domainKey string
	domainKey = r.DomainKey.ValueString()

	var key string
	key = r.Key.ValueString()

	out := operations.AutomationGetReporterRequest{
		OrgID:     orgID,
		EnvID:     envID,
		DomainKey: domainKey,
		Key:       key,
	}

	return &out, diags
}

func (r *ReporterResourceModel) ToSharedAutomationReporterInput(ctx context.Context) (*shared.AutomationReporterInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	configuration := new(string)
	if !r.Configuration.IsUnknown() && !r.Configuration.IsNull() {
		*configuration = r.Configuration.ValueString()
	} else {
		configuration = nil
	}
	enabled := new(bool)
	if !r.Enabled.IsUnknown() && !r.Enabled.IsNull() {
		*enabled = r.Enabled.ValueBool()
	} else {
		enabled = nil
	}
	var key string
	key = r.Key.ValueString()

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	system := new(bool)
	if !r.System.IsUnknown() && !r.System.IsNull() {
		*system = r.System.ValueBool()
	} else {
		system = nil
	}
	typeVar := new(string)
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		*typeVar = r.Type.ValueString()
	} else {
		typeVar = nil
	}
	out := shared.AutomationReporterInput{
		Configuration: configuration,
		Enabled:       enabled,
		Key:           key,
		Name:          name,
		System:        system,
		Type:          typeVar,
	}

	return &out, diags
}
