// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f1281e5ca4ae

package provider

import (
	"context"
	"github.com/gravitee-io/terraform-provider-am/internal/provider/customtypes"
	"github.com/gravitee-io/terraform-provider-am/internal/provider/typeconvert"
	tfTypes "github.com/gravitee-io/terraform-provider-am/internal/provider/types"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/operations"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *ReporterDataSourceModel) RefreshFromSharedAutomationReporter(ctx context.Context, resp *shared.AutomationReporter) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AttributeMappingEventTypes = make([]types.String, 0, len(resp.AttributeMappingEventTypes))
		for _, v := range resp.AttributeMappingEventTypes {
			r.AttributeMappingEventTypes = append(r.AttributeMappingEventTypes, types.StringValue(v))
		}
		r.AttributeMappings = []tfTypes.ReporterAttributeMapping{}

		for _, attributeMappingsItem := range resp.AttributeMappings {
			var attributeMappings tfTypes.ReporterAttributeMapping

			attributeMappings.ExportedName = types.StringPointerValue(attributeMappingsItem.ExportedName)
			attributeMappings.Expression = types.StringPointerValue(attributeMappingsItem.Expression)

			r.AttributeMappings = append(r.AttributeMappings, attributeMappings)
		}
		configurationValuable, configurationDiags := customtypes.MaskedJSONType{}.ValueFromString(ctx, types.StringPointerValue(resp.Configuration))
		diags.Append(configurationDiags...)
		r.Configuration = configurationValuable.(customtypes.MaskedJSON)
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.DataType = types.StringPointerValue(resp.DataType)
		r.Enabled = types.BoolPointerValue(resp.Enabled)
		r.Key = types.StringValue(resp.Key)
		r.Name = types.StringPointerValue(resp.Name)
		r.System = types.BoolPointerValue(resp.System)
		r.Type = types.StringPointerValue(resp.Type)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *ReporterDataSourceModel) ToOperationsAutomationGetReporterRequest(ctx context.Context) (*operations.AutomationGetReporterRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	organizationID := new(string)
	if !r.OrganizationID.IsUnknown() && !r.OrganizationID.IsNull() {
		*organizationID = r.OrganizationID.ValueString()
	} else {
		organizationID = nil
	}
	environmentID := new(string)
	if !r.EnvironmentID.IsUnknown() && !r.EnvironmentID.IsNull() {
		*environmentID = r.EnvironmentID.ValueString()
	} else {
		environmentID = nil
	}
	var domainKey string
	domainKey = r.DomainKey.ValueString()

	var key string
	key = r.Key.ValueString()

	out := operations.AutomationGetReporterRequest{
		OrganizationID: organizationID,
		EnvironmentID:  environmentID,
		DomainKey:      domainKey,
		Key:            key,
	}

	return &out, diags
}
