// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e5e89c5cc824

package provider

import (
	"context"
	"fmt"
	"github.com/gravitee-io/terraform-provider-am/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &ReporterDataSource{}
var _ datasource.DataSourceWithConfigure = &ReporterDataSource{}

func NewReporterDataSource() datasource.DataSource {
	return &ReporterDataSource{}
}

// ReporterDataSource is the data source implementation.
type ReporterDataSource struct {
	// Provider configured SDK client.
	client *sdk.GraviteeAm

	// Identifier of the environment.
	EnvironmentID types.String `tfsdk:"environment_id"`

	// Identifier of the organization that owns the environment.
	OrganizationID types.String `tfsdk:"organization_id"`
}

// ReporterDataSourceModel describes the data model.
type ReporterDataSourceModel struct {
	Configuration  types.String `tfsdk:"configuration"`
	CreatedAt      types.String `tfsdk:"created_at"`
	DataType       types.String `tfsdk:"data_type"`
	DomainKey      types.String `tfsdk:"domain_key"`
	Enabled        types.Bool   `tfsdk:"enabled"`
	EnvironmentID  types.String `tfsdk:"environment_id"`
	Key            types.String `tfsdk:"key"`
	Name           types.String `tfsdk:"name"`
	OrganizationID types.String `tfsdk:"organization_id"`
	System         types.Bool   `tfsdk:"system"`
	Type           types.String `tfsdk:"type"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
}

// Metadata returns the data source type name.
func (r *ReporterDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_reporter"
}

// Schema defines the schema for the data source.
func (r *ReporterDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Reporter DataSource",

		Attributes: map[string]schema.Attribute{
			"configuration": schema.StringAttribute{
				Computed:    true,
				Sensitive:   true,
				Description: `Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected reporter type.`,
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.`,
			},
			"data_type": schema.StringAttribute{
				Computed:    true,
				Description: `Category of data the reporter handles, derived from its type. Read-only.`,
			},
			"domain_key": schema.StringAttribute{
				Required:    true,
				Description: `Key of the domain: its stable, immutable Automation identifier within the environment.`,
			},
			"enabled": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether the reporter is enabled.`,
			},
			"environment_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `Identifier of the environment.`,
			},
			"key": schema.StringAttribute{
				Required:    true,
				Description: `Stable, immutable identifier for the reporter within its domain. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the reporter on create-or-update.`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthBetween(1, 255),
				},
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Human-readable name of the reporter.`,
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `Identifier of the organization that owns the environment.`,
			},
			"system": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether this is the domain's system reporter. Immutable after creation. When true, only key is required; the reporter is built from the domains.reporters.default.* and repository system settings and the name, type, and configuration fields are ignored.`,
			},
			"type": schema.StringAttribute{
				Computed:    true,
				Description: `Reporter plugin type identifier. Immutable after creation.`,
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.`,
			},
		},
	}
}

func (r *ReporterDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*AmProviderConfigureData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *AmProviderConfigureData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.EnvironmentID = providerData.EnvironmentID
	r.OrganizationID = providerData.OrganizationID
	r.client = providerData.SDKClient
}

func (r *ReporterDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *ReporterDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	if (data.EnvironmentID.IsNull() || data.EnvironmentID.IsUnknown()) && !r.EnvironmentID.IsUnknown() {
		data.EnvironmentID = r.EnvironmentID
	}

	if (data.OrganizationID.IsNull() || data.OrganizationID.IsUnknown()) && !r.OrganizationID.IsUnknown() {
		data.OrganizationID = r.OrganizationID
	}

	request, requestDiags := data.ToOperationsAutomationGetReporterRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Reporters.AutomationGetReporter(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AutomationReporter != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedAutomationReporter(ctx, res.AutomationReporter)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
