// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e361b9bdc5c7

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AutomationCIBASettings struct {
	AuthReqExpiry        types.Int32 `tfsdk:"auth_req_expiry"`
	BindingMessageLength types.Int32 `tfsdk:"binding_message_length"`
	Enabled              types.Bool  `tfsdk:"enabled"`
	TokenReqInterval     types.Int32 `tfsdk:"token_req_interval"`
}
