// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7a6836caefaf

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AutomationClientRegistrationSettings struct {
	AllowHTTPSchemeRedirectURI               types.Bool     `tfsdk:"allow_http_scheme_redirect_uri"`
	AllowLocalhostRedirectURI                types.Bool     `tfsdk:"allow_localhost_redirect_uri"`
	AllowRedirectURIParamsExpressionLanguage types.Bool     `tfsdk:"allow_redirect_uri_params_expression_language"`
	AllowWildCardRedirectURI                 types.Bool     `tfsdk:"allow_wild_card_redirect_uri"`
	AllowedScopes                            []types.String `tfsdk:"allowed_scopes"`
	AllowedScopesEnabled                     types.Bool     `tfsdk:"allowed_scopes_enabled"`
	ClientTemplateEnabled                    types.Bool     `tfsdk:"client_template_enabled"`
	DefaultScopes                            []types.String `tfsdk:"default_scopes"`
	DynamicClientRegistrationEnabled         types.Bool     `tfsdk:"dynamic_client_registration_enabled"`
	OpenDynamicClientRegistrationEnabled     types.Bool     `tfsdk:"open_dynamic_client_registration_enabled"`
}
