// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 53660f187554

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AutomationAccountSettings struct {
	AccountBlockedDuration                      types.Int32  `tfsdk:"account_blocked_duration"`
	AutoLoginAfterRegistration                  types.Bool   `tfsdk:"auto_login_after_registration"`
	AutoLoginAfterResetPassword                 types.Bool   `tfsdk:"auto_login_after_reset_password"`
	CompleteRegistrationWhenResetPassword       types.Bool   `tfsdk:"complete_registration_when_reset_password"`
	DefaultIdentityProviderForRegistration      types.String `tfsdk:"default_identity_provider_for_registration"`
	DeletePasswordlessDevicesAfterResetPassword types.Bool   `tfsdk:"delete_passwordless_devices_after_reset_password"`
	DynamicUserRegistration                     types.Bool   `tfsdk:"dynamic_user_registration"`
	Inherited                                   types.Bool   `tfsdk:"inherited"`
	LoginAttemptsDetectionEnabled               types.Bool   `tfsdk:"login_attempts_detection_enabled"`
	LoginAttemptsResetTime                      types.Int32  `tfsdk:"login_attempts_reset_time"`
	MaxLoginAttempts                            types.Int32  `tfsdk:"max_login_attempts"`
	MfaChallengeAttemptsDetectionEnabled        types.Bool   `tfsdk:"mfa_challenge_attempts_detection_enabled"`
	MfaChallengeAttemptsResetTime               types.Int32  `tfsdk:"mfa_challenge_attempts_reset_time"`
	MfaChallengeMaxAttempts                     types.Int32  `tfsdk:"mfa_challenge_max_attempts"`
	MfaChallengeSendVerifyAlertEmail            types.Bool   `tfsdk:"mfa_challenge_send_verify_alert_email"`
	RedirectURIAfterRegistration                types.String `tfsdk:"redirect_uri_after_registration"`
	RedirectURIAfterResetPassword               types.String `tfsdk:"redirect_uri_after_reset_password"`
	RememberMe                                  types.Bool   `tfsdk:"remember_me"`
	RememberMeDuration                          types.Int32  `tfsdk:"remember_me_duration"`
	ResetPasswordConfirmIdentity                types.Bool   `tfsdk:"reset_password_confirm_identity"`
	ResetPasswordCustomForm                     types.Bool   `tfsdk:"reset_password_custom_form"`
	ResetPasswordCustomFormFields               []FormField  `tfsdk:"reset_password_custom_form_fields"`
	ResetPasswordInvalidateTokens               types.Bool   `tfsdk:"reset_password_invalidate_tokens"`
	SendRecoverAccountEmail                     types.Bool   `tfsdk:"send_recover_account_email"`
	SendVerifyRegistrationAccountEmail          types.Bool   `tfsdk:"send_verify_registration_account_email"`
}
