// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1a7d62becc7a

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AutomationSamlSettings struct {
	Certificate types.String `tfsdk:"certificate"`
	Enabled     types.Bool   `tfsdk:"enabled"`
	EntityID    types.String `tfsdk:"entity_id"`
}
