// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 330898f8d300

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AutomationCertificateSettings struct {
	FallbackCertificate types.String `tfsdk:"fallback_certificate"`
}
