// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7299c421ace8

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CorsSettings struct {
	AllowCredentials types.Bool     `tfsdk:"allow_credentials"`
	AllowedHeaders   []types.String `tfsdk:"allowed_headers"`
	AllowedMethods   []types.String `tfsdk:"allowed_methods"`
	AllowedOrigins   []types.String `tfsdk:"allowed_origins"`
	Enabled          types.Bool     `tfsdk:"enabled"`
	MaxAge           types.Int32    `tfsdk:"max_age"`
}
