// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9dfb1902ba89

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CspSettings struct {
	Directives        []types.String `tfsdk:"directives"`
	Enabled           types.Bool     `tfsdk:"enabled"`
	Inherited         types.Bool     `tfsdk:"inherited"`
	ReportOnly        types.Bool     `tfsdk:"report_only"`
	ScriptInlineNonce types.Bool     `tfsdk:"script_inline_nonce"`
}
