// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cd49f34b6efd

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DryRunError struct {
	Message  types.String `tfsdk:"message"`
	Severity types.String `tfsdk:"severity"`
}
