// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7baf2277045c

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type FormField struct {
	Key   types.String `tfsdk:"key"`
	Label types.String `tfsdk:"label"`
	Type  types.String `tfsdk:"type"`
}
