// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ebed787a0c32

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type IDJagSettings struct {
	LaxValidation types.Bool `tfsdk:"lax_validation"`
}
