// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ad58b29021b5

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type KeyRetrievalSettings struct {
	AllowPrivateIPAddress types.Bool  `tfsdk:"allow_private_ip_address"`
	AllowUnsecuredHTTPURI types.Bool  `tfsdk:"allow_unsecured_http_uri"`
	CacheMaxEntries       types.Int32 `tfsdk:"cache_max_entries"`
	CacheTTLSeconds       types.Int32 `tfsdk:"cache_ttl_seconds"`
	FetchTimeoutMs        types.Int32 `tfsdk:"fetch_timeout_ms"`
	MaxResponseSizeKb     types.Int32 `tfsdk:"max_response_size_kb"`
}
