// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: efd51f82cdf9

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type LoginSettings struct {
	CertificateBasedAuthEnabled        types.Bool   `tfsdk:"certificate_based_auth_enabled"`
	CertificateBasedAuthURL            types.String `tfsdk:"certificate_based_auth_url"`
	ForgotPasswordEnabled              types.Bool   `tfsdk:"forgot_password_enabled"`
	HideForm                           types.Bool   `tfsdk:"hide_form"`
	IdentifierFirstEnabled             types.Bool   `tfsdk:"identifier_first_enabled"`
	Inherited                          types.Bool   `tfsdk:"inherited"`
	MagicLinkAuthEnabled               types.Bool   `tfsdk:"magic_link_auth_enabled"`
	PasswordlessDeviceNamingEnabled    types.Bool   `tfsdk:"passwordless_device_naming_enabled"`
	PasswordlessEnabled                types.Bool   `tfsdk:"passwordless_enabled"`
	PasswordlessEnforcePasswordEnabled types.Bool   `tfsdk:"passwordless_enforce_password_enabled"`
	PasswordlessEnforcePasswordMaxAge  types.Int32  `tfsdk:"passwordless_enforce_password_max_age"`
	PasswordlessRememberDeviceEnabled  types.Bool   `tfsdk:"passwordless_remember_device_enabled"`
	RegisterEnabled                    types.Bool   `tfsdk:"register_enabled"`
	RememberMeEnabled                  types.Bool   `tfsdk:"remember_me_enabled"`
	ResetPasswordOnExpiration          types.Bool   `tfsdk:"reset_password_on_expiration"`
}
