// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c765894919af

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PasswordSettings struct {
	ExcludePasswordsInDictionary     types.Bool  `tfsdk:"exclude_passwords_in_dictionary"`
	ExcludeUserProfileInfoInPassword types.Bool  `tfsdk:"exclude_user_profile_info_in_password"`
	ExpiryDuration                   types.Int32 `tfsdk:"expiry_duration"`
	IncludeNumbers                   types.Bool  `tfsdk:"include_numbers"`
	IncludeSpecialCharacters         types.Bool  `tfsdk:"include_special_characters"`
	Inherited                        types.Bool  `tfsdk:"inherited"`
	LettersInMixedCase               types.Bool  `tfsdk:"letters_in_mixed_case"`
	MaxConsecutiveLetters            types.Int32 `tfsdk:"max_consecutive_letters"`
	MaxLength                        types.Int32 `tfsdk:"max_length"`
	MinLength                        types.Int32 `tfsdk:"min_length"`
	OldPasswords                     types.Int32 `tfsdk:"old_passwords"`
	PasswordHistoryEnabled           types.Bool  `tfsdk:"password_history_enabled"`
}
