// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 93a88176d7a5

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ReporterAttributeMapping struct {
	ExportedName types.String `tfsdk:"exported_name"`
	Expression   types.String `tfsdk:"expression"`
}
