// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1f47fb77a77a

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SCIMSettings struct {
	Enabled             types.Bool   `tfsdk:"enabled"`
	IdpSelectionEnabled types.Bool   `tfsdk:"idp_selection_enabled"`
	IdpSelectionRule    types.String `tfsdk:"idp_selection_rule"`
}
