// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 455274b00216

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SelfServiceAccountManagementSettings struct {
	Enabled       types.Bool             `tfsdk:"enabled"`
	ResetPassword *ResetPasswordSettings `tfsdk:"reset_password"`
}
