// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1788cb0efc39

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SpiffeDomainSettings struct {
	AllowPrivateIPAddress    types.Bool     `tfsdk:"allow_private_ip_address"`
	AllowUnsecuredHTTPURI    types.Bool     `tfsdk:"allow_unsecured_http_uri"`
	CacheMaxEntries          types.Int32    `tfsdk:"cache_max_entries"`
	CacheTTLSeconds          types.Int32    `tfsdk:"cache_ttl_seconds"`
	ClockSkewSeconds         types.Int32    `tfsdk:"clock_skew_seconds"`
	DefaultAllowedAlgorithms []types.String `tfsdk:"default_allowed_algorithms"`
	Enabled                  types.Bool     `tfsdk:"enabled"`
	FetchTimeoutMs           types.Int32    `tfsdk:"fetch_timeout_ms"`
	MaxJwtLifetimeSeconds    types.Int32    `tfsdk:"max_jwt_lifetime_seconds"`
	MaxResponseSizeKb        types.Int32    `tfsdk:"max_response_size_kb"`
}
