// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 31d6b1c04178

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TokenExchangeOAuthSettings struct {
	Inherited     types.Bool   `tfsdk:"inherited"`
	ScopeHandling types.String `tfsdk:"scope_handling"`
}
