// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3442a5f16d27

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type UMASettings struct {
	Enabled types.Bool `tfsdk:"enabled"`
}
