// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ac76d998d36d

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type UserBindingCriterion struct {
	Attribute  types.String `tfsdk:"attribute"`
	Expression types.String `tfsdk:"expression"`
}
