// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 275dba020d86

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type VirtualHost struct {
	Host               types.String `tfsdk:"host"`
	OverrideEntrypoint types.Bool   `tfsdk:"override_entrypoint"`
	Path               types.String `tfsdk:"path"`
}
