// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c42617f3b7fc

package types

type WebProtectionSettings struct {
	Csp    *CspSettings           `tfsdk:"csp"`
	Xframe *XFrameSettings        `tfsdk:"xframe"`
	XSS    *XSSProtectionSettings `tfsdk:"xss"`
}
