// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c501ad19864b

package globals

type Globals struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `pathParam:"style=simple,explode=false,name=envId"`
}

func (g *Globals) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *Globals) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}
