// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c501ad19864b

package globals

import (
	"github.com/gravitee-io/terraform-provider-am/internal/sdk/internal/utils"
)

type Globals struct {
	// Identifier of the organization that owns the environment.
	OrganizationID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=orgId"`
	// Identifier of the environment.
	EnvironmentID *string `default:"DEFAULT" pathParam:"style=simple,explode=false,name=envId"`
}

func (g Globals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Globals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *Globals) GetOrganizationID() *string {
	if g == nil {
		return nil
	}
	return g.OrganizationID
}

func (g *Globals) GetEnvironmentID() *string {
	if g == nil {
		return nil
	}
	return g.EnvironmentID
}
